// Embeds the converted legacy dataset (gzip JSON) into src/store/legacy-data.ts as base64.
// Usage: node scripts/embed-legacy.mjs <path-to-legacy-demo.json.gz>
import fs from 'fs';
const src = process.argv[2];
const out = new URL('../src/store/legacy-data.ts', import.meta.url);
if (!src || !fs.existsSync(src)) {
  fs.writeFileSync(out, "// No legacy dataset embedded.\nexport const LEGACY_GZ_B64: string = '';\n");
  console.log('wrote empty legacy-data.ts');
} else {
  const b64 = fs.readFileSync(src).toString('base64');
  fs.writeFileSync(out, `// Generated by scripts/embed-legacy.mjs from ${src.split('/').pop()} – SK Logistics data converted from ERPdatabase20250608.bak\nexport const LEGACY_GZ_B64: string = '${b64}';\n`);
  console.log('embedded', (b64.length / 1e6).toFixed(2), 'MB base64');
}
