// Training Academy content – system & management area: Help/Training Academy, Communication, Reports & prints,
// Masters, Users & Access and Administration (incl. admin training dashboards).
// Every statement here describes what the ERP code does today (or the rebuilt behaviour of help, access/users,
// admin/training and admin/training-coverage as specified by the lead developer).
import type { ScreenTraining, Question, Exercise, Workflow, Lesson } from '../types';

const ALL = ['SA', 'AD', 'OP', 'BU', 'AC', 'CC', 'CO', 'SI', 'HR'] as const;

// ---------------------------------------------------------------------------------------------------------------
// Screens
// ---------------------------------------------------------------------------------------------------------------
export const screens: ScreenTraining[] = [
  // ---------------- Help & Training (Training Academy) ----------------
  {
    id: 'help',
    module: 'admin',
    title: 'Help & Training (Training Academy)',
    purpose: 'Your personal Training Academy. It shows the training plan for your role, what you have finished, and how close you are to being ready to work alone.',
    why: 'You learn each screen with short lessons, Hinglish audio, safe practice on sample data and quizzes. Your manager sees your progress and readiness.',
    when: 'Every day in your first weeks, and any time you start using a new screen or forget how something works.',
    roles: [...ALL],
    upstream: ['access/password', 'dashboard'],
    downstream: ['work', 'board', 'dashboard'],
    before: 'An administrator creates your login. At first sign-in you change the temporary password and see the welcome for your role.',
    after: 'When your lessons, practice and assessment are done, your readiness becomes Ready. Your manager checks it in Admin › Training dashboard.',
    prerequisites: ['You can sign in with your own username and password.'],
    actions: [
      'Follow your role curriculum in order: Getting Started → Your Role → Your Daily Work → Module Training → End-to-End Workflows → Practice Exercises → Assessments → Glossary (managers also get Manager Training).',
      'Open a lesson, read it, and press Listen to hear the Hinglish audio.',
      'Start a practice exercise: read the Task and the Expected result, do the work on the practice screen, then check – the result is Pass or Needs correction.',
      'Take a quiz. Your attempts and best score are saved; you pass when you reach the passing score shown on the quiz.',
      'Use the Glossary to look up words like LR, POD, GRN, DGRN, LDC, TBB and To Pay.',
    ],
    records: ['Your lesson progress, practice results, quiz attempts and best scores – saved on the server against your employee login.'],
    validations: [
      'A quiz counts as passed only when your score reaches its passing score.',
      'A practice step shows Pass only when the checker finds the expected change in the practice data, made after you started the exercise.',
    ],
    mistakes: [
      'Doing practice work on the live screens instead of in practice mode – live work changes real company data.',
      'Guessing quiz answers to finish fast – wrong answers are recorded as failed topics and your manager may assign retraining.',
      'Skipping Getting Started – it explains My Work, the Order Board and search, which every later lesson uses.',
    ],
    warnings: ['Practice mode uses separate sample data in your browser. Nothing you do in practice is saved to the shared ERP data, and practice records never appear in reports.'],
    shortcuts: ['The ? button in the top bar opens Help & Training from any screen.', 'The Guide button turns the yellow page tips on or off.'],
    statuses: [
      { status: 'Not Started', meaning: 'No lesson opened yet.' },
      { status: 'Learning', meaning: 'Lessons are in progress.' },
      { status: 'Practising', meaning: 'Practice exercises are in progress.' },
      { status: 'Assessment Pending', meaning: 'Lessons and practice done; the assessment quiz is not passed yet.' },
      { status: 'Ready', meaning: 'Curriculum and assessment passed – ready to work without supervision.' },
      { status: 'Pass / Needs correction', meaning: 'Result of one practice step: your action matched the expected result, or it did not and you should try again.' },
    ],
    example: 'Sunita joins the Jalgaon branch as a Branch User. On day one she finishes Getting Started and Your Role, practises a booking on sample data, and on day three passes the Booking quiz. Her readiness moves from Learning to Ready.',
    walkthrough: [
      { title: 'Check your dashboard', body: 'The top shows your role curriculum, your progress and your readiness status.' },
      { title: 'Open the next lesson', body: 'Lessons are in order. Read the sections and press Listen for the Hinglish audio.' },
      { title: 'Practise safely', body: 'Start a practice exercise. Read Task and Expected, do the work, then see Your action and the result: Pass or Needs correction.' },
      { title: 'Take the quiz', body: 'Answer the questions. The explanation after each answer teaches the rule. Retake to improve your best score.' },
      { title: 'Finish the curriculum', body: 'When every section is complete and the assessment is passed, your readiness becomes Ready.' },
    ],
    related: ['access/password', 'work', 'board', 'dashboard'],
    audio: [
      'यह आपकी Training Academy है — आपके role के हिसाब से पूरी training यहीं है।',
      'ऊपर दिखता है कि आपने कितना पूरा किया, और आप काम के लिए कितने ready हैं।',
      'हर lesson पढ़िए, या Listen दबाकर सुनिए।',
      'Practice में sample data पर काम कीजिए — वहाँ गलती से कोई असली record नहीं बिगड़ता।',
      'आख़िर में quiz दीजिए। Passing score आते ही आपका status Ready हो जाएगा।',
      'आपकी progress server पर save होती है, इसलिए manager भी इसे देख सकते हैं।',
    ],
    quiz: ['q.admin.practice-isolated', 'q.admin.readiness-meaning'],
    minutes: 5,
  },

  // ---------------- Communication ----------------
  {
    id: 'communication',
    module: 'comms',
    title: 'Team Chat',
    purpose: 'Internal messaging for work: team discussions, direct messages and employee enquiries, with ERP references such as an LR number attached to a message.',
    why: 'Work conversations stay inside the ERP, linked to the LR, bill or trip they are about, and are recorded for administrators.',
    when: 'When you need another person or team to act on a consignment, a bill or any ERP record, or need an answer from a colleague.',
    roles: [...ALL],
    upstream: ['work', 'board'],
    downstream: ['communication/tasks', 'communication/enquiries'],
    before: 'You notice something that needs another person – for example a late card on the Order Board.',
    after: 'If someone must do a job, assign a task from the right-hand panel; it appears in Assigned Tasks.',
    prerequisites: ['The people you want to add must have active login accounts.'],
    actions: [
      'Start a conversation: choose Team discussion, Direct message or Employee enquiry, type a Subject, select participants and press Create conversation.',
      'Select a conversation on the left and write your message. Press Send, or Ctrl+Enter.',
      'Attach an ERP reference: type the reference type (for example LR) and the reference ID or LR number before sending.',
      'Assign an ERP task from the right panel: title, description, assignee, priority (low, normal, high, urgent) and due date.',
      'Use Search conversations to find a discussion by subject, type or participant.',
    ],
    records: ['Conversations, members, messages and tasks in PostgreSQL. Every create, send and task change is written to the audit log.'],
    validations: [
      'A conversation needs a Subject – otherwise “Add a subject”.',
      'An empty message cannot be sent; Send stays disabled.',
      'A task needs a selected conversation and a title – otherwise “Select a conversation and add a task title”.',
      'Tasks can be assigned only to active users.',
    ],
    mistakes: [
      'Writing “check this LR” without the LR number in the reference – the reader has to search for it.',
      'Asking for work in chat without assigning a task – nobody owns it and it is not tracked.',
      'Using chat for passwords – never send a password in a message; messages are kept in the audit log.',
    ],
    warnings: ['Messages refresh automatically every few seconds (no push notification). Press Refresh if you are waiting for a reply.', 'Administrators can read every conversation for oversight.'],
    shortcuts: ['Ctrl+Enter sends the message.'],
    fields: [
      { name: 'Conversation type', help: 'Team discussion (group), Direct message, or Employee enquiry.' },
      { name: 'ERP ref type / Reference ID', help: 'Optional link to a record, e.g. type “LR” and “SKT/JL/10419”. Shown under the message.' },
      { name: 'Priority', help: 'low, normal, high or urgent – for tasks.' },
    ],
    example: 'LR SKT/JL/10419 shows red on the Order Board with “POD not received”. The customer-care user opens a Direct message to the branch user, attaches LR SKT/JL/10419 and assigns a task “Collect signed POD” due tomorrow.',
    walkthrough: [
      { title: 'Pick or start a conversation', body: 'Select from the left list, or fill Start conversation at the bottom of it.' },
      { title: 'Write with a reference', body: 'Type the message, add ERP ref type and Reference ID, and press Send.' },
      { title: 'Assign the job', body: 'If someone must act, fill Assign ERP task on the right and press Assign task.' },
      { title: 'Follow up', body: 'Check Assigned Tasks for status changes.' },
    ],
    related: ['communication/tasks', 'communication/enquiries', 'board', 'work'],
    audio: [
      'यह Team Chat है — काम की बात यहीं कीजिए, WhatsApp पर नहीं।',
      'Message के साथ LR number जैसा ERP reference ज़रूर जोड़िए, ताकि पढ़ने वाले को तुरंत पता चले।',
      'अगर किसी को काम करना है, तो दाईं तरफ़ से task assign कीजिए।',
      'Messages हर कुछ seconds में अपने आप refresh होते हैं।',
      'Chat में कभी password मत भेजिए — हर message record होता है।',
    ],
    quiz: ['q.comms.reference', 'q.comms.audit-access'],
    minutes: 4,
  },
  {
    id: 'communication/tasks',
    module: 'comms',
    title: 'Assigned Tasks',
    purpose: 'List of tasks created from conversations – who it is assigned to, priority and status.',
    why: 'A task gives one clear owner and a status, so requests from chat do not get lost.',
    when: 'At the start and end of the day, and when someone asks you about a job you were given.',
    roles: [...ALL],
    upstream: ['communication'],
    downstream: ['work', 'communication'],
    before: 'A task is assigned from a conversation in Team Chat.',
    after: 'When finished, set it to done. The creator and other participants see the new status.',
    prerequisites: ['You are a participant of the conversation the task belongs to (administrators see all tasks).'],
    actions: [
      'Read each task card: title, conversation subject, assignee and priority.',
      'Change the status from the drop-down: todo, in progress, blocked, done, cancelled.',
      'Open the conversation to discuss a blocked task.',
    ],
    records: ['Task status, assignee, priority and due date; each change increases the task version and is audited.'],
    validations: ['If someone else changed the task after you loaded it, the update is refused with “Task changed by another user”. Refresh and try again.'],
    mistakes: [
      'Leaving a finished task in todo – the requester keeps chasing you.',
      'Marking a task done when it is blocked by someone else – use blocked and write the reason in the conversation.',
    ],
    statuses: [
      { status: 'todo', meaning: 'Not started.' },
      { status: 'in progress', meaning: 'Being worked on.' },
      { status: 'blocked', meaning: 'Cannot continue – waiting on someone or something.' },
      { status: 'done', meaning: 'Finished.' },
      { status: 'cancelled', meaning: 'No longer needed.' },
    ],
    walkthrough: [
      { title: 'Open Assigned Tasks', body: 'Tasks from all your conversations are listed, newest change first.' },
      { title: 'Update the status', body: 'Pick the new status in the drop-down; it saves immediately.' },
      { title: 'Explain blocks', body: 'If blocked, write why in the conversation so the requester knows.' },
    ],
    related: ['communication', 'work'],
    audio: [
      'यहाँ वो सारे tasks हैं जो chat से assign हुए हैं।',
      'काम शुरू करें तो in progress, ख़त्म हो तो done कीजिए।',
      'अगर काम अटका है तो blocked चुनिए, और chat में कारण लिखिए।',
      'अगर message आए कि task किसी और ने बदल दिया है, तो Refresh करके फिर से status बदलिए।',
    ],
    quiz: ['q.comms.task-conflict'],
    minutes: 3,
  },
  {
    id: 'communication/enquiries',
    module: 'comms',
    title: 'Employee Enquiries',
    purpose: 'Questions raised by employees as Employee enquiry conversations, visible to their participants and to administrators.',
    why: 'An enquiry keeps a staff question (HR, access, process) in one recorded thread instead of scattered calls.',
    when: 'When you have a question for HR, an administrator or another department and want a written answer.',
    roles: [...ALL],
    upstream: ['communication'],
    downstream: ['communication/tasks'],
    before: 'You choose “Employee enquiry” as the conversation type when starting a conversation.',
    after: 'The person who answers can assign a task if work is needed.',
    prerequisites: [],
    actions: [
      'Create the enquiry from the Start conversation panel: type Employee enquiry, a clear Subject, and the people who should answer.',
      'Read and reply in the conversation like any chat.',
    ],
    records: ['Enquiry conversations and messages, with Open/Closed shown on the conversation header.'],
    validations: ['A Subject is required.'],
    mistakes: ['Writing a vague subject such as “Problem” – write “Cannot see Billing menu” so the right person picks it up.'],
    walkthrough: [
      { title: 'Start an enquiry', body: 'In Start conversation choose Employee enquiry, write the subject and pick the people.' },
      { title: 'Explain clearly', body: 'Write what you tried, the screen name and any LR or bill number.' },
      { title: 'Watch for the answer', body: 'The conversation shows replies; the header shows Open or Closed.' },
    ],
    related: ['communication', 'communication/tasks'],
    audio: [
      'कोई सवाल हो — HR, access या काम के तरीके के बारे में — तो Employee enquiry बनाइए।',
      'Subject साफ़ लिखिए, जैसे Billing menu नहीं दिख रहा।',
      'जवाब उसी conversation में आएगा, और administrator भी इसे देख सकते हैं।',
    ],
    quiz: ['q.comms.reference'],
    minutes: 2,
  },
  {
    id: 'communication/audit',
    module: 'comms',
    title: 'Communication Oversight',
    purpose: 'Administrator audit trail of communication: who created conversations, sent messages and created or changed tasks, and when.',
    why: 'Management can check that work requests were made and followed up, and review a dispute with facts.',
    when: 'When investigating a complaint, a missed handover, or during a periodic review.',
    roles: ['SA', 'AD'],
    upstream: ['communication', 'communication/tasks'],
    downstream: ['communication'],
    before: 'Staff use Team Chat and tasks; every action writes an audit event.',
    after: 'Follow up with the people involved, or open the conversation (administrators can open every conversation).',
    prerequisites: ['A Super Admin, Admin or ERP Manager login. The server checks this; other users get “Administrator permission required” even if they type the address.'],
    actions: ['Read the latest 500 communication events: When, Actor, Action, Entity and Details.'],
    records: ['Read-only view of audit events whose entity is a communication conversation, message or task.'],
    validations: ['Access is enforced by the API, not only by the menu.'],
    mistakes: ['Reading staff conversations without a work reason – oversight is for audit and disputes, not general monitoring.'],
    fields: [
      { name: 'Action', help: 'create (conversation or task), send (message), update (task change).' },
      { name: 'Entity', help: 'communication_conversation, communication_message or communication_task with its number.' },
    ],
    walkthrough: [
      { title: 'Open the oversight list', body: 'Newest events first, up to 500.' },
      { title: 'Find the event', body: 'Look at Actor, Action and Entity; Details shows the saved state.' },
      { title: 'Act', body: 'Talk to the people involved or open the conversation from Team Chat.' },
    ],
    related: ['communication', 'communication/tasks', 'access/users'],
    audio: [
      'यह Communication Oversight है — सिर्फ़ administrators के लिए।',
      'यहाँ दिखता है कि किसने कब conversation बनाया, message भेजा या task बदला।',
      'Server ख़ुद check करता है, इसलिए बाकी users को यह data नहीं मिलता।',
      'इसे जाँच और शिकायत के लिए इस्तेमाल कीजिए, रोज़ की निगरानी के लिए नहीं।',
    ],
    quiz: ['q.comms.audit-access'],
    minutes: 3,
  },

  // ---------------- Reports & prints ----------------
  {
    id: 'reports',
    module: 'reports',
    title: 'Reports & MIS',
    purpose: 'All 42 reports from the old system, grouped as Operations, Rail, Warehouse, Fleet, Performance, Finance and Workshop, each with filters, KPIs, chart, table and export.',
    why: 'Reports answer management questions – outstanding, rake profitability, vehicle performance, pending POD – from the same data the screens use.',
    when: 'For daily follow-up lists (pending acknowledgment, pending log slips), month-end MIS and when a customer or manager asks for figures.',
    roles: ['SA', 'AD', 'OP', 'BU', 'AC', 'CC', 'CO', 'SI'],
    upstream: ['dashboard'],
    downstream: ['prints', 'fin/receivables', 'ops/lr'],
    before: 'The transactions (LRs, rakes, bills, trips) are entered on the operational screens.',
    after: 'Export to Excel to share, or open a row to go to the record and act on it.',
    prerequisites: ['Reports & MIS is in your role menu.'],
    actions: [
      'Use Find a report to search by name or description.',
      'Open a report, set the filters (date range, branch, customer, status …) and press Search.',
      'Read the KPIs and chart, then the table. Click a row (where available) to open that record.',
      'Press Excel to download the table as a CSV file; Print uses the browser print.',
      'Reset clears all filters.',
    ],
    records: ['Reports only read data; they never change records.'],
    validations: ['Filters apply only after you press Search.', 'Reports with a date filter start with the last 60 days.'],
    mistakes: [
      'Changing filters and reading the old numbers because Search was not pressed.',
      'Sending a report for the wrong period – check From and To before exporting.',
      'Expecting the PDF button to download a file – in this version it only shows a message; use Print or Excel.',
    ],
    warnings: ['Some report cards (stock, damage/shortage, quality control, client outstanding, ledger, rate matrix) open the live working screen instead of a separate report.'],
    example: 'At month end the accounts manager opens Client outstanding, which opens Receivables, and the operations head opens Pending acknowledgment summary to chase PODs before billing.',
    walkthrough: [
      { title: 'Find the report', body: 'Scroll by group or type in Find a report.' },
      { title: 'Set filters', body: 'Choose dates and other filters, then press Search.' },
      { title: 'Read and drill down', body: 'Check KPIs and chart; click a row to open its record.' },
      { title: 'Export', body: 'Press Excel for a CSV of the current rows, or Print.' },
    ],
    related: ['prints', 'dashboard', 'fin/receivables', 'ops/pod'],
    audio: [
      'यहाँ पुराने system की सारी 42 reports हैं, groups में।',
      'Report खोलिए, dates और filters चुनिए, और Search ज़रूर दबाइए।',
      'Search दबाए बिना numbers नहीं बदलते।',
      'Row पर click कीजिए, सीधे उस record पर पहुँच जाएँगे।',
      'Excel button से table download होती है। PDF अभी सिर्फ़ message दिखाता है, इसलिए Print इस्तेमाल कीजिए।',
    ],
    quiz: ['q.reports.search-filters', 'q.reports.export'],
    minutes: 4,
  },
  {
    id: 'prints',
    module: 'reports',
    title: 'Print Formats',
    purpose: 'Gallery of the 22 printable documents (LR, pre-printed LR, freight slip, barcode label, acknowledgment, LDC, GRN, GST bill, supplementary bill, job card, gate passes, PO, payment slips, trip advance, diesel slip, log slip, VP loading summary, maintenance checklist, hamali slip, ledger voucher) as A4 layouts.',
    why: 'You can preview any document for a recent record and reprint it without going to its screen.',
    when: 'When a customer, driver or auditor needs a copy, or to check a layout.',
    roles: ['SA', 'AD', 'OP', 'BU', 'AC', 'CC', 'CO', 'SI'],
    upstream: ['ops/lr', 'fin/billing', 'ops/dc'],
    downstream: [],
    before: 'The record exists – for example the LR is made or the bill is generated.',
    after: 'Print from the preview or save it from the browser print dialog.',
    prerequisites: [],
    actions: ['Pick a document card, choose a record from its list (latest 25), and press Preview.'],
    records: ['Read-only; printing does not change the record.'],
    validations: ['Preview is disabled when the document has no records.'],
    mistakes: ['Printing from here when the record still needs correction – fix it on its own screen first, then reprint.'],
    walkthrough: [
      { title: 'Choose the document', body: 'Each card is one print format.' },
      { title: 'Choose the record', body: 'Pick the LR, bill, slip or other number from the list.' },
      { title: 'Preview and print', body: 'Press Preview, check it, then print.' },
    ],
    related: ['reports', 'ops/lr', 'fin/billing', 'admin/barcode'],
    audio: [
      'यहाँ सारे print formats हैं — LR, bill, challan, slips, सब A4 में।',
      'Card चुनिए, record का number चुनिए, और Preview दबाइए।',
      'Print करने से record नहीं बदलता। गलती हो तो पहले उसकी screen पर ठीक कीजिए।',
    ],
    quiz: ['q.reports.export'],
    minutes: 2,
  },

  // ---------------- Masters ----------------
  {
    id: 'masters',
    module: 'masters',
    title: 'Masters',
    purpose: 'Reference lists used by every form: Organisation (company, branches, departments, designations, employees), Geography, Goods & equipment, Parties, Rates & finance, and Documents & access.',
    why: 'Bookings, bills and trips pick names and rates from these lists. Clean masters mean correct LRs, bills and reports.',
    when: 'When a new branch, city, goods type, transporter, pump, ledger or expense type is really needed, or a detail changes.',
    roles: ['SA', 'AD', 'HR'],
    upstream: [],
    downstream: ['book', 'ops/lr-new', 'fin/billing', 'fleet/fuel'],
    before: 'Someone asks for a new entry or reports a wrong detail.',
    after: 'The change shows in every form and drop-down straight away.',
    prerequisites: ['Masters is in your role menu (Super Admin, Admin and HR by default).'],
    actions: [
      'Use Find a master to open a list; the number on each line is the record count.',
      'Search the list before adding, to avoid duplicates.',
      'Add, View, Edit or Delete a record. Some entries (customers, trucks, drivers, godowns, wagons, suppliers, rates, users, roles) open their own working screens.',
    ],
    records: ['Master records in the shared ERP data.'],
    validations: ['Required fields are checked on Save – the form shows “Required: …” with the missing fields.', 'Delete asks for confirmation.'],
    mistakes: [
      'Adding “Jalgaon” again as “JALGAON” – duplicates split reports and confuse drop-downs.',
      'Deleting a master that is still in use instead of correcting it – old records keep their history, but new forms can no longer pick it.',
      'Changing a name to mean something else (re-using a record) – old LRs and bills will show the new name.',
    ],
    walkthrough: [
      { title: 'Open the list', body: 'Pick the master from its group card or search for it.' },
      { title: 'Search first', body: 'Check that the entry does not already exist under another spelling.' },
      { title: 'Add or edit', body: 'Fill the required fields and press Save.' },
      { title: 'Check a form', body: 'Open a form that uses it (e.g. New booking) and confirm it appears correctly.' },
    ],
    related: ['cust/360', 'fleet/trucks', 'admin/import', 'access/users'],
    audio: [
      'Masters में वो lists हैं जो हर form में काम आती हैं — branches, cities, goods, transporters।',
      'नई entry जोड़ने से पहले search कीजिए, कहीं पहले से तो नहीं है।',
      'Duplicate entry से reports बँट जाती हैं और गलत bill बन सकता है।',
      'Delete करने से पुराने records का इतिहास रहता है, पर नए forms में वो entry नहीं मिलेगी।',
    ],
    quiz: ['q.masters.duplicate'],
    minutes: 4,
  },

  // ---------------- Users & Access ----------------
  {
    id: 'access/users',
    module: 'access',
    title: 'Users',
    purpose: 'Server-backed login accounts. Admin and Super Admin create, edit, activate/deactivate, delete and reset passwords, and see each employee’s last login, account status and training status.',
    why: 'Every employee must sign in with their own account, with the right role, branch and screen permissions – that is what controls what they can see and do.',
    when: 'When someone joins, changes job or branch, goes on long leave, leaves the company, or forgets their password.',
    roles: ['SA', 'AD'],
    upstream: ['hr/employees'],
    downstream: ['access/roles', 'admin/training', 'help'],
    before: 'HR confirms the joining: name, branch, department and designation.',
    after: 'Give the username and temporary password to the employee securely. At first login they must change it; then they start training.',
    prerequisites: ['Admin or Super Admin login.'],
    actions: [
      'Create user: username, display name, role, branch, department, designation, and extra or denied screen permissions.',
      'Edit a user’s role, branch or permissions when their job changes.',
      'Deactivate (blocks sign-in, keeps history) or Activate again.',
      'Delete – a soft delete after confirmation; use it only for accounts that should never sign in again.',
      'Reset password: a temporary password is shown once; the employee must change it at next login.',
      'Open the employee’s training profile to see their progress and readiness.',
    ],
    records: ['Login account (username, role, branch, department, designation, active flag, permissions), last login, and audit events for create, update, reset and delete.'],
    validations: [
      'You cannot deactivate, delete or demote your own account.',
      'The last active Super Admin cannot be deactivated, deleted or demoted.',
      'An Admin cannot create or change Super Admin accounts – only a Super Admin can.',
      'Passwords are stored as hashes; an existing password can never be displayed. A temporary password is shown only once, right after reset.',
      'Password reset works only for active accounts.',
    ],
    mistakes: [
      'Sharing one login between two employees – the audit log and training records can no longer tell them apart.',
      'Deleting a user who is only on leave – deactivate instead, then activate when they return.',
      'Closing the temporary-password window before copying it – it cannot be shown again; you must reset again.',
      'Sending the temporary password in a group chat or e-mail thread – give it personally or by a private channel.',
      'Giving a new employee the Admin role “to be safe” – give the smallest role that fits the job.',
    ],
    warnings: ['A deactivated account cannot sign in at all; their past work stays in all records and reports.'],
    statuses: [
      { status: 'Active', meaning: 'Can sign in.' },
      { status: 'Inactive', meaning: 'Deactivated – cannot sign in; history kept; can be activated again.' },
      { status: 'Deleted', meaning: 'Soft-deleted – removed from daily lists; history kept.' },
    ],
    fields: [
      { name: 'Username', help: 'The login name the employee types. Keep one account per person.' },
      { name: 'Role', help: 'Decides the menus and screens the employee sees.' },
      { name: 'Branch / Department / Designation', help: 'Where and as what the employee works; used in lists and training reports.' },
      { name: 'Extra / denied permissions', help: 'Screens added to, or removed from, what the role gives this one person.' },
      { name: 'Last login', help: 'When the employee last signed in – useful to find unused accounts.' },
    ],
    example: 'Ramesh moves from Jalgaon booking to Accounts. The admin edits his account: role Accounts, branch Head Office. His menus change to Finance screens at his next sign-in, and his training curriculum switches to the Accounts role.',
    walkthrough: [
      { title: 'Create the account', body: 'Press create, fill username, display name, role, branch, department and designation.' },
      { title: 'Set permissions', body: 'Add extra screens or deny screens only if this person’s job differs from the role.' },
      { title: 'Copy the temporary password', body: 'It is shown once. Give it to the employee privately.' },
      { title: 'Check first login', body: 'Last login shows when they signed in; they must change the password then.' },
      { title: 'Track training', body: 'Open the training profile or Admin › Training dashboard to see readiness.' },
    ],
    related: ['access/roles', 'access/password', 'access/credentials', 'admin/training'],
    audio: [
      'यहाँ हर employee का login account बनता है — username, role, branch और department के साथ।',
      'Role से तय होता है कि employee को कौन से menu दिखेंगे।',
      'Password reset करने पर temporary password सिर्फ़ एक बार दिखता है। उसे तुरंत copy कीजिए।',
      'Employee को पहली login पर अपना नया password बनाना ही पड़ेगा।',
      'कोई छुट्टी पर है तो deactivate कीजिए, delete नहीं।',
      'आप अपना ख़ुद का account deactivate नहीं कर सकते, और आख़िरी Super Admin को कोई हटा नहीं सकता।',
    ],
    quiz: ['q.access.reset-shown-once', 'q.access.deactivate-vs-delete'],
    minutes: 6,
  },
  {
    id: 'access/roles',
    module: 'access',
    title: 'Roles & Permissions',
    purpose: 'Decides which menus each role sees (permission matrix), lists the roles, and lets you adjust menu access for one user.',
    why: 'Menus and direct screen access come from the role plus the user’s own additions and denials. A wrong tick shows a screen to the wrong people.',
    when: 'When a new role is needed, a role’s duties change, or one person needs one extra screen or must lose one.',
    roles: ['SA', 'AD'],
    upstream: ['access/users'],
    downstream: ['admin/training'],
    before: 'The user account exists with a role.',
    after: 'The user sees the new menus. Use Preview menu to confirm.',
    prerequisites: ['Admin or Super Admin login.'],
    actions: [
      'Permission matrix: tick or untick a menu for a role. The Super Admin column cannot be changed – Super Admin always has every screen.',
      'Roles tab: add a role (name and description), edit it, or delete it. Delete is hidden while any user has that role.',
      'Menu access per user: pick the user, move menus between Available and Assigned with the arrow buttons, and check with Preview menu.',
    ],
    records: ['Role menu lists; per-user extra menus and denied menus.'],
    validations: [
      'Super Admin menus are locked on.',
      'A role that is still assigned to users cannot be deleted.',
      'Changes apply immediately – there is no separate save step for ticks.',
      'Someone who opens a screen outside their menus sees “You don’t have access to this module”.',
    ],
    mistakes: [
      'Giving a whole role a menu that only one person needs – use Menu access per user instead.',
      'Unticking a menu for a role while people of that role are mid-task on it – tell them first.',
      'Assuming a hidden menu is the only protection – server-side checks also protect admin data such as credentials and communication audit.',
    ],
    fields: [
      { name: '“+” in Assigned menus', help: 'A menu added to this user beyond their role.' },
    ],
    walkthrough: [
      { title: 'Choose the level', body: 'Role-wide change: Permission matrix. One person: Menu access per user.' },
      { title: 'Make the change', body: 'Tick/untick, or move menus with the arrows.' },
      { title: 'Preview', body: 'Use Preview menu to see exactly what the user will see.' },
      { title: 'Tell the user', body: 'Ask them to refresh; menus follow the new access.' },
    ],
    related: ['access/users', 'access/credentials'],
    audio: [
      'यहाँ तय होता है कि किस role को कौन से menu दिखेंगे।',
      'पूरे role के लिए Permission matrix में tick कीजिए। एक ही व्यक्ति के लिए Menu access per user इस्तेमाल कीजिए।',
      'Super Admin के सारे menu हमेशा चालू रहते हैं, उन्हें बदला नहीं जा सकता।',
      'जिस role पर users हैं, उसे delete नहीं कर सकते।',
      'बदलाव तुरंत लागू होता है। Preview menu से check कर लीजिए।',
    ],
    quiz: ['q.access.roles-decide-menus'],
    minutes: 5,
  },
  {
    id: 'access/password',
    module: 'access',
    title: 'Change Password',
    purpose: 'Change your own login password.',
    why: 'Your password protects your work and your name in the audit log. You must replace a temporary password with your own.',
    when: 'At first login, after an administrator resets your password, or whenever you think someone knows it.',
    roles: [...ALL],
    upstream: ['access/users'],
    downstream: ['help'],
    before: 'You are signed in (with your current or temporary password).',
    after: 'Use the new password at your next sign-in.',
    prerequisites: ['You know your current password.'],
    actions: ['Enter Old password, New password and Re-type password, then press Save.'],
    records: ['Your password hash on the server; a “password changed” audit event.'],
    validations: [
      'Old password must be correct – otherwise “Current password is incorrect”.',
      'New password must be at least 12 characters with letters and numbers, and pass the strength check (add a capital letter or a symbol).',
      'Both new password boxes must match – otherwise “Passwords do not match”.',
    ],
    mistakes: [
      'Using your name, mobile number or “Skt@1234” style passwords – easy to guess.',
      'Writing the password on a note at the desk.',
      'Typing a wrong password many times – after 5 wrong attempts sign-in is blocked for 15 minutes (“Try again later”).',
    ],
    walkthrough: [
      { title: 'Type the old password', body: 'Your current or temporary password.' },
      { title: 'Choose a strong new one', body: '12+ characters, letters and numbers, plus a capital or symbol. Watch the strength bar.' },
      { title: 'Re-type and Save', body: 'Both must match. You will see “Password changed”.' },
    ],
    related: ['access/users', 'help'],
    audio: [
      'यहाँ अपना password बदलिए।',
      'नया password कम से कम बारह characters का हो, letters और numbers के साथ, और एक capital letter या symbol भी डालिए।',
      'Temporary password मिले, तो पहली login पर ही उसे बदल दीजिए।',
      'पाँच बार गलत password डालने पर पंद्रह मिनट के लिए login रुक जाता है।',
    ],
    quiz: ['q.access.password-rules', 'q.access.login-lockout'],
    minutes: 2,
  },
  {
    id: 'access/credentials',
    module: 'access',
    title: 'Credential Administration',
    purpose: 'Super Admin screen listing every authentication account with role, status and created date, with role change, activate/deactivate and set/reset password.',
    why: 'It is the direct server-side control of login accounts. For daily user management use Users; this screen remains for Super Admin credential work.',
    when: 'When a Super Admin must change a login role, block an account immediately, or set a password.',
    roles: ['SA'],
    upstream: ['access/users'],
    downstream: ['access/users'],
    before: 'A request comes to the Super Admin (for example a forgotten password).',
    after: 'Deliver any temporary password securely and ask the user to change it immediately.',
    prerequisites: ['Super Admin login – the server refuses everyone else with “Super Admin permission required”.'],
    actions: [
      'Change an account’s role from the Role drop-down (saves at once).',
      'Deactivate or Activate an account.',
      'Set / reset password: type a new password (12+ characters, letters and numbers) or leave it blank to generate a secure temporary password.',
    ],
    records: ['Account role/active flag and password hash; audit events “account_update” and “password_reset” (the password itself is never logged).'],
    validations: [
      'Existing passwords are never displayed or recoverable.',
      'The new temporary password is shown once in “Temporary password — copy now”.',
      'You cannot deactivate your own account.',
      'Reset works only for active accounts.',
    ],
    mistakes: [
      'Changing the role drop-down by accident – it saves immediately; set it back at once.',
      'Pressing Done before copying the temporary password.',
    ],
    warnings: ['Reset passwords only when necessary.'],
    walkthrough: [
      { title: 'Find the account', body: 'Accounts are listed by username.' },
      { title: 'Choose the action', body: 'Role drop-down, Deactivate/Activate, or Set / reset password.' },
      { title: 'Copy and deliver', body: 'After reset, copy the username and temporary password before pressing Done.' },
    ],
    related: ['access/users', 'access/roles'],
    audio: [
      'यह screen सिर्फ़ Super Admin के लिए है।',
      'रोज़ के काम के लिए Users screen इस्तेमाल कीजिए। यह server के login accounts का सीधा control है।',
      'पुराना password कभी नहीं दिखता। Reset के बाद नया temporary password सिर्फ़ एक बार दिखता है।',
      'Role का drop-down बदलते ही save हो जाता है, इसलिए ध्यान से चुनिए।',
    ],
    quiz: ['q.access.last-super-admin', 'q.access.admin-super-admin'],
    minutes: 3,
  },

  // ---------------- Administration ----------------
  {
    id: 'admin/corrections',
    module: 'admin',
    title: 'Data Corrections',
    purpose: 'Controlled corrections from the old Admin pages: delete LR, delete bill, delete an LR from a bill, delete ledger entry, delete payment receivable entry (receipt), open log slip, update finalised LR, and update trip.',
    why: 'Mistakes in finalised records must be corrected in a controlled way, with confirmation and an audit log, not by editing data directly.',
    when: 'Only after the mistake is confirmed with the person responsible and, for money records, with Accounts.',
    roles: ['SA', 'AD'],
    upstream: ['ops/lr', 'fin/billing', 'fin/client-payments', 'fleet/logslips'],
    downstream: ['fin/billing', 'ops/lr-new', 'fleet/trips'],
    before: 'Someone reports a wrong LR, bill, receipt, ledger voucher or trip.',
    after: 'The corrected record returns to its queue (for example the LRs of a deleted bill return to billing). Check the Correction audit log.',
    prerequisites: ['Admin or Super Admin login.', 'The exact document number (e.g. SKT/JL/10419, RV/412, PV/611).'],
    actions: [
      'Pick the correction on the left, type the number and check the summary shown.',
      'Delete bill: LRs return to the billing queue and the sales voucher is reversed; it appears in the Sale bill deleted report.',
      'Delete bill LR: removes one LR; bill value and GST are recalculated and the LR returns to billing.',
      'Delete receipt: the bill outstanding is restored.',
      'Open log slip: reopens it and releases its trips for correction.',
      'Update finalised LR: opens the LR form (not possible once billed).',
      'Update trip: change Advance, Onward Freight or Trip Opening KM of a trip without a log slip.',
    ],
    records: ['The corrected records, and an entry in the Correction audit log (When, Action, Reference, By).'],
    validations: [
      'Every delete asks for confirmation.',
      'A billed LR cannot be deleted – “LR is billed – delete the bill first”.',
      'A bill with receipts cannot be deleted or have LRs removed – “Delete linked receipts before deleting this bill”.',
      'Update finalised LR is disabled for billed LRs.',
      'A wrong number shows “Not found”, “Voucher not found” or “Log slip not found”.',
    ],
    mistakes: [
      'Deleting an LR when only the freight was wrong – use Update LR Freight or Update finalised LR instead.',
      'Deleting a bill to fix one LR – use Delete bill LR.',
      'Correcting without telling Accounts – ledger and outstanding change immediately.',
    ],
    warnings: ['Delete LR permanently removes the LR. Double-check the number.'],
    example: 'Bill SKT/B/512 included a wrong LR and a receipt RV/412 was already posted. Accounts deletes RV/412, then the admin removes the wrong LR from the bill with Delete bill LR, and Accounts records the receipt again.',
    walkthrough: [
      { title: 'Confirm the mistake', body: 'Agree the correction with the record owner and Accounts.' },
      { title: 'Choose the correction', body: 'Pick the smallest correction that fixes it.' },
      { title: 'Type the number', body: 'Check the summary (customer, route, status, amounts).' },
      { title: 'Confirm', body: 'Read the confirmation text, then confirm.' },
      { title: 'Check the log', body: 'The Correction audit log shows what was done and by whom.' },
    ],
    related: ['fin/freight-update', 'fin/billing', 'fin/client-payments', 'reports'],
    audio: [
      'यह Data Corrections है — गलत LR, bill, receipt या trip को ठीक करने की जगह।',
      'हमेशा सबसे छोटा correction चुनिए। एक LR गलत है तो पूरा bill delete मत कीजिए।',
      'Billed LR delete नहीं होता — पहले bill हटाना पड़ता है।',
      'और जिस bill पर receipt है, उसे हटाने से पहले receipt delete करनी पड़ती है।',
      'हर correction नीचे audit log में आपके नाम से दर्ज होता है।',
    ],
    quiz: ['q.admin.correction-order'],
    minutes: 5,
  },
  {
    id: 'admin/announcements',
    module: 'admin',
    title: 'Announcements',
    purpose: 'Notices for staff (all, by branch, role or user) and for customers on the customer portal.',
    why: 'Rule changes, holidays and service notices reach the right people inside the ERP.',
    when: 'When a policy, timing, holiday or service change must be told to staff or customers.',
    roles: ['SA', 'AD'],
    upstream: [],
    downstream: ['dashboard'],
    before: 'The notice text is approved.',
    after: 'The announcement shows as Active until its expiry/end date, then as Expired.',
    prerequisites: [],
    actions: [
      'Staff tab: New announcement with Title, Description, Expiry date and Viewers (All, Branch, Roles, Users).',
      'Customer portal tab: Title, Description, Start and End date, Viewers (All or Select Customers).',
      'Tick the branches, roles, users or customers when Viewers is not All.',
      'Edit or Delete an announcement from the list.',
    ],
    records: ['Staff announcements and customer announcements.'],
    validations: ['Title is required – Publish does nothing without it.', 'Status is Expired after the expiry/end date.'],
    mistakes: ['Choosing Viewers = Branch but ticking no branch – nobody is targeted.', 'Leaving today as the expiry date for a notice that must stay for a week.'],
    walkthrough: [
      { title: 'Pick the tab', body: 'Staff or Customer portal.' },
      { title: 'Write it', body: 'Clear title, short description, correct dates.' },
      { title: 'Choose viewers', body: 'All, or tick the exact branches, roles, users or customers.' },
      { title: 'Publish', body: 'Check its Status in the list.' },
    ],
    related: ['communication', 'dashboard'],
    audio: [
      'यहाँ staff और customers के लिए announcements बनती हैं।',
      'Title ज़रूरी है, और expiry date ध्यान से डालिए।',
      'Viewers में branch, role या user चुनें, तो नीचे सही नामों पर tick भी कीजिए।',
    ],
    quiz: ['q.admin.announcement-viewers'],
    minutes: 2,
  },
  {
    id: 'admin/import',
    module: 'admin',
    title: 'Excel Import',
    purpose: 'Bulk-load screen for master tables (customers, goods, cities, trucks, drivers, transporters, rate matrix, godowns, labour, inventory spares) with a template and a message log.',
    why: 'Large lists from Excel can be checked in one go instead of typing each record.',
    when: 'During migration or when a large master list arrives from a customer or department.',
    roles: ['SA', 'AD'],
    upstream: [],
    downstream: ['masters'],
    before: 'Download the template and fill the columns Name, Code, City, Remarks.',
    after: 'Check the Messages log and verify the records in Masters.',
    prerequisites: ['A file in .xlsx, .xls or .csv format.'],
    actions: [
      'Choose the Table.',
      'Press Template to download the CSV template.',
      'Press Upload file, drop or browse the file, check the preview of the first rows, and press Import.',
      'Read the Messages log for the result.',
    ],
    records: ['A line in the Messages log for each upload.'],
    validations: ['Import is disabled until a file is chosen.', 'CSV files show a preview of the first rows; Excel files show the expected columns.'],
    mistakes: ['Uploading into the wrong table – check Table before uploading.', 'Not checking Masters afterwards.'],
    warnings: ['In this version the import is a preview: it records a message but does not yet write the rows into the master lists. Add or check records in Masters and confirm with the development team before relying on bulk import.'],
    walkthrough: [
      { title: 'Choose the table', body: 'Pick the master you are loading.' },
      { title: 'Prepare the file', body: 'Use the template columns.' },
      { title: 'Upload and preview', body: 'Check the preview rows before Import.' },
      { title: 'Verify', body: 'Read Messages and confirm in Masters.' },
    ],
    related: ['masters', 'cust/360'],
    audio: [
      'यहाँ Excel से master data एक साथ चढ़ाने की सुविधा है।',
      'पहले Table चुनिए, फिर Template download कीजिए।',
      'अभी यह import सिर्फ़ preview और message दिखाता है, असली records Masters में ख़ुद check कीजिए।',
    ],
    quiz: ['q.masters.duplicate'],
    minutes: 2,
  },
  {
    id: 'admin/barcode',
    module: 'admin',
    title: 'LR Barcodes',
    purpose: 'Barcode labels for each package of a finalised LR.',
    why: 'Labels on each package let the godown and rail head identify pieces quickly and match them to the LR.',
    when: 'After the LR is finalised, before goods are loaded.',
    roles: ['SA', 'AD'],
    upstream: ['ops/lr-new', 'ops/lr'],
    downstream: ['ops/grn', 'ops/vp-loading'],
    before: 'The LR is finalised.',
    after: 'Stick one label on each package.',
    prerequisites: ['Only finalised LRs are listed.'],
    actions: ['Click an LR row or Print labels to open the label preview and print.'],
    records: ['Read-only; the barcode value is the LR number without slashes and without “SKT”.'],
    validations: ['Draft LRs do not appear.'],
    mistakes: ['Printing fewer labels than packages – the Labels column shows how many are needed.'],
    walkthrough: [
      { title: 'Find the LR', body: 'Newest finalised LRs first.' },
      { title: 'Check Labels', body: 'Labels = number of packages.' },
      { title: 'Print', body: 'Open the preview and print.' },
    ],
    related: ['ops/lr', 'prints', 'ops/grn'],
    audio: [
      'यहाँ finalised LR के हर package के लिए barcode label बनता है।',
      'Labels column बताता है कि कितने labels चाहिए।',
      'Draft LR यहाँ नहीं दिखता, पहले LR finalise कीजिए।',
    ],
    quiz: ['q.admin.barcode-final'],
    minutes: 2,
  },
  {
    id: 'admin/settings',
    module: 'admin',
    title: 'System Settings',
    purpose: 'Company profile, next document numbers (number series), scheduled e-mail settings, appearance and the data source.',
    why: 'Administrators check company details and number series, and manage which data the system runs on.',
    when: 'When checking company details or numbering, testing the GRN summary mail, or when the development team asks for a data export.',
    roles: ['SA', 'AD'],
    upstream: [],
    downstream: ['admin/time-limits'],
    before: 'The system is set up with the company profile and number series.',
    after: 'Changes to theme apply at once; data-source changes sign you out and reload the chosen data.',
    prerequisites: ['Admin or Super Admin login.'],
    actions: [
      'Read the Company card (name, address, GSTIN, PAN/TAN, phone, e-mail).',
      'Read Number series – the next LR, order, GRN, DGRN, challan, bill, receipt, payment slip and job card numbers.',
      'Scheduled e-mails: Daily GRN summary toggle and time; Send test now shows how many GRNs of the last 24 hours would be included.',
      'Appearance: System, Light or Dark theme.',
      'Data source: switch between SK Logistics data and sample data (when available), Export JSON, or Restore original data.',
    ],
    records: ['Theme preference; data source choice.'],
    validations: ['Switching data source and Restore original data both ask for confirmation.'],
    mistakes: ['Pressing Restore original data to “fix” one record – it discards all changes made in this browser for that data source.'],
    warnings: ['Switching the data source signs you out.', 'Restore original data cannot be undone.'],
    walkthrough: [
      { title: 'Check company details', body: 'Confirm GSTIN and PAN used on bills.' },
      { title: 'Check numbering', body: 'Number series shows the next number each document will get.' },
      { title: 'Leave data source alone', body: 'Only change it on instruction from the development team.' },
    ],
    related: ['admin/time-limits', 'prints'],
    audio: [
      'यहाँ company की जानकारी, अगले document numbers और theme दिखते हैं।',
      'Data source और Restore original data को बिना instruction के मत छेड़िए।',
      'Restore करने से इस browser के सारे बदलाव हट जाते हैं, और यह वापस नहीं होता।',
    ],
    quiz: ['q.admin.restore-data'],
    minutes: 3,
  },
  {
    id: 'admin/time-limits',
    module: 'admin',
    title: 'Stage Time Limits',
    purpose: 'Sets how long a consignment may wait in each stage before it turns red (late) on the Order Board, Home and My Work. Amber means 80% of the time is used.',
    why: 'Late flags drive daily follow-up. Limits that are too loose hide problems; too tight make everything red and people stop looking.',
    when: 'When setting up, after a process change, or when managers find the late counts do not match reality.',
    roles: ['SA', 'AD'],
    upstream: ['board', 'work'],
    downstream: ['board', 'dashboard', 'work'],
    before: 'Managers review how many cards are late in each stage on the Order Board.',
    after: 'After Save, the Order Board, Home and My Work use the new limits straight away.',
    prerequisites: ['Admin or Super Admin login.'],
    actions: [
      'Change the limit for a stage: Confirm a new order (hours), Assign a truck / make the LR (hours), Extra days allowed on the road (added to the route’s standard transit time), Get the signed POD back (days), Make the bill (days), Collect payment (days or the customer’s credit days).',
      'Watch “Late now → new” on each line and the total before saving.',
      'Press Save time limits, or Back to default.',
    ],
    records: ['The time limits in the shared ERP data. No consignment record is changed.'],
    validations: ['Save is enabled only when something changed.'],
    mistakes: [
      'Raising a limit just to make the board look green – the work is still late for the customer.',
      'Forgetting that the payment limit uses the customer’s credit days when that switch is on.',
    ],
    fields: [
      { name: 'Default limits', help: 'Confirm order 6 hours; assign truck / make LR 24 hours; road: standard transit + 1 day; POD back 7 days; make bill 3 days; payment = customer’s credit days (30 if none set).' },
      { name: 'Waiting on', help: 'The team that owns the stage – Branch manager, Branch operations, Operations / rail team, Customer care, Accounts.' },
    ],
    statuses: [
      { status: 'Red (late)', meaning: 'Time in stage is over the limit.' },
      { status: 'Amber', meaning: '80% or more of the limit is used.' },
    ],
    walkthrough: [
      { title: 'Open the board first', body: 'See which stages have many red cards and why.' },
      { title: 'Adjust a limit', body: 'Change hours or days for that stage.' },
      { title: 'Check the effect', body: 'See Late now → new before saving.' },
      { title: 'Save and tell the team', body: 'Board, Home and My Work update at once.' },
    ],
    related: ['board', 'work', 'dashboard'],
    audio: [
      'यहाँ तय कीजिए कि consignment किसी stage में कितनी देर रुक सकता है।',
      'उसके बाद card लाल, यानी late दिखेगा। अस्सी percent समय होते ही card पीला हो जाता है।',
      'Hours या days बदलिए — हर line पर दिखेगा कि अभी कितने late हैं और बदलने के बाद कितने होंगे।',
      'Save करते ही Order Board, Home और My Work नई limits इस्तेमाल करते हैं।',
      'सिर्फ़ board हरा दिखाने के लिए limit मत बढ़ाइए — customer के लिए माल फिर भी late है।',
    ],
    quiz: ['q.admin.time-limits-effect'],
    minutes: 4,
  },
  {
    id: 'admin/legacy-map',
    module: 'admin',
    title: 'Developer Reference',
    purpose: 'Internal map of every legacy ASPX page to its new screen, for the development team. Not for business users.',
    why: 'Shows whether every old page has a new home, and where.',
    when: 'When someone asks “where is the old page X now?” or during migration review.',
    roles: ['SA', 'AD'],
    upstream: [],
    downstream: [],
    before: 'Someone remembers an old ERP page by its ASPX name.',
    after: 'Click a mapped row to open its new screen.',
    prerequisites: [],
    actions: ['Filter by Area, find the legacy page, read the Modern screen, and click the row to open it.'],
    records: ['Read-only.'],
    validations: ['Unmapped pages are shown in red and counted in the Unmapped KPI.'],
    mistakes: ['Sharing this screen with business users as a menu – they should use the normal menus and search.'],
    walkthrough: [
      { title: 'Find the old page', body: 'Search or filter by area (Accounts, Transactions, MasterPages …).' },
      { title: 'Open the new screen', body: 'Click the row.' },
    ],
    related: ['admin/training-coverage', 'reports', 'masters'],
    audio: [
      'यह development team के लिए reference है — पुराना ASPX page नए system में कहाँ है।',
      'Row पर click कीजिए, नई screen खुल जाएगी।',
      'रोज़ के users के लिए यह screen नहीं है।',
    ],
    quiz: ['q.admin.coverage-gap'],
    minutes: 1,
  },
  {
    id: 'admin/training',
    module: 'admin',
    title: 'Training Dashboard',
    purpose: 'Admin view of every employee’s training: role, branch, progress, readiness, lessons, practice, quiz score, assessment status and last activity.',
    why: 'Managers decide who can work unsupervised, who needs retraining, and which topics people fail most.',
    when: 'Weekly during onboarding, before giving a new employee independent work, and after errors that suggest a training gap.',
    roles: ['SA', 'AD'],
    upstream: ['access/users', 'help'],
    downstream: ['access/users', 'help', 'admin/training-coverage'],
    before: 'Employees work through their curriculum in Help & Training; progress is saved on the server.',
    after: 'Assign retraining, confirm readiness, or adjust the employee’s role and permissions.',
    prerequisites: ['Admin or Super Admin login.'],
    actions: [
      'Filter by role, branch, readiness and completion.',
      'Sort by last activity to find employees who have stopped training.',
      'Open an employee to see completed and incomplete lessons, quiz attempts, failed topics, practice exercises and recommended retraining.',
    ],
    records: ['Read-only view of training records saved per employee.'],
    validations: ['An employee is Ready only after the curriculum and assessment are passed.'],
    mistakes: [
      'Giving independent work to someone in Assessment Pending – the assessment is not passed yet.',
      'Looking only at the progress percentage – check failed topics; a high percentage with repeated failures needs retraining.',
    ],
    statuses: [
      { status: 'Not Started', meaning: 'No training activity yet.' },
      { status: 'Learning', meaning: 'Lessons in progress.' },
      { status: 'Practising', meaning: 'Practice exercises in progress.' },
      { status: 'Assessment Pending', meaning: 'Lessons and practice done; assessment not passed yet.' },
      { status: 'Ready', meaning: 'Curriculum complete and assessment passed.' },
    ],
    example: 'Filter Branch = Jalgaon, Readiness = Assessment Pending. Two booking clerks appear; one has failed the POD topic twice. The manager asks her to repeat the POD lesson and practice before the next attempt.',
    walkthrough: [
      { title: 'Filter', body: 'Pick role, branch or readiness.' },
      { title: 'Spot problems', body: 'Look at Not Started, old last activity and low quiz scores.' },
      { title: 'Open the employee', body: 'Check failed topics and recommended retraining.' },
      { title: 'Act', body: 'Tell the employee what to repeat; confirm Ready before independent work.' },
    ],
    related: ['admin/training-coverage', 'access/users', 'help'],
    audio: [
      'यह Training dashboard है — हर employee की training एक जगह।',
      'Role, branch या readiness से filter कीजिए।',
      'Ready का मतलब है lessons, practice और assessment सब पूरे।',
      'Employee खोलिए — कौन से topics में बार-बार गलती हुई, वो दिखेगा, और retraining की सलाह भी।',
      'Assessment Pending वाले को अकेले काम मत दीजिए।',
    ],
    quiz: ['q.admin.readiness-meaning'],
    minutes: 4,
  },
  {
    id: 'admin/training-coverage',
    module: 'admin',
    title: 'Training Coverage',
    purpose: 'Matrix of every ERP screen showing whether it has help metadata, a lesson, audio, a quiz and a practice exercise.',
    why: 'Finds screens with no training before employees are expected to use them.',
    when: 'Before rolling out a new screen or role, and during periodic training reviews.',
    roles: ['SA', 'AD'],
    upstream: ['admin/training'],
    downstream: ['admin/training', 'help'],
    before: 'New screens are added to the ERP menus.',
    after: 'Ask the training owner or development team to add the missing lesson, audio, quiz or practice.',
    prerequisites: [],
    actions: ['Scan or filter the matrix for missing items, and prioritise screens used daily by many roles.'],
    records: ['Read-only.'],
    validations: [],
    mistakes: ['Expecting every screen to have practice – some admin actions cannot be practised on sample data and are taught by lesson and quiz only.'],
    walkthrough: [
      { title: 'Look for gaps', body: 'Find screens missing a lesson, audio or quiz.' },
      { title: 'Prioritise', body: 'Daily screens used by many employees first.' },
      { title: 'Request content', body: 'Send the list to the training owner.' },
    ],
    related: ['admin/training', 'help', 'admin/legacy-map'],
    audio: [
      'यह matrix बताती है कि किस screen की training तैयार है और किसकी नहीं।',
      'Help, lesson, audio, quiz और practice — हर screen के लिए अलग column है।',
      'जिस screen पर रोज़ ज़्यादा लोग काम करते हैं, उसकी कमी पहले पूरी करवाइए।',
    ],
    quiz: ['q.admin.coverage-gap'],
    minutes: 2,
  },
];

// ---------------------------------------------------------------------------------------------------------------
// Questions
// ---------------------------------------------------------------------------------------------------------------
export const questions: Question[] = [
  {
    id: 'q.access.reset-shown-once',
    module: 'access',
    type: 'mcq',
    prompt: 'You reset a driver-desk employee’s password and pressed Done before copying the temporary password. What now?',
    options: [
      { id: 'a', text: 'Open the user again – the password is shown on the account.' },
      { id: 'b', text: 'Ask the server team to look it up in the database.' },
      { id: 'c', text: 'Reset the password again and copy it this time.' },
      { id: 'd', text: 'Check the audit log for the password.' },
    ],
    answer: 'c',
    explanation: 'Passwords are stored only as hashes. The temporary password is shown once and is not written to the audit log, so nobody can see it again. Reset again and copy it before closing.',
    screens: ['access/users', 'access/credentials'],
    difficulty: 1,
  },
  {
    id: 'q.access.last-super-admin',
    module: 'access',
    type: 'scenario',
    prompt: 'What will the ERP do?',
    scenario: 'The company has only one active Super Admin. He wants to change his own role to Admin so that he “cannot break anything”.',
    options: [
      { id: 'a', text: 'Allow it – a user may change their own role.' },
      { id: 'b', text: 'Block it – you cannot demote yourself, and the last active Super Admin cannot be demoted.' },
      { id: 'c', text: 'Allow it, then make another Admin a Super Admin automatically.' },
    ],
    answer: 'b',
    explanation: 'Two safeguards apply: nobody can deactivate, delete or demote their own account, and the last active Super Admin can never be deactivated, deleted or demoted. Create a second Super Admin first if the role must move.',
    screens: ['access/users', 'access/credentials'],
    difficulty: 2,
  },
  {
    id: 'q.access.deactivate-vs-delete',
    module: 'access',
    type: 'scenario',
    prompt: 'What should the admin do with her account?',
    scenario: 'A billing clerk goes on 3 months’ maternity leave and will return to the same job.',
    options: [
      { id: 'a', text: 'Delete the account and create a new one when she returns.' },
      { id: 'b', text: 'Deactivate the account now and activate it when she returns.' },
      { id: 'c', text: 'Leave it active and share the password with her replacement.' },
    ],
    answer: 'b',
    explanation: 'Deactivation blocks sign-in but keeps the account, history and training records, and can be reversed. Delete is for accounts that should never sign in again. Never share a login.',
    screens: ['access/users'],
    difficulty: 1,
  },
  {
    id: 'q.access.admin-super-admin',
    module: 'access',
    type: 'mcq',
    prompt: 'An Admin (not Super Admin) needs a new Super Admin account for the new director. What happens?',
    options: [
      { id: 'a', text: 'The Admin creates it with role Super Admin.' },
      { id: 'b', text: 'The Admin cannot create or change Super Admin accounts; a Super Admin must do it.' },
      { id: 'c', text: 'The Admin creates an Admin account and ticks every screen.' },
    ],
    answer: 'b',
    explanation: 'Only a Super Admin can create or change Super Admin accounts. Ticking every screen for an Admin is not the same and should not be used as a workaround.',
    screens: ['access/users'],
    difficulty: 2,
  },
  {
    id: 'q.access.roles-decide-menus',
    module: 'access',
    type: 'scenario',
    prompt: 'What is the right fix?',
    scenario: 'Priya (Customer Care) must check Receivables for her customers. Nobody else in Customer Care needs it. When she opens the screen she sees “You don’t have access to this module”.',
    options: [
      { id: 'a', text: 'Tick Receivables for the whole Customer Care role in the Permission matrix.' },
      { id: 'b', text: 'Give Priya the Accounts role.' },
      { id: 'c', text: 'Add Receivables to Priya only (extra permission / Menu access per user).' },
      { id: 'd', text: 'Give her an Accounts colleague’s login.' },
    ],
    answer: 'c',
    explanation: 'Menus come from the role plus per-user additions and denials. When one person needs one extra screen, add it to that user only; changing the role affects everyone with it.',
    screens: ['access/roles', 'access/users'],
    difficulty: 2,
  },
  {
    id: 'q.access.password-rules',
    module: 'access',
    type: 'mcq',
    prompt: 'Which new password will Change Password accept?',
    options: [
      { id: 'a', text: 'Skt@2026' },
      { id: 'b', text: 'jalgaonbranch' },
      { id: 'c', text: 'Rake#Jalgaon2026' },
      { id: 'd', text: '987654321012' },
    ],
    answer: 'c',
    explanation: 'The new password must be at least 12 characters with letters and numbers, and pass the strength check (capital letter or symbol). “Skt@2026” is too short, “jalgaonbranch” has no number, “987654321012” has no letters.',
    screens: ['access/password'],
    difficulty: 2,
  },
  {
    id: 'q.access.login-lockout',
    module: 'access',
    type: 'next',
    prompt: 'A branch user typed a wrong password 5 times and now sees “Try again later”. What happens next?',
    options: [
      { id: 'a', text: 'Sign-in for that username is blocked for 15 minutes; after that, try again or ask an admin to reset the password.' },
      { id: 'b', text: 'The account is deleted.' },
      { id: 'c', text: 'The account is deactivated until a Super Admin activates it.' },
    ],
    answer: 'a',
    explanation: 'After 5 failed attempts the server blocks sign-in for that username for 15 minutes. The account is not deactivated. If the password is forgotten, an administrator resets it and gives a one-time temporary password.',
    screens: ['access/password', 'access/users'],
    difficulty: 1,
  },
  {
    id: 'q.access.new-employee-order',
    module: 'access',
    type: 'order',
    prompt: 'Put the onboarding of a new employee in the right order.',
    items: [
      { id: 'create', text: 'Create the login account with role and branch (Users)' },
      { id: 'perm', text: 'Adjust screen permissions if the job differs from the role (Roles & Permissions)' },
      { id: 'handover', text: 'Give the username and one-time temporary password privately' },
      { id: 'first', text: 'Employee signs in and changes the temporary password' },
      { id: 'train', text: 'Employee completes the role curriculum in Help & Training' },
      { id: 'ready', text: 'Manager checks readiness in the Training dashboard' },
    ],
    answer: ['create', 'perm', 'handover', 'first', 'train', 'ready'],
    explanation: 'Access is set before the first login so the employee sees the right menus and the right curriculum. The temporary password must be changed at first login. Independent work starts only when the Training dashboard shows Ready.',
    screens: ['access/users', 'access/roles', 'help', 'admin/training'],
    difficulty: 2,
  },
  {
    id: 'q.admin.time-limits-effect',
    module: 'admin',
    type: 'mcq',
    prompt: 'The admin changes “Get the signed POD back within” from 7 to 10 days and saves. What happens?',
    options: [
      { id: 'a', text: 'Only consignments delivered after today use the new limit.' },
      { id: 'b', text: 'Late (red) flags in the POD stage are recalculated at once on the Order Board, Home and My Work; no LR is changed.' },
      { id: 'c', text: 'The POD dates on LRs are moved by 3 days.' },
      { id: 'd', text: 'Nothing changes until the next day.' },
    ],
    answer: 'b',
    explanation: 'Time limits only change how late is measured. The board compares each card’s time in stage with the limit, so the change applies immediately to all open cards. Check “Late now → new” before saving.',
    screens: ['admin/time-limits', 'board'],
    difficulty: 2,
  },
  {
    id: 'q.admin.correction-order',
    module: 'admin',
    type: 'order',
    prompt: 'An LR was booked twice by mistake. The duplicate is already billed and the customer’s receipt is posted against that bill. In what order do you correct it?',
    items: [
      { id: 'receipt', text: 'Delete the receipt (payment receivable entry) against the bill' },
      { id: 'billlr', text: 'Remove the duplicate LR from the bill (Delete bill LR)' },
      { id: 'lr', text: 'Delete the duplicate LR' },
      { id: 'rereceipt', text: 'Accounts records the receipt again' },
    ],
    answer: ['receipt', 'billlr', 'lr', 'rereceipt'],
    explanation: 'A bill with receipts cannot be changed (“Delete linked receipts before …”), and a billed LR cannot be deleted (“LR is billed – delete the bill first”). Remove one LR from the bill rather than deleting the whole bill, then re-post the receipt.',
    screens: ['admin/corrections', 'fin/client-payments'],
    difficulty: 3,
  },
  {
    id: 'q.admin.restore-data',
    module: 'admin',
    type: 'scenario',
    prompt: 'What should he do?',
    scenario: 'An admin sees one wrong customer address and thinks of pressing Restore original data in System Settings to “clean it up”.',
    options: [
      { id: 'a', text: 'Press Restore original data – it fixes only wrong records.' },
      { id: 'b', text: 'Correct the address in Customer 360 / Masters; Restore discards all changes for that data source and cannot be undone.' },
      { id: 'c', text: 'Switch to sample data and back.' },
    ],
    answer: 'b',
    explanation: 'Restore original data throws away every change made in this browser for the data source; switching source also signs you out. Fix single records on their own screen.',
    screens: ['admin/settings', 'masters'],
    difficulty: 2,
  },
  {
    id: 'q.admin.announcement-viewers',
    module: 'admin',
    type: 'spot',
    prompt: 'Spot the mistake in this announcement.',
    scenario: 'Title: “Pune branch closed on Saturday”. Expiry date: today. Viewers: Branch, with no branch ticked. Published on Wednesday.',
    options: [
      { id: 'a', text: 'The title is too specific.' },
      { id: 'b', text: 'No branch is ticked and the expiry is today, so nobody sees it until Saturday.' },
      { id: 'c', text: 'Branch notices must go to the customer portal.' },
    ],
    answer: 'b',
    explanation: 'With Viewers = Branch you must tick the branches, and the expiry date must cover the period people need to see it. After expiry the status becomes Expired.',
    screens: ['admin/announcements'],
    difficulty: 2,
  },
  {
    id: 'q.admin.barcode-final',
    module: 'admin',
    type: 'mcq',
    prompt: 'Why can’t the booking clerk find LR SKT/JL/10522 in LR Barcodes?',
    options: [
      { id: 'a', text: 'Barcodes are printed only for rail LRs.' },
      { id: 'b', text: 'The LR is still a draft – only finalised LRs get barcode labels.' },
      { id: 'c', text: 'Barcodes are printed only after delivery.' },
    ],
    answer: 'b',
    explanation: 'LR Barcodes lists finalised LRs only. Finish and finalise the LR, then print one label per package.',
    screens: ['admin/barcode', 'ops/lr-new'],
    difficulty: 1,
  },
  {
    id: 'q.admin.readiness-meaning',
    module: 'admin',
    type: 'mcq',
    prompt: 'In the Training dashboard a new booking clerk shows “Assessment Pending”. What does it mean?',
    options: [
      { id: 'a', text: 'She has not opened any lesson.' },
      { id: 'b', text: 'Lessons and practice are done, but she has not passed the assessment yet.' },
      { id: 'c', text: 'She passed everything and is ready.' },
    ],
    answer: 'b',
    explanation: 'Readiness moves Not Started → Learning → Practising → Assessment Pending → Ready. Give independent work only at Ready.',
    screens: ['admin/training', 'help'],
    difficulty: 1,
  },
  {
    id: 'q.admin.practice-isolated',
    module: 'admin',
    type: 'tf',
    prompt: 'Work done in a practice exercise is saved to the shared ERP data and appears in reports.',
    options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
    answer: 'false',
    explanation: 'Practice runs on separate sample data kept in your browser. Only your result (Pass / Needs correction) is saved to your training record – never the practice records themselves.',
    screens: ['help'],
    difficulty: 1,
  },
  {
    id: 'q.admin.coverage-gap',
    module: 'admin',
    type: 'scenario',
    prompt: 'What is the best use of the Training Coverage matrix here?',
    scenario: 'A new screen, Detention Management, goes live next week for Accounts. In the coverage matrix it has help metadata but no lesson, audio or quiz.',
    options: [
      { id: 'a', text: 'Ignore it – staff will learn by using it.' },
      { id: 'b', text: 'Ask for the missing lesson, audio and quiz before go-live, because Accounts will use it daily.' },
      { id: 'c', text: 'Hide the screen from all roles permanently.' },
    ],
    answer: 'b',
    explanation: 'The coverage matrix exists to find screens without training before people rely on them. Prioritise daily-use screens for many users.',
    screens: ['admin/training-coverage', 'admin/training'],
    difficulty: 1,
  },
  {
    id: 'q.comms.audit-access',
    module: 'comms',
    type: 'mcq',
    prompt: 'A branch user types the Communication Oversight address directly in the browser. What happens?',
    options: [
      { id: 'a', text: 'He sees the audit because he knows the address.' },
      { id: 'b', text: 'The server refuses the data with “Administrator permission required”.' },
      { id: 'c', text: 'He sees only his own messages in the audit.' },
    ],
    answer: 'b',
    explanation: 'Communication oversight is protected by the API, not only by the menu. Only Super Admin, Admin and ERP Manager accounts receive audit data.',
    screens: ['communication/audit', 'communication'],
    difficulty: 2,
  },
  {
    id: 'q.comms.task-conflict',
    module: 'comms',
    type: 'next',
    prompt: 'You change a task to done and see “Task update failed – Task changed by another user”. What is the next step?',
    options: [
      { id: 'a', text: 'Keep selecting done until it saves.' },
      { id: 'b', text: 'Press Refresh, read the task’s new status and conversation, then update it if still needed.' },
      { id: 'c', text: 'Create a new duplicate task.' },
    ],
    answer: 'b',
    explanation: 'Each task has a version. If someone else changed it after you loaded the page, your update is refused so you do not overwrite their change. Refresh, check, then update.',
    screens: ['communication/tasks'],
    difficulty: 2,
  },
  {
    id: 'q.comms.reference',
    module: 'comms',
    type: 'scenario',
    prompt: 'What is the best message?',
    scenario: 'You need the Pune branch to confirm delivery of LR SKT/JL/10419 today.',
    options: [
      { id: 'a', text: 'A WhatsApp message to the branch manager.' },
      { id: 'b', text: 'A Team Chat message “please check” with no reference.' },
      { id: 'c', text: 'A Team Chat message with ERP ref type LR and reference SKT/JL/10419, plus a task “Confirm delivery” assigned to the branch user, due today.' },
    ],
    answer: 'c',
    explanation: 'An ERP reference tells the reader exactly which record, and a task gives one owner, a priority and a due date. Both are recorded for follow-up and audit.',
    screens: ['communication', 'communication/tasks'],
    difficulty: 1,
  },
  {
    id: 'q.reports.search-filters',
    module: 'reports',
    type: 'next',
    prompt: 'You changed the From date in Pending acknowledgment summary, but the KPIs did not change. What next?',
    options: [
      { id: 'a', text: 'Press Search – filters apply only after Search.' },
      { id: 'b', text: 'Export to Excel; the export uses the new dates.' },
      { id: 'c', text: 'Reload the whole ERP.' },
    ],
    answer: 'a',
    explanation: 'Report filters are a draft until you press Search. Exports and KPIs use the last searched filters.',
    screens: ['reports'],
    difficulty: 1,
  },
  {
    id: 'q.reports.export',
    module: 'reports',
    type: 'mcq',
    prompt: 'A manager needs this month’s sale bill list in Excel. What does the report do?',
    options: [
      { id: 'a', text: 'Excel downloads the rows currently in the table (after Search) as a CSV file.' },
      { id: 'b', text: 'PDF downloads a ready PDF file of all pages.' },
      { id: 'c', text: 'Reports can only be printed.' },
    ],
    answer: 'a',
    explanation: 'Excel exports the current filtered rows as CSV, which opens in Excel. In this version the PDF button only shows a message; use Print for a paper or PDF copy from the browser.',
    screens: ['reports', 'prints'],
    difficulty: 1,
  },
  {
    id: 'q.masters.duplicate',
    module: 'masters',
    type: 'scenario',
    prompt: 'What should the HR/admin user do?',
    scenario: 'A booking clerk cannot find “Aurangabad” in the city list and asks for it to be added. The list already has “Chhatrapati Sambhajinagar (Aurangabad)”.',
    options: [
      { id: 'a', text: 'Add “Aurangabad” as a new city.' },
      { id: 'b', text: 'Search first, show the clerk the existing city, and do not create a duplicate.' },
      { id: 'c', text: 'Delete the existing city and add the old name.' },
    ],
    answer: 'b',
    explanation: 'Duplicate masters split reports and freight rates between two names. Always search before adding; deleting a master in use only stops new forms from picking it.',
    screens: ['masters'],
    difficulty: 1,
  },
];

// ---------------------------------------------------------------------------------------------------------------
// Practice exercises – admin actions here change accounts, permissions and settings and are not practised on
// sample data. They are taught through lessons, workflows and quizzes.
// ---------------------------------------------------------------------------------------------------------------
export const exercises: Exercise[] = [];

// ---------------------------------------------------------------------------------------------------------------
// Workflows
// ---------------------------------------------------------------------------------------------------------------
export const workflows: Workflow[] = [
  {
    id: 'wf.new-employee',
    title: 'Onboard a new employee',
    module: 'admin',
    roles: ['SA', 'AD'],
    summary: 'From a real login account to a trained, ready employee: account, permissions, first login, training and readiness check.',
    lesson: 'ls.admin.onboarding',
    steps: [
      { screen: 'access/users', title: 'Create the account', does: 'Create the login with username, display name, role, branch, department and designation. Copy the one-time temporary password and give it privately.' },
      { screen: 'access/roles', title: 'Check permissions', does: 'Add or deny single screens only if the job differs from the role. Use Preview menu to confirm what the employee will see.' },
      { screen: 'admin/training', title: 'Track training', does: 'After first login the employee changes the password and starts the role curriculum. Watch progress, quiz scores and failed topics.' },
      { screen: 'help', title: 'Employee completes the curriculum', does: 'Lessons, practice exercises and the assessment in Help & Training. Readiness moves to Ready when the assessment is passed.' },
    ],
    notes: [
      'One login per person – never share accounts.',
      'An Admin cannot create Super Admin accounts.',
      'Do not give independent work before readiness is Ready.',
    ],
  },
  {
    id: 'wf.exception-monitoring',
    title: 'Daily exception monitoring',
    module: 'admin',
    roles: ['SA', 'AD', 'OP'],
    summary: 'Find late work, see who it is waiting on, get it moving, and tune time limits and reports so the late flags stay meaningful.',
    lesson: 'ls.admin.exception-monitoring',
    steps: [
      { screen: 'dashboard', title: 'Look at Home', does: 'See the stage pipeline and late counts across branches.' },
      { screen: 'board', title: 'Open the Order Board', does: 'Red cards are late, amber are close. Each card says why it is stuck and who it is waiting on.' },
      { screen: 'work', title: 'Check My Work', does: 'Clear the red rows first; follow up the owners of other late cards through Team Chat tasks.' },
      { screen: 'admin/time-limits', title: 'Review time limits', does: 'If a stage is red for reasons that are normal for the business, adjust its limit and check Late now → new before saving.' },
      { screen: 'reports', title: 'Confirm with reports', does: 'Use reports such as Pending acknowledgment summary and Client outstanding to confirm the trend and share figures.' },
    ],
    notes: ['Do not raise limits only to make the board green – late for the customer is still late.'],
  },
];

// ---------------------------------------------------------------------------------------------------------------
// Manager lessons
// ---------------------------------------------------------------------------------------------------------------
export const lessons: Lesson[] = [
  {
    id: 'ls.admin.exception-monitoring',
    title: 'Monitoring work and exceptions',
    module: 'admin',
    kind: 'manager',
    roles: ['SA', 'AD', 'OP'],
    screens: ['dashboard', 'board', 'work', 'admin/time-limits'],
    summary: 'Use Home, the Order Board, My Work and stage time limits to find late consignments every day and get them moving.',
    sections: [
      {
        heading: 'How “late” is decided',
        body: 'Every open order and LR sits in one stage: Booked, Waiting for vehicle, On the way, Delivered – POD pending, Ready to bill, Billed – awaiting payment, Paid. The ERP measures how long it has been in that stage and compares it with the stage time limit.',
        bullets: [
          'Amber: 80% of the limit used – act today.',
          'Red: over the limit – late.',
          'Each card shows the reason (e.g. “POD not received”, “No vehicle assigned”) and who it is waiting on.',
        ],
      },
      {
        heading: 'A daily routine',
        body: 'Start on Home for the overall picture, open the Order Board for the late cards, and use My Work for the jobs waiting on you.',
        bullets: [
          'Sort out red cards that are waiting on your own team first.',
          'For cards waiting on another team, send a Team Chat message with the LR reference and assign a task.',
          'Look for patterns: one branch, one customer or one stage that is always red.',
        ],
      },
      {
        heading: 'Tuning time limits',
        body: 'Stage Time Limits sets the hours or days per stage. Defaults: confirm order 6 hours, assign truck / make LR 24 hours, road transit = standard days + 1, POD back 7 days, make bill 3 days, payment = customer credit days (30 if none).',
        bullets: [
          'Before saving, read “Late now → new” to see the effect.',
          'Saving changes late flags immediately on the Order Board, Home and My Work; no LR data is changed.',
          'Never loosen a limit only to make the board look green.',
        ],
      },
    ],
    audio: [
      'Manager का पहला काम है — रोज़ late काम ढूँढना और उसे आगे बढ़ाना।',
      'Home पर पूरी तस्वीर, Order Board पर late cards, और My Work में आपका अपना काम।',
      'पीला card मतलब अस्सी percent समय गया, लाल मतलब late।',
      'Card पर लिखा होता है कि क्यों अटका है और किसके पास।',
      'दूसरी team के पास अटका हो, तो chat में LR number के साथ task assign कीजिए।',
      'Time limits तभी बदलिए जब वो business की असलियत से मेल न खाएँ।',
    ],
    minutes: 7,
    quiz: ['q.admin.time-limits-effect'],
  },
  {
    id: 'ls.admin.reports',
    title: 'Using reports and dashboards',
    module: 'admin',
    kind: 'manager',
    roles: ['SA', 'AD', 'OP', 'AC'],
    screens: ['dashboard', 'reports', 'prints'],
    summary: 'Pick the right report for a management question, filter it correctly, drill down to records and export figures.',
    sections: [
      {
        heading: 'Dashboards versus reports',
        body: 'Home and the Order Board show today’s situation and what to act on now. Reports & MIS gives the 42 detailed reports for a period, grouped as Operations, Rail, Warehouse, Fleet, Performance, Finance and Workshop.',
      },
      {
        heading: 'Getting correct numbers',
        body: 'Every report has its own filters. Dated reports start with the last 60 days.',
        bullets: [
          'Set filters, then press Search – nothing changes until you do.',
          'Check From and To before sharing figures.',
          'Click a row (where available) to open the record behind it.',
          'Some cards (stock, damage/shortage, quality control, client outstanding, ledger, rate matrix) open the live working screen.',
        ],
      },
      {
        heading: 'Useful management reports',
        body: 'A few reports answer most weekly questions.',
        bullets: [
          'Pending acknowledgment summary – PODs to chase before billing.',
          'Client outstanding and Sale bill – money to collect and billed value.',
          'Rake profitability and MIS report (rake) – rail performance.',
          'Vehicle performance, Top 10 trucks/drivers and Pending log slip – fleet.',
          'Sale bill deleted and Account ledger audit – control of corrections.',
        ],
      },
      {
        heading: 'Sharing',
        body: 'Excel exports the current rows as CSV. In this version the PDF button only shows a message – use Print for a paper or PDF copy. Print Formats reprints LRs, bills, challans and slips.',
      },
    ],
    audio: [
      'Home आज का हाल बताता है, और Reports किसी भी period का पूरा हिसाब।',
      'Report में filters चुनिए और Search ज़रूर दबाइए।',
      'Row पर click करके सीधे record तक जाइए।',
      'Bill delete या ledger audit जैसी reports से corrections पर नज़र रखिए।',
      'Excel button से data download कीजिए, और paper copy के लिए Print।',
    ],
    minutes: 6,
    quiz: ['q.reports.search-filters', 'q.reports.export'],
  },
  {
    id: 'ls.admin.onboarding',
    title: 'Onboarding a new employee end to end',
    module: 'admin',
    kind: 'manager',
    roles: ['SA', 'AD', 'HR'],
    screens: ['access/users', 'access/roles', 'access/password', 'help', 'admin/training'],
    summary: 'Create the login, set role and permissions, hand over the temporary password, and follow the employee through training to Ready.',
    sections: [
      {
        heading: '1. Create the user',
        body: 'In Users, create the account: username, display name, role, branch, department and designation. One account per person.',
        bullets: [
          'Choose the smallest role that fits the job.',
          'Only a Super Admin can create Super Admin accounts.',
        ],
      },
      {
        heading: '2. Role and permissions',
        body: 'The role decides the menus and the training curriculum. Add extra screens or deny screens for this one person only when the job is different from the role. Check with Preview menu in Roles & Permissions.',
      },
      {
        heading: '3. First login',
        body: 'The temporary password is shown once – copy it and give it privately, never in a group chat. At first sign-in the employee must change it (at least 12 characters, letters and numbers, plus a capital or symbol) and sees the welcome for the role.',
      },
      {
        heading: '4. Training',
        body: 'The employee follows the curriculum in Help & Training: Getting Started, Your Role, Your Daily Work, Module Training, Workflows, Practice and Assessments. Practice runs on sample data, so mistakes do no harm.',
      },
      {
        heading: '5. Readiness check',
        body: 'In the Training dashboard filter by branch or role. Readiness moves Not Started → Learning → Practising → Assessment Pending → Ready.',
        bullets: [
          'Open the employee to see failed topics and recommended retraining.',
          'Give independent work only at Ready.',
          'If the job changes later, edit the role – the menus and curriculum follow.',
        ],
      },
    ],
    audio: [
      'नए employee का onboarding पाँच steps में होता है।',
      'पहले Users में उसका अपना login बनाइए — role, branch और department के साथ।',
      'ज़रूरत हो तो सिर्फ़ उसी व्यक्ति के लिए screen जोड़िए या हटाइए।',
      'Temporary password एक ही बार दिखता है — उसे private तरीके से दीजिए।',
      'पहली login पर employee अपना password बदलेगा और training शुरू करेगा।',
      'Training dashboard में Ready दिखने के बाद ही उसे अकेले काम दीजिए।',
    ],
    minutes: 8,
    quiz: ['q.access.new-employee-order', 'q.access.reset-shown-once', 'q.admin.readiness-meaning'],
  },
  {
    id: 'ls.admin.clean-masters',
    title: 'Keeping masters and access clean',
    module: 'admin',
    kind: 'manager',
    roles: ['SA', 'AD', 'HR'],
    screens: ['masters', 'access/users', 'access/roles', 'admin/corrections'],
    summary: 'Prevent duplicate master records, retire unused accounts correctly, and use controlled corrections instead of shortcuts.',
    sections: [
      {
        heading: 'Masters',
        body: 'Cities, goods, branches, transporters, pumps, ledgers and expense types feed every form and report.',
        bullets: [
          'Search before adding; a duplicate splits reports and rates.',
          'Correct a wrong detail by editing; do not re-use a record for something else.',
          'Deleting a master keeps old records’ history, but new forms can no longer pick it.',
        ],
      },
      {
        heading: 'User accounts',
        body: 'Review Users monthly using Last login and status.',
        bullets: [
          'Leaver: deactivate at once; delete (soft) only when the account will never be used again.',
          'Long leave: deactivate, then activate on return.',
          'Job change: edit role and branch instead of creating a second account.',
          'Remove per-user extra screens that are no longer needed.',
        ],
      },
      {
        heading: 'Corrections',
        body: 'Use the smallest correction in Data Corrections and follow the order the ERP enforces: receipts before bills, bills before billed LRs. Every correction is logged with your name.',
      },
    ],
    audio: [
      'Master lists साफ़ हों, तो bills और reports सही आते हैं।',
      'नई entry से पहले हमेशा search कीजिए।',
      'हर महीने Users में last login देखिए। छोड़कर गए लोगों का account तुरंत deactivate कीजिए।',
      'Job बदले तो नया account नहीं, बस role और branch बदलिए।',
      'Corrections में पहले receipt, फिर bill, फिर LR — यही order है।',
    ],
    minutes: 6,
    quiz: ['q.masters.duplicate', 'q.access.deactivate-vs-delete', 'q.admin.correction-order'],
  },
  {
    id: 'ls.admin.communication-audit',
    title: 'Communication and audit',
    module: 'admin',
    kind: 'manager',
    roles: ['SA', 'AD'],
    screens: ['communication', 'communication/tasks', 'communication/enquiries', 'communication/audit'],
    summary: 'Run follow-ups through Team Chat tasks with ERP references, and use Communication Oversight responsibly.',
    sections: [
      {
        heading: 'Work through tasks, not calls',
        body: 'Ask for work in Team Chat with an ERP reference (for example LR and the LR number), and assign a task with assignee, priority and due date. Assigned Tasks shows todo, in progress, blocked, done and cancelled.',
        bullets: [
          'Tasks can be assigned only to active users.',
          'If an update says “Task changed by another user”, refresh and check before changing again.',
          'Employee enquiries keep staff questions in one recorded thread.',
        ],
      },
      {
        heading: 'Oversight',
        body: 'Communication Oversight lists the latest 500 communication events: who created conversations, sent messages and created or changed tasks. The server allows it only for Super Admin, Admin and ERP Manager accounts.',
        bullets: [
          'Administrators can open every conversation.',
          'Use oversight for audits, disputes and missed handovers – not for general monitoring of staff.',
          'Never let anyone send passwords in chat; messages are retained.',
        ],
      },
    ],
    audio: [
      'काम की हर बात Team Chat में, LR number के साथ कीजिए।',
      'जिसे काम करना है, उसे task assign कीजिए — priority और due date के साथ।',
      'Communication Oversight में दिखता है कि किसने कब message भेजा या task बदला।',
      'यह server से सुरक्षित है — सिर्फ़ administrators इसे देख सकते हैं।',
      'इसे जाँच के लिए इस्तेमाल कीजिए, रोज़ की निगरानी के लिए नहीं।',
    ],
    minutes: 5,
    quiz: ['q.comms.audit-access', 'q.comms.task-conflict', 'q.comms.reference'],
  },
];
