import React, { useEffect, useMemo, useState } from 'react';
import { useUI } from '../store/store';
import { getERPUser, fetchCommunicationOverview, createCommunicationConversation, fetchCommunicationMessages, sendCommunicationMessage, markCommunicationRead, createCommunicationTask, updateCommunicationTask, fetchCommunicationAudit, type CommunicationConversation, type CommunicationMessage, type CommunicationTask, type CommunicationUser } from '../lib/api';
import { PageHeader, Card, Field, Input, Textarea, Select, StatusBadge, EmptyState, Segmented } from '../components/ui';
import { MessageCircle, Send, Plus, ClipboardList, Search, ShieldCheck, Link2, RefreshCw, CheckCircle2, HelpCircle } from 'lucide-react';
import { cls, fmtDT } from '../lib/util';

const roleLabel=(role:string)=>role.replace(/_/g,' ').replace(/\b\w/g,x=>x.toUpperCase());
const emptyMessage='Select a conversation to read messages.';

export function Communication() {
  const route=useUI(s=>s.route), toast=useUI(s=>s.toast);
  const [conversations,setConversations]=useState<CommunicationConversation[]>([]),[users,setUsers]=useState<CommunicationUser[]>([]),[tasks,setTasks]=useState<CommunicationTask[]>([]),[admin,setAdmin]=useState(false),[selected,setSelected]=useState<string>(''),[messages,setMessages]=useState<CommunicationMessage[]>([]),[loading,setLoading]=useState(true),[body,setBody]=useState(''),[referenceType,setReferenceType]=useState(''),[referenceId,setReferenceId]=useState(''),[search,setSearch]=useState('');
  const [composer,setComposer]=useState({kind:'group',subject:'',members:[] as string[]}),[taskForm,setTaskForm]=useState({title:'',description:'',assigned_to:'',priority:'normal',due_at:''});
  const [audit,setAudit]=useState<any[]>([]);
  const focus=route.endsWith('/tasks')?'tasks':route.endsWith('/enquiries')?'enquiries':route.endsWith('/audit')?'audit':'chat';
  const load=async()=>{try{const x=await fetchCommunicationOverview();setConversations(x.conversations);setUsers(x.users);setTasks(x.tasks);setAdmin(x.admin);if(!selected&&x.conversations[0])setSelected(String(x.conversations[0].id));}catch(e){toast('Communication unavailable','bad',e instanceof Error?e.message:'Request failed');}finally{setLoading(false);}};
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>{if(!selected||focus!=='chat')return;let live=true;fetchCommunicationMessages(selected).then(x=>{if(live){setMessages(x.messages);void markCommunicationRead(selected);}}).catch(()=>{});const timer=window.setInterval(()=>fetchCommunicationMessages(selected).then(x=>live&&setMessages(x.messages)).catch(()=>{}),8000);return()=>{live=false;window.clearInterval(timer);};},[selected,focus]);
  useEffect(()=>{if(focus==='audit'&&admin)fetchCommunicationAudit().then(x=>setAudit(x.events)).catch(e=>toast('Audit unavailable','bad',e instanceof Error?e.message:'Request failed'));},[focus,admin]);
  const selectedConversation=conversations.find(x=>String(x.id)===selected);
  const filtered=useMemo(()=>conversations.filter(x=>`${x.subject} ${x.kind} ${x.members.map(m=>m.username).join(' ')}`.toLowerCase().includes(search.toLowerCase())),[conversations,search]);
  const send=async()=>{if(!selected||!body.trim())return;try{await sendCommunicationMessage(selected,{body,reference_type:referenceType||undefined,reference_id:referenceId||undefined});setBody('');setReferenceType('');setReferenceId('');const x=await fetchCommunicationMessages(selected);setMessages(x.messages);await load();}catch(e){toast('Message was not sent','bad',e instanceof Error?e.message:'Request failed');}};
  const newConversation=async()=>{if(!composer.subject.trim())return toast('Add a subject','bad');try{const c=await createCommunicationConversation({kind:composer.kind,subject:composer.subject,member_ids:composer.members});setComposer({kind:'group',subject:'',members:[]});await load();setSelected(String(c.id));toast('Conversation created','ok');}catch(e){toast('Conversation was not created','bad',e instanceof Error?e.message:'Request failed');}};
  const newTask=async()=>{if(!selected||!taskForm.title.trim())return toast('Select a conversation and add a task title','bad');try{await createCommunicationTask({conversation_id:selected,...taskForm,assigned_to:taskForm.assigned_to||null,due_at:taskForm.due_at||null});setTaskForm({title:'',description:'',assigned_to:'',priority:'normal',due_at:''});await load();toast('Task assigned','ok');}catch(e){toast('Task was not created','bad',e instanceof Error?e.message:'Request failed');}};
  const updateTask=async(t:CommunicationTask,status:string)=>{try{await updateCommunicationTask(t.id,{status,version:Number(t.version)});await load();}catch(e){toast('Task update failed','bad',e instanceof Error?e.message:'Request failed');}};
  if(focus==='audit')return <AuditPage events={audit} loading={loading} />;
  return <div className="grid gap-4">
    <PageHeader eyebrow="Communication" title={focus==='tasks'?'Tasks & assignments':focus==='enquiries'?'Employee enquiries':'Team communication'} subtitle="Discuss work, attach ERP references, assign responsibility, and keep every operational conversation in one place." actions={<button className="btn-ghost" onClick={()=>void load()}><RefreshCw size={15}/> Refresh</button>} />
    <div className="grid xl:grid-cols-[280px_minmax(0,1fr)_320px] gap-4 items-start">
      <Card pad={false}>
        <div className="p-3 border-b border-line"><div className="flex gap-2"><Input placeholder="Search conversations" value={search} onChange={e=>setSearch(e.target.value)} /><button className="btn-primary btn-sm" title="New conversation" onClick={()=>document.getElementById('new-conversation')?.scrollIntoView({behavior:'smooth'})}><Plus size={15}/></button></div></div>
        <div className="max-h-[62vh] overflow-auto">{loading&&!conversations.length?<div className="p-5 text-sm text-muted">Loading conversations…</div>:filtered.map(c=><button key={c.id} onClick={()=>setSelected(String(c.id))} className={cls('w-full text-left p-3 border-b border-line hover:bg-surface2',selected===String(c.id)&&'bg-violet/[.08] border-l-2 border-l-violet')}><div className="flex items-center gap-2"><MessageCircle size={15} className="text-violet"/><span className="font-semibold truncate flex-1">{c.subject}</span><span className="text-[10px] text-muted uppercase">{c.kind}</span></div><div className="text-[11.5px] text-muted mt-1 truncate">{c.last_message?.body||'No messages yet'}</div><div className="text-[10.5px] text-faint mt-1">{c.members.map(m=>m.username).join(', ')}</div></button>)}{!filtered.length&&<div className="p-5 text-sm text-muted">No conversations yet.</div>}</div>
        <div id="new-conversation" className="p-3 border-t border-line grid gap-2"><div className="font-semibold text-sm">Start conversation</div><Select value={composer.kind} onChange={e=>setComposer({...composer,kind:e.target.value})} options={[{value:'group',label:'Team discussion'},{value:'direct',label:'Direct message'},{value:'enquiry',label:'Employee enquiry'}]} /><Input placeholder="Subject" value={composer.subject} onChange={e=>setComposer({...composer,subject:e.target.value})}/><select multiple className="input h-20 text-xs" value={composer.members} onChange={e=>setComposer({...composer,members:Array.from(e.target.selectedOptions).map(o=>o.value)})} aria-label="Conversation participants">{users.filter(u=>String(u.id)!==String(getERPUser()?.id)).map(u=><option key={u.id} value={u.id}>{u.username} · {roleLabel(u.role)}</option>)}</select><button className="btn-primary btn-sm" onClick={()=>void newConversation()}><Plus size={14}/> Create conversation</button></div>
      </Card>
      {focus==='chat'?<Card pad={false}>
        <div className="px-4 py-3 border-b border-line flex items-center gap-2"><div className="flex-1"><div className="font-semibold">{selectedConversation?.subject||emptyMessage}</div>{selectedConversation&&<div className="text-[11.5px] text-muted">{selectedConversation.members.map(m=>m.username).join(', ')}</div>}</div>{selectedConversation?.kind==='enquiry'&&<StatusBadge s={selectedConversation.closed?'Closed':'Open'}/>}</div>
        <div className="min-h-[420px] max-h-[58vh] overflow-auto p-4 space-y-3">{!selectedConversation?<EmptyState icon={MessageCircle} title="No conversation selected" body="Start a conversation or select one from the left."/>:!messages.length?<div className="text-sm text-muted text-center py-10">No messages yet. Start the conversation.</div>:messages.map(m=><div key={m.id} className={cls('max-w-[88%] rounded-xl p-3',String(m.sender_id)===String(getERPUser()?.id)?'ml-auto bg-violet/[.1]':'bg-surface2')}><div className="flex gap-2 items-center text-[11px] text-muted"><b>{m.sender}</b><span>{fmtDT(m.created_at)}</span></div><div className="text-[13px] whitespace-pre-wrap mt-1">{m.body}</div>{m.reference_type&&<div className="inline-flex items-center gap-1 mt-2 text-[11px] text-violet"><Link2 size={12}/> {m.reference_type}: {m.reference_id}</div>}</div>)}</div>
        <div className="border-t border-line p-3 grid gap-2"><Textarea rows={3} placeholder="Write a message…" value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();void send();}}}/><div className="flex flex-wrap gap-2"><Input className="max-w-[150px]" placeholder="ERP ref type" value={referenceType} onChange={e=>setReferenceType(e.target.value)}/><Input className="max-w-[180px]" placeholder="Reference ID / LR no." value={referenceId} onChange={e=>setReferenceId(e.target.value)}/><button className="btn-primary ml-auto" onClick={()=>void send()} disabled={!selected||!body.trim()}><Send size={15}/> Send</button></div></div>
      </Card>:<Card><PageHeader eyebrow="Communication" title={focus==='tasks'?'Assigned tasks':'Employee enquiries'} subtitle="These records are shared with the conversation participants." />{focus==='tasks'?<div className="grid gap-2">{tasks.map(t=><div key={t.id} className="border border-line rounded-lg p-3"><div className="flex gap-2 items-center"><ClipboardList size={15} className="text-violet"/><b className="flex-1">{t.title}</b><StatusBadge s={t.status}/></div><div className="text-xs text-muted mt-1">{t.subject} · assigned to {t.assigned_username||'Unassigned'} · {t.priority}</div><div className="flex gap-2 mt-2"><Select value={t.status} onChange={e=>void updateTask(t,e.target.value)} options={['todo','in_progress','blocked','done','cancelled'].map(x=>({value:x,label:x.replace('_',' ')}))}/></div></div>)}{!tasks.length&&<p className="text-sm text-muted">No communication tasks yet.</p>}</div>:<p className="text-sm text-muted">Create an enquiry from the conversation panel. Enquiries remain visible to their participants and administrators.</p>}</Card>}
      <Card><div className="flex items-center gap-2 mb-3"><ClipboardList size={16} className="text-violet"/><h2 className="font-semibold flex-1">Assign ERP task</h2></div><p className="text-xs text-muted mb-3">Create a task linked to the selected conversation.</p><div className="grid gap-3"><Field label="Task title"><Input value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})} placeholder="e.g. Confirm LR delivery"/></Field><Field label="Description"><Textarea rows={3} value={taskForm.description} onChange={e=>setTaskForm({...taskForm,description:e.target.value})}/></Field><Field label="Assign to"><Select value={taskForm.assigned_to} onChange={e=>setTaskForm({...taskForm,assigned_to:e.target.value})} options={[{value:'',label:'Unassigned'},...users.map(u=>({value:String(u.id),label:`${u.username} · ${roleLabel(u.role)}`}))]}/></Field><div className="grid grid-cols-2 gap-2"><Field label="Priority"><Select value={taskForm.priority} onChange={e=>setTaskForm({...taskForm,priority:e.target.value})} options={['low','normal','high','urgent']}/></Field><Field label="Due date"><Input type="datetime-local" value={taskForm.due_at} onChange={e=>setTaskForm({...taskForm,due_at:e.target.value})}/></Field></div><button className="btn-primary" onClick={()=>void newTask()} disabled={!selected}><CheckCircle2 size={15}/> Assign task</button></div></Card>
    </div>
  </div>;
}

function AuditPage({events,loading}:{events:any[];loading:boolean}) { return <div><PageHeader eyebrow="Communication Admin" title="Communication oversight" subtitle="Administrator audit trail of conversations, messages, and assigned tasks."/><Card pad={false}>{loading?<div className="p-5 text-sm text-muted">Loading audit…</div>:<div className="overflow-auto"><table className="w-full text-xs min-w-[760px]"><thead><tr className="border-b border-line text-left text-muted"><th className="px-3 py-2">When</th><th className="px-3 py-2">Actor</th><th className="px-3 py-2">Action</th><th className="px-3 py-2">Entity</th><th className="px-3 py-2">Details</th></tr></thead><tbody>{events.map(e=><tr key={e.id} className="border-b border-line/60"><td className="px-3 py-2">{fmtDT(e.created_at)}</td><td className="px-3 py-2 font-semibold">{e.actor||'system'}</td><td className="px-3 py-2">{e.action}</td><td className="px-3 py-2">{e.entity_type} #{e.entity_id}</td><td className="px-3 py-2 max-w-[360px] truncate">{JSON.stringify(e.after_state)}</td></tr>)}</tbody></table>{!events.length&&<div className="p-5 text-sm text-muted">No communication activity recorded.</div>}</div>}</Card></div>; }

export function CommunicationTasks(){return <Communication/>;}
export function CommunicationEnquiries(){return <Communication/>;}
export function CommunicationAudit(){return <Communication/>;}
