import React,{useEffect,useMemo,useState} from 'react';
import {BarChart3,CheckCircle2,Clock3,MessageSquare,Paperclip,RefreshCw,Search,UserRound} from 'lucide-react';
import {commentFeedback,fetchAdminUsers,listFeedback,openFeedbackAttachment,updateFeedback,type FeedbackItem,type AdminAuthUser} from '../lib/api';

const STATUSES=['New','Reviewing','Accepted','Planned','In Development','Ready for Testing','Fixed','Verified','Closed','Duplicate','Not Planned','Need More Information'];
const IMPACT=['Low','Medium','High','Blocking'];
const active=s=>!['Verified','Closed','Duplicate','Not Planned'].includes(s);

export function FeedbackReview(){
 const [items,setItems]=useState<FeedbackItem[]>([]),[users,setUsers]=useState<AdminAuthUser[]>([]),[selected,setSelected]=useState<string>(''),[q,setQ]=useState(''),[status,setStatus]=useState('Active'),[module,setModule]=useState('All'),[impact,setImpact]=useState('All'),[loading,setLoading]=useState(true),[msg,setMsg]=useState(''),[note,setNote]=useState(''),[internal,setInternal]=useState(true),[resolution,setResolution]=useState('');
 const load=async()=>{setLoading(true);setMsg('');try{const [f,u]=await Promise.all([listFeedback(),fetchAdminUsers()]);setItems(f.items);setUsers(u.users.filter(x=>x.active));if(!selected&&f.items[0])setSelected(String(f.items[0].id))}catch(e:any){setMsg(e.message)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const modules=useMemo(()=>['All',...Array.from(new Set(items.map(x=>x.module||'Unspecified'))).sort()], [items]);
 const filtered=useMemo(()=>items.filter(x=>(status==='All'||(status==='Active'?active(x.status):x.status===status))&&(module==='All'||(x.module||'Unspecified')===module)&&(impact==='All'||x.impact===impact)&&(!q||[x.feedback_no,x.description,x.full_name,x.username,x.screen_id,x.record_no].join(' ').toLowerCase().includes(q.toLowerCase()))),[items,status,module,impact,q]);
 const item=items.find(x=>String(x.id)===selected)||filtered[0];
 useEffect(()=>{setResolution(item?.resolution||'')},[item?.id]);
 const counts={new:items.filter(x=>x.status==='New').length,active:items.filter(x=>active(x.status)).length,blocking:items.filter(x=>x.impact==='Blocking'&&active(x.status)).length,testing:items.filter(x=>x.status==='Ready for Testing').length,closed:items.filter(x=>['Verified','Closed'].includes(x.status)).length};
 const patch=async(data:Record<string,unknown>)=>{if(!item)return;try{await updateFeedback(item.id,data);await load()}catch(e:any){setMsg(e.message)}};
 const addNote=async()=>{if(!item||!note.trim())return;try{await commentFeedback(item.id,note.trim(),internal);setNote('');await load()}catch(e:any){setMsg(e.message)}};
 const openFile=async(id:string)=>{try{const a=await openFeedbackAttachment(id);window.open(a.url,'_blank','noopener')}catch(e:any){setMsg(e.message)}};
 return <div className="page space-y-4">
  <div className="page-head"><div><div className="eyebrow">Administration</div><h1>Feedback & Review</h1><p>Central UAT inbox for ERP issues, improvements and employee review feedback.</p></div><button className="btn-ghost" onClick={()=>void load()}><RefreshCw size={15}/>{loading?'Loading…':'Refresh'}</button></div>
  <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
   {[['New',counts.new,MessageSquare],['Open',counts.active,Clock3],['Blocking',counts.blocking,BarChart3],['Ready for testing',counts.testing,CheckCircle2],['Verified / closed',counts.closed,CheckCircle2]].map(([l,n,I]:any)=><div className="card p-3" key={l}><div className="flex items-center gap-2 text-muted text-[11px] font-semibold"><I size={14}/>{l}</div><div className="text-2xl font-bold mt-1">{n}</div></div>)}
  </div>
  <div className="card p-3 grid md:grid-cols-4 gap-2">
   <div className="relative"><Search size={14} className="absolute left-3 top-3 text-muted"/><input className="input w-full pl-9" placeholder="Search feedback, user, screen…" value={q} onChange={e=>setQ(e.target.value)}/></div>
   <select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option>Active</option><option>All</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select>
   <select className="input" value={module} onChange={e=>setModule(e.target.value)}>{modules.map(x=><option key={x}>{x}</option>)}</select>
   <select className="input" value={impact} onChange={e=>setImpact(e.target.value)}><option>All</option>{IMPACT.map(x=><option key={x}>{x}</option>)}</select>
  </div>
  {msg&&<div className="card p-3 text-[12px] font-semibold">{msg}</div>}
  <div className="grid lg:grid-cols-[minmax(320px,0.8fr)_minmax(0,1.4fr)] gap-4 items-start">
   <div className="card overflow-hidden"><div className="px-3 py-2 border-b border-line text-[12px] font-semibold">{filtered.length} feedback items</div><div className="max-h-[68vh] overflow-y-auto">{filtered.map(x=><button key={x.id} onClick={()=>setSelected(String(x.id))} className={'w-full text-left p-3 border-b border-line hover:bg-surface2 '+(String(item?.id)===String(x.id)?'bg-surface2':'')}><div className="flex items-center gap-2"><b className="text-[12.5px]">{x.feedback_no}</b><span className="chip">{x.impact}</span><span className="chip">{x.status}</span></div><div className="text-[12.5px] mt-1 line-clamp-2">{x.description||x.title||'Attachment feedback'}</div><div className="text-[10.5px] text-muted mt-1">{x.full_name||x.username} · {x.module||x.screen_id} · {new Date(x.created_at).toLocaleDateString()}</div></button>)}{!filtered.length&&<div className="p-5 text-sm text-muted">No feedback matches these filters.</div>}</div></div>
   {item?<div className="space-y-3">
    <div className="card p-4"><div className="flex flex-wrap gap-2 items-center"><h2 className="font-bold">{item.feedback_no}</h2><span className="chip">{item.feedback_type}</span><span className="chip">{item.impact}</span><span className="chip">{item.status}</span></div><div className="text-[11.5px] text-muted mt-2">{item.full_name||item.username} ({item.role}) · {item.mode} · {new Date(item.created_at).toLocaleString()}</div><p className="mt-3 text-[13.5px] whitespace-pre-wrap">{item.description}</p>{item.points?.map(p=><div className="mt-1 text-[12.5px]" key={p.id}>• {p.body}</div>)}
     <div className="mt-3 rounded-lg bg-surface2 p-3 grid sm:grid-cols-2 gap-2 text-[11.5px]"><div><b>Module:</b> {item.module||'—'}</div><div><b>Screen:</b> {item.screen_id||'—'}</div><div><b>Record:</b> {item.record_no||'—'}</div><div><b>Route:</b> {item.route||'—'}</div></div>
     {!!item.attachments?.length&&<div className="flex flex-wrap gap-2 mt-3">{item.attachments.map((a:any)=><button className="btn-ghost h-9" key={a.id} onClick={()=>void openFile(a.id)}><Paperclip size={13}/>{a.name}</button>)}</div>}
    </div>
    <div className="card p-4"><h3 className="font-semibold mb-3">Triage & ownership</h3><div className="grid sm:grid-cols-3 gap-2"><label className="text-[11px] font-semibold">Status<select className="input w-full mt-1" value={item.status} onChange={e=>void patch({status:e.target.value})}>{STATUSES.filter(x=>x!=='Duplicate'||item.status==='Duplicate').map(x=><option key={x}>{x}</option>)}</select></label><label className="text-[11px] font-semibold">Impact<select className="input w-full mt-1" value={item.impact} onChange={e=>void patch({impact:e.target.value})}>{IMPACT.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-[11px] font-semibold">Assigned to<select className="input w-full mt-1" value={(item as any).assigned_to||''} onChange={e=>void patch({assigned_to:e.target.value||null})}><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>{u.full_name||u.username}</option>)}</select></label></div>
     <label className="text-[11px] font-semibold block mt-3">Resolution / implementation note<textarea className="input w-full min-h-20 mt-1" value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="What changed, why it was closed, or what the reviewer should verify…"/></label><div className="flex flex-wrap gap-2 items-end mt-3"><button className="btn-primary h-9" onClick={()=>void patch({resolution})}>Save resolution</button><label className="text-[11px] font-semibold ml-auto">Mark as duplicate<select className="input h-9 ml-2" value="" onChange={e=>{if(e.target.value)void patch({status:'Duplicate',duplicate_of:e.target.value})}}><option value="">Select original…</option>{items.filter(x=>String(x.id)!==String(item.id)&&x.status!=='Duplicate').map(x=><option key={x.id} value={x.id}>{x.feedback_no} · {x.description.slice(0,45)}</option>)}</select></label></div>
    </div>
    <div className="card p-4"><h3 className="font-semibold">Discussion & internal notes</h3><div className="space-y-2 mt-3">{(item as any).comments?.map((c:any)=><div className="rounded-lg bg-surface2 p-3" key={c.id}><div className="flex items-center gap-2 text-[10.5px] text-muted"><UserRound size={12}/>{c.full_name||c.username}{c.internal&&<span className="chip">Internal</span>}<span className="ml-auto">{new Date(c.created_at).toLocaleString()}</span></div><div className="text-[12.5px] mt-1 whitespace-pre-wrap">{c.body}</div></div>)}{!(item as any).comments?.length&&<div className="text-[12px] text-muted">No discussion yet.</div>}</div><textarea className="input w-full min-h-20 mt-3" placeholder="Add review note…" value={note} onChange={e=>setNote(e.target.value)}/><div className="flex items-center gap-3 mt-2"><label className="text-[11.5px] flex items-center gap-2"><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/> Internal admin note</label><button className="btn-primary h-9 ml-auto" disabled={!note.trim()} onClick={()=>void addNote()}>Add note</button></div></div>
   </div>:<div className="card p-8 text-sm text-muted">Select feedback to review.</div>}
  </div>
 </div>
}

