import React,{useEffect,useState} from 'react';
import {AreaChart,Area,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer,BarChart,Bar,PieChart,Pie,Cell} from 'recharts';
import {LayoutDashboard,Truck,Package,Users,Landmark,Warehouse,FileText,ChartNoAxesCombined,ShieldCheck,LogOut,RefreshCw,Search,Menu,CalendarDays,MapPinned,AlertTriangle,ArrowUpRight,Wallet,Boxes,Activity,Building2} from 'lucide-react';
import {fetchERPDashboard,fetchERPAnalytics,logoutERP,type ERPUser,type ERPDashboard,type ERPAnalytics} from '../lib/api';
const currency=(n:number)=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0});
const num=(n:number|string)=>Number(n||0).toLocaleString('en-IN');
const palette=['#6474f5','#20bfa8','#f6ac54','#d77ce7','#55a9df','#f07183'];
const nav=[['Overview',LayoutDashboard],['Consignments',Package],['Operations',Truck],['Customers',Users],['Branches',Building2],['Fleet',Truck],['Rail logistics',Boxes],['Warehouse',Warehouse],['Billing & Finance',Wallet],['Reports & MIS',ChartNoAxesCombined],['Administration',ShieldCheck]] as const;
export default function FullLiveDashboard({user,onSignOut}:{user:ERPUser;onSignOut:()=>void}){
 const [dashboard,setDashboard]=useState<ERPDashboard|null>(null);
 const [analytics,setAnalytics]=useState<ERPAnalytics|null>(null);
 const [error,setError]=useState('');
 const [busy,setBusy]=useState(false);
 const [selected,setSelected]=useState('Overview');
 const [mobileNav,setMobileNav]=useState(false);
 const [search,setSearch]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const [d,a]=await Promise.all([fetchERPDashboard(),fetchERPAnalytics()]);setDashboard(d);setAnalytics(a);}catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard');}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const counts=dashboard?.counts;
 const totalFreight=analytics?.monthly.reduce((s,x)=>s+x.freight,0)||0;
 const totalPending=analytics?.ageing.reduce((s,x)=>s+x.outstanding,0)||0;
 const cards=[{name:'Total LRs',value:num(counts?.lrs||0),icon:Package,sub:'Historical consignments'},{name:'Customers',value:num(counts?.customers||0),icon:Users,sub:'Customer master'},{name:'Branches',value:num(counts?.branches||0),icon:Building2,sub:'Branch master'},{name:'Bills generated',value:num(counts?.bills||0),icon:FileText,sub:'Historical billing'},{name:'Ledger entries',value:num(counts?.ledger_entries||0),icon:Landmark,sub:'Account transactions'},{name:'Outstanding bills',value:currency(totalPending),icon:Wallet,sub:'Historical pending amounts'},{name:'12-month LR freight',value:currency(totalFreight),icon:Truck,sub:'Last 12 months in snapshot'},{name:'Active vehicles',value:'—',icon:Activity,sub:'Live tracking not connected'}];
 const lrs=(dashboard?.recentLrs||[]) as Record<string,unknown>[];
 const bills=(dashboard?.recentBills||[]) as Record<string,unknown>[];
 const filtered=lrs.filter(x=>!search||String(x.lr_number||'').toLowerCase().includes(search.toLowerCase()));
 const tooltipStyle={background:'#171a2c',border:'1px solid #30354d',borderRadius:10,color:'#e5e9ff'};
 return <div className="min-h-screen bg-[#0d1020] text-[#e7eafb] flex">
  {mobileNav&&<div className="fixed inset-0 bg-black/60 z-30 lg:hidden" onClick={()=>setMobileNav(false)}/>}
  <aside className={`fixed lg:sticky top-0 h-screen z-40 w-[254px] shrink-0 bg-[#14182b] border-r border-[#2b3045] flex flex-col transition-transform lg:translate-x-0 ${mobileNav?'translate-x-0':'-translate-x-full'}`}>
   <div className="px-5 py-6 border-b border-[#2b3045]"><div className="font-bold text-lg tracking-tight">SK <span className="text-[#ee6269]">TRANSLINES</span></div><div className="text-[11px] text-[#9299b2] mt-1">ENTERPRISE RESOURCE PLANNING</div></div>
   <div className="text-[10px] uppercase tracking-[.16em] text-[#777f9c] px-5 mt-6 mb-2">Workspace</div>
   <nav className="px-3 space-y-1 overflow-y-auto flex-1">{nav.map(([label,Icon])=><button key={label} onClick={()=>{setSelected(label);setMobileNav(false);}} className={`w-full flex items-center gap-3 px-3 py-3 rounded-xl text-[13px] text-left transition ${selected===label?'bg-[#353b68] text-white':'text-[#aeb6d1] hover:bg-[#20253d]'}`}><Icon size={17}/><span>{label}</span>{selected===label&&<span className="ml-auto w-1.5 h-1.5 rounded-full bg-[#8e9aff]"/>}</button>)}</nav>
   <div className="p-4 border-t border-[#2b3045]"><div className="text-sm font-semibold">{user.username}</div><div className="text-xs text-[#9099b8] capitalize mb-3">{user.role} · PostgreSQL</div><button className="flex items-center gap-2 text-sm text-[#c6cbe0]" onClick={async()=>{await logoutERP();onSignOut();}}><LogOut size={16}/> Sign out</button></div>
  </aside>
  <main className="flex-1 min-w-0">
   <header className="h-[72px] border-b border-[#2b3045] flex items-center justify-between gap-3 px-4 sm:px-7 bg-[#111527]"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={()=>setMobileNav(true)}><Menu size={22}/></button><div className="text-sm text-[#9da6c0]">Workspace <span className="mx-2">/</span> <span className="text-white">{selected}</span></div></div><div className="flex items-center gap-3"><span className="hidden sm:flex items-center gap-2 text-xs text-[#abb3ce]"><CalendarDays size={14}/> Data through 08 Jun 2025</span><button onClick={()=>void load()} disabled={busy} className="rounded-lg bg-[#2c3353] p-2.5 hover:bg-[#3b456d]" title="Refresh"><RefreshCw size={16} className={busy?'animate-spin':''}/></button><div className="w-9 h-9 rounded-full bg-[#5261a4] flex items-center justify-center font-bold">{user.username.slice(0,1).toUpperCase()}</div></div></header>
   <div className="max-w-[1650px] mx-auto px-4 sm:px-7 py-7 space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[#9ca6c7] text-xs uppercase tracking-widest mb-2">Operations control center</div><h1 className="text-2xl sm:text-3xl font-bold">{selected==='Overview'?'Dashboard Overview':selected}</h1><p className="text-[#99a3c2] text-sm mt-1">SK Translines · Verified historical PostgreSQL records</p></div><span className="text-xs bg-[#233b3c] text-[#85ddbd] rounded-full px-3 py-2 flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-[#63caa3]"/> Database connected</span></div>
    <div className="bg-[#27243c] border border-[#544266] rounded-xl p-3 text-[#ddc4ef] text-xs flex gap-2"><AlertTriangle size={16} className="shrink-0"/><span>Historical snapshot as of 8 June 2025. These figures are not live operational statuses. Modules not yet migrated remain read-only or unavailable.</span></div>
    {error&&<div role="alert" className="bg-[#482738] rounded-lg p-4 text-[#ffb9c1]">{error} <button className="underline ml-2" onClick={()=>void load()}>Retry</button></div>}
    {selected!=='Overview'&&<div className="rounded-xl bg-[#1a1e33] border border-[#30364e] p-4 text-sm text-[#aeb8d5]">{selected} workspace is being migrated. The overview below uses verified PostgreSQL data; editable workflows are not yet enabled.</div>}
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-4">{cards.map((c,i)=><div key={c.name} className="bg-[#191e33] border border-[#2d344c] rounded-2xl p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><div className="text-[#9ea9c7] text-xs sm:text-sm">{c.name}</div><span className="rounded-xl p-2 bg-[#293150]" style={{color:palette[i%palette.length]}}><c.icon size={17}/></span></div><div className="text-xl sm:text-2xl font-bold mt-3 break-words">{c.value}</div><div className="text-[#7985a5] text-[11px] mt-2">{c.sub}</div></div>)}</div>
    <div className="grid xl:grid-cols-3 gap-4"><section className="xl:col-span-2 bg-[#191e33] border border-[#2d344c] rounded-2xl p-5"><div className="flex items-center justify-between mb-5"><div><h2 className="font-semibold">LR booking trend</h2><p className="text-xs text-[#929dbc] mt-1">Last 12 available months · historical bookings</p></div><ChartNoAxesCombined size={19} className="text-[#919edb]"/></div><div className="h-[260px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={analytics?.monthly||[]}><defs><linearGradient id="lrFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7c8cff" stopOpacity={.35}/><stop offset="100%" stopColor="#7c8cff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#30364e" vertical={false}/><XAxis dataKey="month" tick={{fill:'#929dbb',fontSize:10}}/><YAxis tick={{fill:'#929dbb',fontSize:11}}/><Tooltip contentStyle={tooltipStyle}/><Area dataKey="lrs" type="monotone" stroke="#8493ff" strokeWidth={3} fill="url(#lrFill)"/></AreaChart></ResponsiveContainer></div></section>
    <section className="bg-[#191e33] border border-[#2d344c] rounded-2xl p-5"><h2 className="font-semibold">Outstanding ageing</h2><p className="text-xs text-[#929dbc] mt-1">Pending bills at snapshot date</p><div className="h-[230px] mt-4"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={analytics?.ageing||[]} dataKey="outstanding" nameKey="bucket" innerRadius={56} outerRadius={85} paddingAngle={3}>{analytics?.ageing.map((_,i)=><Cell key={i} fill={palette[i%palette.length]}/>)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(v:number)=>currency(v)}/></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2 text-xs">{analytics?.ageing.map((a,i)=><div key={a.bucket} className="flex items-center gap-2"><span className="w-2 h-2 rounded-full" style={{background:palette[i%palette.length]}}/>{a.bucket} days <span className="ml-auto text-[#aab5d0]">{currency(a.outstanding)}</span></div>)}</div></section></div>
    <div className="grid xl:grid-cols-2 gap-4"><section className="bg-[#191e33] border border-[#2d344c] rounded-2xl p-5"><h2 className="font-semibold">Monthly freight value</h2><p className="text-xs text-[#929dbc] mt-1">Recorded LR total freight by month</p><div className="h-[245px] mt-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics?.monthly||[]}><CartesianGrid stroke="#30364e" vertical={false}/><XAxis dataKey="month" tick={{fill:'#929dbb',fontSize:10}}/><YAxis tick={{fill:'#929dbb',fontSize:10}} tickFormatter={v=>(v/100000).toFixed(0)+'L'}/><Tooltip contentStyle={tooltipStyle} formatter={(v:number)=>currency(v)}/><Bar dataKey="freight" fill="#43c6b0" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="bg-[#191e33] border border-[#2d344c] rounded-2xl p-5"><h2 className="font-semibold">Top branches by LRs</h2><p className="text-xs text-[#929dbc] mt-1">Branch IDs from legacy database</p><div className="h-[245px] mt-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics?.branches||[]} layout="vertical"><CartesianGrid stroke="#30364e" horizontal={false}/><XAxis type="number" tick={{fill:'#929dbb',fontSize:10}}/><YAxis type="category" dataKey="branch_id" width={60} tick={{fill:'#929dbb',fontSize:11}}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="lrs" fill="#8992f9" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div></section></div>
    <section className="bg-[#191e33] border border-[#2d344c] rounded-2xl p-5"><div className="flex items-center justify-between flex-wrap gap-3 mb-4"><div><h2 className="font-semibold">Consignment control tower</h2><p className="text-xs text-[#929dbc] mt-1">Most recent LR records · historical, not GPS tracking</p></div><div className="relative"><Search size={15} className="absolute left-3 top-2.5 text-[#929dbc]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search LR number" className="bg-[#111629] border border-[#343b55] rounded-lg pl-9 pr-3 py-2 text-sm outline-none w-48"/></div></div><div className="overflow-x-auto"><table className="w-full text-left text-xs sm:text-sm min-w-[720px]"><thead className="text-[#939fbd] border-b border-[#353b52]"><tr>{['LR Number','Created','Branch ID','Weight','Total Freight','Source'].map(x=><th className="py-3 px-3 font-medium" key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map((x,i)=><tr key={i} className="border-b border-[#292f44] hover:bg-[#222941]"><td className="px-3 py-3 text-[#aeb8ff] font-semibold">{String(x.lr_number??'—')}</td><td className="px-3 py-3">{String(x.created_date??'—').slice(0,10)}</td><td className="px-3 py-3">{String(x.branch_id??'—')}</td><td className="px-3 py-3">{num(Number(x.total_weight||0))}</td><td className="px-3 py-3">{currency(Number(x.total_freight||0))}</td><td className="px-3 py-3 text-[#8bcabf]">PostgreSQL</td></tr>)}</tbody></table></div></section>
    <section className="bg-[#191e33] border border-[#2d344c] rounded-2xl p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-semibold">Recent billing</h2><p className="text-xs text-[#929dbc] mt-1">Actual historical bill records</p></div><FileText size={18} className="text-[#919edb]"/></div><div className="overflow-x-auto"><table className="w-full text-left text-xs sm:text-sm min-w-[650px]"><thead className="text-[#939fbd] border-b border-[#353b52]"><tr>{['Bill Number','Bill Date','Net Amount','Pending Amount'].map(x=><th key={x} className="py-3 px-3 font-medium">{x}</th>)}</tr></thead><tbody>{bills.map((x,i)=><tr key={i} className="border-b border-[#292f44]"><td className="px-3 py-3 text-[#aeb8ff]">{String(x.bill_number??'—')}</td><td className="px-3 py-3">{String(x.bill_date??'—').slice(0,10)}</td><td className="px-3 py-3">{currency(Number(x.net_amt||0))}</td><td className="px-3 py-3">{currency(Number(x.pending_amt||0))}</td></tr>)}</tbody></table></div></section>
    <div className="text-center text-[#6f7c9e] text-xs pb-5">SK Translines ERP · PostgreSQL historical dashboard · Read-only migration phase</div>
   </div>
  </main>
 </div>;
}
