import React, { useEffect, useMemo, useState } from 'react';
import { useDB, useUI, A, lookup } from '../store/store';
import { PageHeader, KPI, StatusBadge, Field, Input, Select, Textarea, Radio, FormSection, DocNo, Card, Check, KV, EmptyState } from '../components/ui';
import { DataTable, Col } from '../components/DataTable';
import { Drawer } from '../components/overlays';
import { fmtDate, inr, num, cls, ymd } from '../lib/util';
import { Plus, Eye, Pencil, Trash2, Upload, Database, ArrowRight, Building2, MapPin, Package, Users, Landmark, FileText, Search } from 'lucide-react';

export type FieldDef = { k: string; l: string; t?: 'text' | 'number' | 'date' | 'select' | 'bool' | 'textarea' | 'radio' | 'email' | 'file'; opts?: ((db: any) => any[]) | string[]; req?: boolean; span?: number; section?: string; hint?: string; show?: (f: any) => boolean };
export type EntityDef = { key: string; coll: string; title: string; singular: string; legacy: string[]; group: string; desc: string; fields: FieldDef[]; cols: (db: any) => Col[]; kpis?: (db: any, rows: any[]) => React.ReactNode; record?: string; defaults?: (db: any) => any; icon?: any; filterRows?: (r: any) => boolean; quick?: { key: string; label: string; fn: (r: any) => boolean }[]; eyebrow?: string; actions?: React.ReactNode };

const opt = (db: any, o: FieldDef['opts']) => (typeof o === 'function' ? o(db) : o || []);
const cityOpts = (db: any) => db.cities.map((c: any) => ({ value: c.id, label: c.name }));
const branchOpts = (db: any) => db.branches.map((b: any) => ({ value: b.id, label: b.name }));
const stateOpts = (db: any) => db.states.map((s: any) => s.name);
const yes = (v: any) => (v ? <StatusBadge s="Yes" tone="ok" dot={false} /> : <span className="text-faint">No</span>);

export function CrudPage({ def }: { def: EntityDef }) {
  const db = useDB();
  const params = useUI((s) => s.params);
  const { openRecord, ask } = useUI.getState();
  const [form, setForm] = useState<any>(null);
  const [view, setView] = useState<any>(null);
  const rows = ((db as any)[def.coll] as any[]).filter(def.filterRows || (() => true));
  useEffect(() => { if (params.edit) { const r = rows.find((x) => x.id === params.edit); if (r) setForm(r); } if (params.new) setForm(def.defaults?.(db) || {}); }, [params.edit, params.new]);
  const sections = [...new Set(def.fields.map((f) => f.section || 'Details'))];
  return (
    <div>
      <PageHeader eyebrow={def.eyebrow || 'Masters'} title={def.title} subtitle={def.desc} actions={<>{def.actions}<button className="btn-primary" onClick={() => setForm(def.defaults?.(db) || {})}><Plus size={15} /> Add {def.singular.toLowerCase()}</button></>} />
      {def.kpis && <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-4">{def.kpis(db, rows)}</div>}
      <DataTable id={`m-${def.key}`} rows={rows} quickFilters={def.quick} onRow={(r) => (def.record ? openRecord(def.record, r.id) : setView(r))} cols={def.cols(db)} rowActions={(r: any) => [
        { label: 'View', icon: Eye, onClick: () => (def.record ? openRecord(def.record, r.id) : setView(r)) },
        { label: 'Edit', icon: Pencil, onClick: () => setForm(r) },
        { label: 'Delete', icon: Trash2, tone: 'bad', onClick: () => ask({ title: `Delete ${def.singular.toLowerCase()}?`, body: `${r.name || r.number || r.title || ''} will be removed. Records that reference it keep their history.`, tone: 'bad', confirmLabel: 'Delete', onConfirm: () => A.remove(def.coll, r.id, def.singular) }) },
      ]} />
      {view && (
        <Drawer open onClose={() => setView(null)} title={view.name || view.number || view.title || def.singular} subtitle={def.singular} footer={<><button className="btn-ghost" onClick={() => { setForm(view); setView(null); }}><Pencil size={14} /> Edit</button></>}>
          <div className="p-4 sm:p-5 grid gap-4">{sections.map((s) => <Card key={s} title={s}><KV cols={2} items={def.fields.filter((f) => (f.section || 'Details') === s).map((f) => [f.l, display(db, f, view[f.k])])} /></Card>)}</div>
        </Drawer>
      )}
      {form && <EntityForm def={def} init={form} onClose={() => { setForm(null); useUI.getState().set({ params: {} }); }} />}
    </div>
  );
}
function display(db: any, f: FieldDef, v: any) {
  if (f.t === 'bool') return v ? 'Yes' : 'No';
  if (f.t === 'date') return fmtDate(v);
  if (f.t === 'select' && typeof f.opts === 'function') { const o = f.opts(db).find((x: any) => (typeof x === 'string' ? x === v : x.value === v)); return typeof o === 'string' ? o : o?.label || v || '—'; }
  if (f.t === 'number' && /amt|rent|salary|limit|rate|deposit|emi|charge|amount/i.test(f.k)) return inr(v);
  return v === '' || v == null ? '—' : String(v);
}
export function EntityForm({ def, init, onClose }: { def: EntityDef; init: any; onClose: () => void }) {
  const db = useDB();
  const [f, setF] = useState<any>(() => ({ ...(def.defaults?.(db) || {}), ...init }));
  const [err, setErr] = useState('');
  const sections = [...new Set(def.fields.map((x) => x.section || 'Details'))];
  const save = () => {
    const miss = def.fields.filter((x) => x.req && (f[x.k] === undefined || f[x.k] === '') && (!x.show || x.show(f)));
    if (miss.length) return setErr(`Required: ${miss.map((m) => m.l).join(', ')}`);
    const rec = { ...f };
    def.fields.forEach((x) => { if (x.t === 'number' && rec[x.k] !== '' && rec[x.k] != null) rec[x.k] = Number(rec[x.k]); });
    A.save(def.coll, rec, def.singular);
    onClose();
  };
  return (
    <Drawer open onClose={onClose} title={init.id ? `Edit ${def.singular.toLowerCase()}` : `New ${def.singular.toLowerCase()}`} subtitle={`Legacy: ${def.legacy.join(', ')}`} footer={<><button className="btn-ghost" onClick={onClose}>Cancel</button><button className="btn-primary" onClick={save}>Save</button></>}>
      <div className="p-4 sm:p-5 grid gap-5">
        {err && <div className="bg-bad/10 text-bad rounded-lg px-3 py-2 text-[12.5px]">{err}</div>}
        {sections.map((s) => (
          <FormSection key={s} title={s} cols={2}>
            {def.fields.filter((x) => (x.section || 'Details') === s && (!x.show || x.show(f))).map((x) => {
              const v = f[x.k] ?? '';
              const on = (val: any) => setF({ ...f, [x.k]: val });
              const cls2 = x.span === 2 ? 'sm:col-span-2' : '';
              if (x.t === 'bool') return <div key={x.k} className={cls('flex items-end pb-1.5', cls2)}><Check label={x.l} checked={!!v} onChange={on} /></div>;
              return (
                <Field key={x.k} label={x.l} required={x.req} hint={x.hint} className={cls2}>
                  {x.t === 'select' ? <Select value={v} onChange={(e) => on(e.target.value)} placeholder="Select" options={opt(db, x.opts)} />
                    : x.t === 'radio' ? <Radio options={opt(db, x.opts) as string[]} value={v} onChange={on} />
                    : x.t === 'textarea' ? <Textarea rows={2} value={v} onChange={(e) => on(e.target.value)} />
                    : x.t === 'file' ? <label className="btn-ghost h-9 cursor-pointer w-full justify-start"><Upload size={14} /> {v || 'Choose file'}<input type="file" className="sr-only" onChange={(e) => on(e.target.files?.[0]?.name || '')} /></label>
                    : <Input type={x.t === 'number' ? 'number' : x.t === 'date' ? 'date' : x.t === 'email' ? 'email' : 'text'} value={v} onChange={(e) => on(e.target.value)} />}
                </Field>
              );
            })}
          </FormSection>
        ))}
      </div>
    </Drawer>
  );
}

// ---------------- Entity definitions (fields mirror the legacy *Detail.aspx forms) ----------------
export const DEFS: Record<string, EntityDef> = {
  company: { key: 'company', coll: 'companiesList', title: 'Company', singular: 'Company', group: 'Organisation', legacy: ['MasterPages/CompanyList', 'CompanyDetail'], desc: 'Legal entity details printed on LRs, bills and challans.', fields: [{ k: 'name', l: 'Company', req: true }, { k: 'address', l: 'Address', t: 'textarea', span: 2 }, { k: 'country', l: 'Country' }, { k: 'state', l: 'State', t: 'select', opts: stateOpts }, { k: 'city', l: 'City', t: 'select', opts: cityOpts }, { k: 'phone', l: 'Contact phone' }, { k: 'estd', l: 'Establishment year', t: 'number' }, { k: 'pan', l: 'Company PAN' }, { k: 'tan', l: 'Company TAN' }, { k: 'gst', l: 'GSTIN' }, { k: 'mainLogo', l: 'Main logo', t: 'file' }, { k: 'insideLogo', l: 'Inside logo', t: 'file' }], cols: (db) => [{ key: 'name', label: 'Company', mobile: 'title' }, { key: 'city', label: 'City', value: (r) => lookup.cityName(db, r.city) }, { key: 'state', label: 'State' }, { key: 'country', label: 'Country' }, { key: 'phone', label: 'Phone', mobile: 'sub' }] },
  branch: { key: 'branch', coll: 'branches', title: 'Branches', singular: 'Branch', group: 'Organisation', legacy: ['MasterPages/BranchList', 'BranchDetail'], desc: 'Booking branches and rail heads. Rail-head branches appear in VP scheduling; LR creation can be disabled per branch.', fields: [{ k: 'code', l: 'Branch code', req: true }, { k: 'short', l: 'Branch short code', req: true }, { k: 'name', l: 'Branch name', req: true }, { k: 'city', l: 'City', t: 'select', opts: cityOpts, req: true }, { k: 'address', l: 'Address', t: 'textarea', span: 2 }, { k: 'contact', l: 'Contact name' }, { k: 'phone', l: 'Contact phone' }, { k: 'email', l: 'Branch email', t: 'email' }, { k: 'godown', l: 'Godown', t: 'select', opts: (db) => db.godowns.map((g: any) => ({ value: g.id, label: g.name })) }, { k: 'weeklyOff', l: 'Weekly off day', t: 'select', opts: ['Sunday', 'Monday', 'Saturday'] }, { k: 'hours', l: 'Working hours' }, { k: 'receipt', l: 'Allow receipt', t: 'select', opts: ['Cash Receipts', 'Cheque Receipt'] }, { k: 'gst', l: 'GST no.' }, { k: 'allowLR', l: 'Allow LR create', t: 'bool' }, { k: 'isRailHead', l: 'Is rail head', t: 'bool' }], cols: (db) => [{ key: 'name', label: 'Branch', mobile: 'title' }, { key: 'short', label: 'Short code' }, { key: 'city', label: 'City', value: (r) => lookup.cityName(db, r.city), mobile: 'sub' }, { key: 'phone', label: 'Phone' }, { key: 'gst', label: 'GST no.', render: (r) => <span className="docno">{r.gst}</span> }, { key: 'isRailHead', label: 'Rail head', render: (r) => yes(r.isRailHead), mobile: 'meta' }, { key: 'allowLR', label: 'LR booking', render: (r) => yes(r.allowLR) }] },
  department: { key: 'department', coll: 'departments', title: 'Departments', singular: 'Department', group: 'Organisation', legacy: ['MasterPages/DepartmentList', 'DepartmentDetail'], desc: '', fields: [{ k: 'name', l: 'Department', req: true }, { k: 'branchId', l: 'Branch', t: 'select', opts: branchOpts }, { k: 'description', l: 'Description', t: 'textarea', span: 2 }], cols: (db) => [{ key: 'name', label: 'Department', mobile: 'title' }, { key: 'b', label: 'Branch', value: (r) => lookup.branch(db, r.branchId)?.name }, { key: 'description', label: 'Description' }, { key: 'emp', label: 'Employees', align: 'right', value: (r) => db.employees.filter((e: any) => e.departmentId === r.id).length }] },
  designation: { key: 'designation', coll: 'designations', title: 'Designations', singular: 'Designation', group: 'Organisation', legacy: ['MasterPages/DesignationList', 'DesignationDetail'], desc: 'Expense approval limits by designation.', fields: [{ k: 'name', l: 'Designation', req: true }, { k: 'seniorMgmt', l: 'Senior management position', t: 'bool' }, { k: 'powered', l: 'Powered designation', t: 'select', opts: (db) => db.designations.map((d: any) => d.name) }, { k: 'approvalLimit', l: 'Expense approval limit (₹)', t: 'number' }, { k: 'description', l: 'Description', t: 'textarea', span: 2 }], cols: () => [{ key: 'name', label: 'Designation', mobile: 'title' }, { key: 'seniorMgmt', label: 'Senior mgmt', render: (r) => yes(r.seniorMgmt) }, { key: 'approvalLimit', label: 'Approval limit', align: 'right', render: (r) => inr(r.approvalLimit), mobile: 'right' }, { key: 'powered', label: 'Powered designation' }] },
  employee: { key: 'employee', coll: 'employees', title: 'Employees', singular: 'Employee', group: 'Organisation', legacy: ['MasterPages/EmployeeList', 'EmployeeDetails'], desc: 'Staff records with department, designation and branch.', fields: [{ k: 'salutation', l: 'Salutation', t: 'select', opts: ['Mr.', 'Mrs.', 'Ms.'], section: 'Personal' }, { k: 'firstName', l: 'First name', req: true, section: 'Personal' }, { k: 'middleName', l: 'Middle name', section: 'Personal' }, { k: 'lastName', l: 'Last name', req: true, section: 'Personal' }, { k: 'gender', l: 'Gender', t: 'radio', opts: ['Male', 'Female'], section: 'Personal' }, { k: 'dob', l: 'Birth date', t: 'date', section: 'Personal' }, { k: 'maritalStatus', l: 'Marital status', t: 'select', opts: ['Married', 'Unmarried'], section: 'Personal' }, { k: 'bloodGroup', l: 'Blood group', t: 'select', opts: ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'], section: 'Personal' }, { k: 'photo', l: 'Photo', t: 'file', section: 'Personal' }, { k: 'mobile', l: 'Mobile', section: 'Contact' }, { k: 'landline', l: 'Landline', section: 'Contact' }, { k: 'personalEmail', l: 'Personal email', t: 'email', section: 'Contact' }, { k: 'workEmail', l: 'Work email', t: 'email', section: 'Contact' }, { k: 'address', l: 'Permanent address', t: 'textarea', span: 2, section: 'Contact' }, { k: 'city', l: 'City', t: 'select', opts: cityOpts, section: 'Contact' }, { k: 'pin', l: 'PIN', section: 'Contact' }, { k: 'payrollNo', l: 'Payroll no.', section: 'Employment' }, { k: 'designationId', l: 'Designation', t: 'select', opts: (db) => db.designations.map((d: any) => ({ value: d.id, label: d.name })), section: 'Employment' }, { k: 'departmentId', l: 'Department', t: 'select', opts: (db) => db.departments.map((d: any) => ({ value: d.id, label: d.name })), section: 'Employment' }, { k: 'branchId', l: 'Branch', t: 'select', opts: branchOpts, section: 'Employment' }, { k: 'joiningDate', l: 'Joining date', t: 'date', section: 'Employment' }, { k: 'totalExp', l: 'Total experience (yrs)', t: 'number', section: 'Employment' }, { k: 'prevEmployer', l: 'Previous employer', section: 'Employment' }, { k: 'promotion', l: 'Promotion record', section: 'Employment' }, { k: 'blacklisted', l: 'Blacklisted', t: 'select', opts: ['No', 'Yes'], section: 'Employment' }], cols: (db) => [{ key: 'name', label: 'Name', value: (r) => `${r.salutation} ${r.firstName} ${r.lastName}`, mobile: 'title' }, { key: 'payrollNo', label: 'Payroll' }, { key: 'dep', label: 'Department', value: (r) => db.departments.find((d: any) => d.id === r.departmentId)?.name, filter: true }, { key: 'des', label: 'Designation', value: (r) => db.designations.find((d: any) => d.id === r.designationId)?.name, mobile: 'sub' }, { key: 'b', label: 'Branch', value: (r) => lookup.branch(db, r.branchId)?.short, filter: true }, { key: 'mobile', label: 'Mobile' }, { key: 'workEmail', label: 'Work email' }] },
  country: { key: 'country', coll: 'countries', title: 'Countries', singular: 'Country', group: 'Geography', legacy: ['MasterPages/CountryList', 'CountryDetail'], desc: '', fields: [{ k: 'name', l: 'Country', req: true }, { k: 'description', l: 'Description' }, { k: 'lrBookingAllowed', l: 'LR booking allowed', t: 'bool' }], cols: () => [{ key: 'name', label: 'Country', mobile: 'title' }, { key: 'description', label: 'Description', mobile: 'sub' }, { key: 'lrBookingAllowed', label: 'LR booking', render: (r) => yes(r.lrBookingAllowed) }] },
  state: { key: 'state', coll: 'states', title: 'States', singular: 'State', group: 'Geography', legacy: ['MasterPages/StateList', 'StateDetail'], desc: 'Used for GST place of supply.', fields: [{ k: 'name', l: 'State', req: true }, { k: 'country', l: 'Country', t: 'select', opts: (db) => db.countries.map((c: any) => c.name) }, { k: 'description', l: 'Description' }], cols: () => [{ key: 'name', label: 'State', mobile: 'title' }, { key: 'country', label: 'Country' }, { key: 'description', label: 'Description' }] },
  city: { key: 'city', coll: 'cities', title: 'Cities', singular: 'City', group: 'Geography', legacy: ['MasterPages/CityList', 'CityDetail'], desc: 'Cities with coordinates drive distance-based freight suggestions and the control-tower map.', fields: [{ k: 'name', l: 'City', req: true }, { k: 'state', l: 'State', t: 'select', opts: stateOpts, req: true }, { k: 'lat', l: 'Latitude', t: 'number' }, { k: 'lng', l: 'Longitude', t: 'number' }, { k: 'description', l: 'Description', span: 2 }], cols: () => [{ key: 'name', label: 'City', mobile: 'title' }, { key: 'state', label: 'State', filter: true, mobile: 'sub' }, { key: 'country', label: 'Country', value: () => 'India' }, { key: 'll', label: 'Lat / Lng', value: (r) => (r.lat != null && r.lng != null ? `${r.lat}, ${r.lng}` : '—') }] },
  goods: { key: 'goods', coll: 'goods', title: 'Goods', singular: 'Goods', group: 'Logistics', legacy: ['MasterPages/GoodsList', 'GoodsDetail'], desc: 'Dimensions, weight, orientation and stacking rules feed VP load optimisation.', fields: [{ k: 'name', l: 'Goods name', req: true }, { k: 'description', l: 'Description' }, { k: 'weight', l: 'Weight (kg)', t: 'number', req: true }, { k: 'unit', l: 'Unit', t: 'select', opts: (db) => db.units.map((u: any) => ({ value: u.id, label: u.name })) }, { k: 'length', l: 'Length (cm)', t: 'number' }, { k: 'width', l: 'Width (cm)', t: 'number' }, { k: 'height', l: 'Height (cm)', t: 'number' }, { k: 'category', l: 'Category', t: 'select', opts: ['Consumer Durable', 'Electronics', 'Lifestyle', 'Building Material', 'Perishable', 'Agri', 'FMCG', 'Steel'] }, { k: 'storagePosition', l: 'Storage position', t: 'select', opts: ['Upright', 'Flat', 'Any'] }, { k: 'layer', l: 'Storage layers', t: 'number' }, { k: 'stacking', l: 'Stacking allowed', t: 'bool' }], cols: (db) => [{ key: 'name', label: 'Name', mobile: 'title' }, { key: 'category', label: 'Category', filter: true, mobile: 'sub' }, { key: 'weight', label: 'Weight kg', align: 'right' }, { key: 'length', label: 'Length', align: 'right' }, { key: 'width', label: 'Width', align: 'right' }, { key: 'height', label: 'Height', align: 'right' }, { key: 'storagePosition', label: 'Position' }, { key: 'stacking', label: 'Stacking', render: (r) => yes(r.stacking) }] },
  unit: { key: 'unit', coll: 'units', title: 'Units', singular: 'Unit', group: 'Logistics', legacy: ['MasterPages/UnitList', 'UnitDetail'], desc: 'Billing units; slab units enable range-based rate matrices.', fields: [{ k: 'name', l: 'Unit', req: true }, { k: 'description', l: 'Description' }, { k: 'slab', l: 'Is slab rate', t: 'bool' }], cols: () => [{ key: 'name', label: 'Unit', mobile: 'title' }, { key: 'description', label: 'Description', mobile: 'sub' }, { key: 'slab', label: 'Slab rate', render: (r) => yes(r.slab) }] },
  container: { key: 'container', coll: 'containers', title: 'Containers', singular: 'Container', group: 'Logistics', legacy: ['LGST_Container'], desc: '', fields: [{ k: 'name', l: 'Container', req: true }, { k: 'description', l: 'Description' }, { k: 'length', l: 'Length (cm)', t: 'number' }, { k: 'width', l: 'Width (cm)', t: 'number' }, { k: 'height', l: 'Height (cm)', t: 'number' }, { k: 'weight', l: 'Tare weight (kg)', t: 'number' }], cols: () => [{ key: 'name', label: 'Container', mobile: 'title' }, { key: 'description', label: 'Description' }, { key: 'length', label: 'L', align: 'right' }, { key: 'width', label: 'W', align: 'right' }, { key: 'height', label: 'H', align: 'right' }, { key: 'weight', label: 'Weight', align: 'right' }] },
  wagon: { key: 'wagon', coll: 'wagons', title: 'Wagons', singular: 'Wagon', group: 'Logistics', eyebrow: 'Rail & Rake', legacy: ['MasterPages/WagonList', 'WagonDetail'], desc: 'Wagon types available for VP schedules, with internal dimensions and payload for load planning.', fields: [{ k: 'name', l: 'Wagon', req: true }, { k: 'type', l: 'Wagon type', t: 'select', opts: ['Parcel Van', 'High Capacity Parcel Van', 'Covered Wagon', 'Covered Wagon HL', 'Auto Carrier'] }, { k: 'description', l: 'Description', span: 2 }, { k: 'width', l: 'Width (cm)', t: 'number' }, { k: 'height', l: 'Height (cm)', t: 'number' }, { k: 'length', l: 'Length (cm)', t: 'number' }, { k: 'weight', l: 'Payload (kg)', t: 'number' }], cols: () => [{ key: 'name', label: 'Wagon', mobile: 'title' }, { key: 'type', label: 'Type', mobile: 'sub' }, { key: 'description', label: 'Description' }, { key: 'height', label: 'Height', align: 'right' }, { key: 'width', label: 'Width', align: 'right' }, { key: 'length', label: 'Length', align: 'right' }, { key: 'weight', label: 'Payload kg', align: 'right', render: (r) => num(r.weight) }] },
  railfreight: { key: 'railfreight', coll: 'railFreight', title: 'Railway freight matrix', singular: 'Railway freight', group: 'Logistics', eyebrow: 'Rail & Rake', legacy: ['MasterPages/RailwayFreight'], desc: 'Per-wagon railway freight by route; pre-fills MR/RR and drives rake profitability.', fields: [{ k: 'wagonId', l: 'Wagon type', t: 'select', opts: (db) => db.wagons.map((w: any) => ({ value: w.id, label: w.name })), req: true }, { k: 'source', l: 'Source', t: 'select', opts: cityOpts, req: true }, { k: 'dest', l: 'Destination', t: 'select', opts: cityOpts, req: true }, { k: 'rate', l: 'Amount (₹)', t: 'number', req: true }], cols: (db) => [{ key: 'src', label: 'Source', value: (r) => lookup.cityName(db, r.source), mobile: 'title' }, { key: 'dst', label: 'Destination', value: (r) => lookup.cityName(db, r.dest), mobile: 'sub' }, { key: 'w', label: 'Wagon type', value: (r) => lookup.wagon(db, r.wagonId), filter: true }, { key: 'rate', label: 'Rate', align: 'right', render: (r) => inr(r.rate), mobile: 'right' }] },
  godown: { key: 'godown', coll: 'godowns', title: 'Godowns', singular: 'Godown', group: 'Logistics', eyebrow: 'Warehouse', legacy: ['MasterPages/GodownList', 'GodownDetail'], desc: 'Owned and leased warehouses with capacity, gates, rent and agreement expiry.', fields: [{ k: 'name', l: 'Godown', req: true }, { k: 'type', l: 'Godown type', t: 'select', opts: ['Owned', 'Leased', 'Rail siding'] }, { k: 'address', l: 'Address', t: 'textarea', span: 2 }, { k: 'city', l: 'City', t: 'select', opts: cityOpts }, { k: 'branchId', l: 'Branch', t: 'select', opts: branchOpts }, { k: 'contact', l: 'Contact name' }, { k: 'phone', l: 'Contact phone' }, { k: 'rent', l: 'Monthly rent (₹)', t: 'number', section: 'Agreement' }, { k: 'deposit', l: 'Security deposit (₹)', t: 'number', section: 'Agreement' }, { k: 'agreementDate', l: 'Agreement date', t: 'date', section: 'Agreement' }, { k: 'expiry', l: 'Expiry date', t: 'date', section: 'Agreement' }, { k: 'length', l: 'Length (ft)', t: 'number', section: 'Capacity' }, { k: 'breadth', l: 'Breadth (ft)', t: 'number', section: 'Capacity' }, { k: 'width', l: 'Width (ft)', t: 'number', section: 'Capacity' }, { k: 'capacity', l: 'Storage capacity (MT)', t: 'number', section: 'Capacity' }, { k: 'gateNo', l: 'No. of gates', t: 'number', section: 'Capacity' }], cols: (db) => [{ key: 'name', label: 'Godown', mobile: 'title' }, { key: 'type', label: 'Type', filter: true }, { key: 'city', label: 'City', value: (r) => lookup.cityName(db, r.city), mobile: 'sub' }, { key: 'branchId', label: 'Branch' }, { key: 'capacity', label: 'Capacity MT', align: 'right' }, { key: 'gateNo', label: 'Gates', align: 'right' }, { key: 'rent', label: 'Rent', align: 'right', render: (r) => inr(r.rent) }, { key: 'expiry', label: 'Agreement expiry', render: (r) => fmtDate(r.expiry) }, { key: 'phone', label: 'Phone', hidden: true }] },
  hamali: { key: 'hamali', coll: 'hamaliRates', title: 'Hamali rates', singular: 'Hamali rate', group: 'Logistics', eyebrow: 'Customers', legacy: ['MasterPages/HamaliList', 'HamaliDetail'], desc: 'Loading/unloading labour rates per goods, client and branch – pre-fills labour charges on GRN, VP loading and DGRN.', fields: [{ k: 'goodsId', l: 'Goods', t: 'select', opts: (db) => db.goods.map((g: any) => ({ value: g.id, label: g.name })), req: true }, { k: 'clientId', l: 'Client', t: 'select', opts: (db) => db.customers.map((c: any) => ({ value: c.id, label: c.name })) }, { k: 'branchId', l: 'Branch', t: 'select', opts: branchOpts }, { k: 'unitId', l: 'Unit', t: 'select', opts: (db) => db.units.map((u: any) => ({ value: u.id, label: u.name })) }, { k: 'rate', l: 'Rate (₹)', t: 'number', req: true }, { k: 'use', l: 'Hamali use', t: 'select', opts: ['GRN Station', 'Branch GRN', 'VP Loading'] }], cols: (db) => [{ key: 'g', label: 'Goods', value: (r) => lookup.goods(db, r.goodsId)?.name, mobile: 'title' }, { key: 'c', label: 'Customer', value: (r) => lookup.custName(db, r.clientId), filter: true, mobile: 'sub' }, { key: 'b', label: 'Branch', value: (r) => lookup.branch(db, r.branchId)?.name, filter: true }, { key: 'u', label: 'Unit', value: (r) => db.units.find((u: any) => u.id === r.unitId)?.name }, { key: 'use', label: 'Use', filter: true }, { key: 'rate', label: 'Rate', align: 'right', render: (r) => inr(r.rate, 2), mobile: 'right' }] },
  transporter: { key: 'transporter', coll: 'transporters', title: 'Transporters', singular: 'Transporter', group: 'Parties', legacy: ['MasterPages/TransportList', 'TransportDetail'], desc: 'Market fleet owners and brokers. TDS rate, PAN declaration and payable split are used on payment slips.', fields: [{ k: 'name', l: 'Transporter', req: true }, { k: 'address', l: 'Address', t: 'textarea', span: 2 }, { k: 'city', l: 'City', t: 'select', opts: cityOpts }, { k: 'contact', l: 'Contact name' }, { k: 'phone', l: 'Contact phone' }, { k: 'mobile', l: 'Primary mobile' }, { k: 'mobile2', l: 'Secondary mobile' }, { k: 'locations', l: 'Available locations', span: 2 }, { k: 'pan', l: 'PAN', section: 'Tax & payment' }, { k: 'stNo', l: 'GST / service tax no.', section: 'Tax & payment' }, { k: 'tdsRate', l: 'TDS rate (%)', t: 'number', section: 'Tax & payment' }, { k: 'noTdsAmt', l: 'No-TDS up to (₹)', t: 'number', section: 'Tax & payment' }, { k: 'paymentMode', l: 'Payment mode', t: 'select', opts: ['Cash', 'Cheque', 'Bank'], section: 'Tax & payment' }, { k: 'payable1', l: 'Payable 1 (%)', t: 'number', section: 'Tax & payment' }, { k: 'payable2', l: 'Payable 2 (%)', t: 'number', section: 'Tax & payment' }, { k: 'payable3', l: 'Payable 3 (%)', t: 'number', section: 'Tax & payment' }, { k: 'payable4', l: 'Payable 4 (%)', t: 'number', section: 'Tax & payment' }, { k: 'declaration', l: 'PAN declaration on file', t: 'bool', section: 'Tax & payment' }, { k: 'blacklisted', l: 'Blacklisted', t: 'bool', section: 'Tax & payment' }, { k: 'associate', l: 'Associate transporter', t: 'bool', section: 'Tax & payment' }], cols: (db) => [{ key: 'name', label: 'Transporter', mobile: 'title' }, { key: 'city', label: 'City', value: (r) => lookup.cityName(db, r.city), filter: true, mobile: 'sub' }, { key: 'mobile', label: 'Phone' }, { key: 'pan', label: 'PAN', render: (r) => <span className="docno">{r.pan}</span> }, { key: 'tdsRate', label: 'TDS %', align: 'right' }, { key: 'trucks', label: 'Trucks', align: 'right', value: (r) => db.trucks.filter((t: any) => t.transporterId === r.id).length }, { key: 'st', label: 'Status', value: (r) => (r.blacklisted ? 'Blacklisted' : r.associate ? 'Associate' : 'Active'), render: (r) => <StatusBadge s={r.blacklisted ? 'Blacklisted' : r.associate ? 'Associate' : 'Active'} tone={r.blacklisted ? 'bad' : r.associate ? 'violet' : 'ok'} />, filter: true, mobile: 'meta' }] },
  labour: { key: 'labour', coll: 'labours', title: 'Labour, supervisors & mechanics', singular: 'Labour', group: 'Parties', legacy: ['MasterPages/LabourList', 'LabourDetail'], desc: 'Hamals (loading gangs), supervisors and workshop mechanics by branch.', quick: [{ key: 's', label: 'Supervisors', fn: (r) => r.type === 'Supervisor' }, { key: 'h', label: 'Hamals', fn: (r) => r.type === 'Hamal' }, { key: 'm', label: 'Mechanics', fn: (r) => r.type === 'Mechanic' }], fields: [{ k: 'type', l: 'Type', t: 'radio', opts: ['Supervisor', 'Hamal', 'Mechanic'], req: true, span: 2 }, { k: 'name', l: 'Labour name', req: true }, { k: 'branchId', l: 'Branch', t: 'select', opts: branchOpts }, { k: 'address', l: 'Address', span: 2 }, { k: 'city', l: 'City', t: 'select', opts: cityOpts }, { k: 'contact', l: 'Contact name' }, { k: 'phone', l: 'Contact phone' }, { k: 'mobile', l: 'Mobile' }, { k: 'refName', l: 'Reference person' }, { k: 'refContact', l: 'Reference contact' }, { k: 'startDate', l: 'Start date', t: 'date' }, { k: 'photo', l: 'Photo', t: 'file' }, { k: 'pan', l: 'PAN', section: 'TDS' }, { k: 'tdsRate', l: 'TDS rate (%)', t: 'number', section: 'TDS' }, { k: 'noTdsAmt', l: 'No-TDS up to (₹) (not to apply)', t: 'number', section: 'TDS' }], cols: (db) => [{ key: 'name', label: 'Name', mobile: 'title' }, { key: 'type', label: 'Type', filter: true, render: (r) => <StatusBadge s={r.type} tone={r.type === 'Supervisor' ? 'violet' : r.type === 'Hamal' ? 'info' : 'warn'} dot={false} />, mobile: 'meta' }, { key: 'branchId', label: 'Branch', filter: true }, { key: 'contact', label: 'Contact person', mobile: 'sub' }, { key: 'mobile', label: 'Phone' }, { key: 'startDate', label: 'Start date', render: (r) => fmtDate(r.startDate) }, { key: 'pan', label: 'PAN' }] },
  pump: { key: 'pump', coll: 'pumps', title: 'Diesel pumps', singular: 'Pump', group: 'Parties', eyebrow: 'Road Fleet', legacy: ['MasterPages/PumpList', 'PumpDetail'], desc: 'Credit fuel stations with current diesel rate and rate history.', fields: [{ k: 'name', l: 'Pump', req: true }, { k: 'address', l: 'Address', span: 2 }, { k: 'city', l: 'City', t: 'select', opts: cityOpts }, { k: 'contact', l: 'Contact name' }, { k: 'phone', l: 'Contact phone' }, { k: 'dieselRate', l: 'Current diesel rate (₹/L)', t: 'number', req: true }, { k: 'rateUpdated', l: 'Rate last updated', t: 'date' }, { k: 'vat', l: 'VAT / TIN' }, { k: 'pan', l: 'Pump PAN' }, { k: 'creditLimit', l: 'Credit limit (₹)', t: 'number' }, { k: 'bank', l: 'Bank name', section: 'Bank' }, { k: 'account', l: 'Account name', section: 'Bank' }, { k: 'ifsc', l: 'Branch IFSC code', section: 'Bank' }, { k: 'blacklisted', l: 'Blacklisted', t: 'bool', section: 'Bank' }], cols: (db) => [{ key: 'name', label: 'Pump', mobile: 'title' }, { key: 'city', label: 'City', value: (r) => lookup.cityName(db, r.city), mobile: 'sub' }, { key: 'phone', label: 'Phone' }, { key: 'dieselRate', label: 'Diesel ₹/L', align: 'right', render: (r) => r.dieselRate.toFixed(2), mobile: 'right' }, { key: 'creditLimit', label: 'Credit limit', align: 'right', render: (r) => inr(r.creditLimit) }, { key: 'spend', label: 'Spend (all)', align: 'right', value: (r) => db.tripExpenses.filter((e: any) => e.pumpId === r.id).reduce((a: number, e: any) => a + e.amount, 0), render: (r) => inr(db.tripExpenses.filter((e: any) => e.pumpId === r.id).reduce((a: number, e: any) => a + e.amount, 0)) }] },
  ledger: { key: 'ledger', coll: 'ledgers', title: 'Bank & card ledgers', singular: 'Ledger', group: 'Finance', legacy: ['MasterPages/LedgerList', 'LedgerDetail'], desc: 'Bank accounts and fleet fuel cards used as “paid by” on payments and expenses.', fields: [{ k: 'name', l: 'Ledger name', req: true }, { k: 'type', l: 'Ledger type', t: 'radio', opts: ['Bank', 'Card'], req: true }, { k: 'branches', l: 'Branches' }], cols: () => [{ key: 'name', label: 'Ledger name', mobile: 'title' }, { key: 'type', label: 'Type', filter: true, render: (r) => <StatusBadge s={r.type} tone={r.type === 'Bank' ? 'info' : 'violet'} dot={false} />, mobile: 'meta' }, { key: 'branches', label: 'Branches', mobile: 'sub' }] },
  expensetype: { key: 'expensetype', coll: 'expenseTypes', title: 'Expense types', singular: 'Expense type', group: 'Finance', legacy: ['MasterPages/ExpenseTypeList', 'ExpenseTypeDetail'], desc: 'Trip and vehicle expense heads with four approval limits and Tally ledger mapping.', fields: [{ k: 'name', l: 'Expense name', req: true }, { k: 'ledger', l: 'Ledger name (Tally)' }, { k: 'l1', l: 'Expense limit 1', t: 'number' }, { k: 'l2', l: 'Expense limit 2', t: 'number' }, { k: 'l3', l: 'Expense limit 3', t: 'number' }, { k: 'l4', l: 'Expense limit 4', t: 'number' }, { k: 'mode', l: 'Expense mode', t: 'select', opts: ['Cash', 'Card', 'Bank'] }, { k: 'applicableFor', l: 'Applicable for', t: 'select', opts: ['All', 'Own Vehicle', 'Market Vehicle'] }], cols: () => [{ key: 'name', label: 'Expense name', mobile: 'title' }, { key: 'ledger', label: 'Ledger', mobile: 'sub' }, { key: 'l1', label: 'Limit 1', align: 'right', render: (r) => inr(r.l1) }, { key: 'l2', label: 'Limit 2', align: 'right', render: (r) => inr(r.l2) }, { key: 'l3', label: 'Limit 3', align: 'right', render: (r) => inr(r.l3) }, { key: 'l4', label: 'Limit 4', align: 'right', render: (r) => inr(r.l4) }, { key: 'mode', label: 'Mode' }] },
  document: { key: 'document', coll: 'documents', title: 'Documents', singular: 'Document', group: 'Finance', eyebrow: 'Customers', legacy: ['MasterPages/DocumentList', 'DocumentDetail'], desc: 'Company certificates, licences, policies and templates shared with customers.', fields: [{ k: 'name', l: 'Document', req: true }, { k: 'type', l: 'Document type', t: 'select', opts: ['Certificate', 'Statutory', 'Licence', 'Insurance', 'Commercial', 'Contract', 'HR Policy'] }, { k: 'path', l: 'Document file', t: 'file' }, { k: 'remarks', l: 'Remarks', t: 'textarea', span: 2 }], cols: () => [{ key: 'name', label: 'Document', mobile: 'title' }, { key: 'type', label: 'Type', filter: true, mobile: 'meta' }, { key: 'path', label: 'File', render: (r) => <span className="docno text-muted">{r.path}</span>, mobile: 'sub' }, { key: 'updated', label: 'Updated', render: (r) => fmtDate(r.updated) }] },
  agreement: { key: 'agreement', coll: 'agreements', title: 'Agreements', singular: 'Agreement', group: 'Finance', eyebrow: 'Customers', legacy: ['MasterPages/AgreementList', 'AgreementDetail'], desc: 'Client agreements with committed trips, detention rate and carrying capacity.', fields: [{ k: 'clientId', l: 'Client', t: 'select', opts: (db) => db.customers.map((c: any) => ({ value: c.id, label: c.name })), req: true }, { k: 'city', l: 'City', t: 'select', opts: cityOpts }, { k: 'agreementDate', l: 'Agreement date', t: 'date' }, { k: 'start', l: 'Start date', t: 'date', req: true }, { k: 'expiry', l: 'Expiry date', t: 'date', req: true }, { k: 'rateType', l: 'Rate type', t: 'select', opts: ['Per Truck', 'Per MT', 'Per Carton', 'Per KM'] }, { k: 'rate', l: 'Rate (₹)', t: 'number' }, { k: 'rateInclTax', l: 'Rate inclusive of tax', t: 'bool' }, { k: 'detentionRate', l: 'Detention rate (₹/day)', t: 'number' }, { k: 'branchId', l: 'Lead generated by branch', t: 'select', opts: branchOpts }, { k: 'committedTrips', l: 'Committed trips', t: 'number' }, { k: 'applyRateIfNotAchieved', l: 'Apply rate if committed business not achieved', t: 'bool' }, { k: 'carryingCapacity', l: 'Carrying capacity' }, { k: 'approvedBy', l: 'Approved by' }], cols: (db) => [{ key: 'c', label: 'Client', value: (r) => lookup.custName(db, r.clientId), mobile: 'title' }, { key: 'rateType', label: 'Rate type', filter: true }, { key: 'rate', label: 'Rate', align: 'right', render: (r) => inr(r.rate), mobile: 'right' }, { key: 'agreementDate', label: 'Agreement date', render: (r) => fmtDate(r.agreementDate) }, { key: 'start', label: 'Start', render: (r) => fmtDate(r.start) }, { key: 'expiry', label: 'Expiry', render: (r) => <span className={cls(r.expiry < ymd() && 'text-bad')}>{fmtDate(r.expiry)}</span>, mobile: 'sub' }, { key: 'committedTrips', label: 'Committed trips', align: 'right' }] },
  transrate: { key: 'transrate', coll: 'transRates', title: 'Transporter rate matrix', singular: 'Transporter rate', group: 'Finance', eyebrow: 'Customers', legacy: ['MasterPages/TransporterRateMatrix'], desc: 'Market and union truck freight by lane; suggests lorry hire on LRs and delivery challans.', fields: [{ k: 'source', l: 'Source', t: 'select', opts: cityOpts, req: true }, { k: 'dest', l: 'Destination', t: 'select', opts: cityOpts, req: true }, { k: 'truckType', l: 'Truck type', t: 'radio', opts: ['Market', 'Union'] }, { k: 'rate', l: 'Amount (₹)', t: 'number', req: true }], cols: (db) => [{ key: 's', label: 'Source', value: (r) => lookup.cityName(db, r.source), filter: true, mobile: 'title' }, { key: 'd', label: 'Destination', value: (r) => lookup.cityName(db, r.dest), mobile: 'sub' }, { key: 'truckType', label: 'Truck type', filter: true }, { key: 'rate', label: 'Rate', align: 'right', render: (r) => inr(r.rate), mobile: 'right' }] },
};
DEFS.company.coll = 'companiesList';

export const MASTER_GROUPS: { title: string; icon: any; items: { key: string; label: string; route?: string; count: (db: any) => number }[] }[] = [
  { title: 'Organisation', icon: Building2, items: [{ key: 'company', label: 'Company', count: () => 1 }, { key: 'branch', label: 'Branches', count: (db) => db.branches.length }, { key: 'department', label: 'Departments', count: (db) => db.departments.length }, { key: 'designation', label: 'Designations', count: (db) => db.designations.length }, { key: 'employee', label: 'Employees', count: (db) => db.employees.length }] },
  { title: 'Geography', icon: MapPin, items: [{ key: 'country', label: 'Countries', count: (db) => db.countries.length }, { key: 'state', label: 'States', count: (db) => db.states.length }, { key: 'city', label: 'Cities', count: (db) => db.cities.length }] },
  { title: 'Goods & equipment', icon: Package, items: [{ key: 'goods', label: 'Goods', count: (db) => db.goods.length }, { key: 'unit', label: 'Units', count: (db) => db.units.length }, { key: 'container', label: 'Containers', count: (db) => db.containers.length }, { key: 'wagon', label: 'Wagons', route: 'rail/wagons', count: (db) => db.wagons.length }, { key: 'godown', label: 'Godowns', route: 'wh/godowns', count: (db) => db.godowns.length }, { key: 'truck', label: 'Trucks', route: 'fleet/trucks', count: (db) => db.trucks.length }] },
  { title: 'Parties', icon: Users, items: [{ key: 'customer', label: 'Customers', route: 'cust/360', count: (db) => db.customers.length }, { key: 'transporter', label: 'Transporters', count: (db) => db.transporters.length }, { key: 'driver', label: 'Drivers', route: 'fleet/drivers', count: (db) => db.drivers.length }, { key: 'labour', label: 'Labour / supervisors / mechanics', count: (db) => db.labours.length }, { key: 'pump', label: 'Diesel pumps', count: (db) => db.pumps.length }, { key: 'supplier', label: 'Suppliers', route: 'ws/suppliers', count: (db) => db.suppliers.length }] },
  { title: 'Rates & finance', icon: Landmark, items: [{ key: 'ledger', label: 'Bank / card ledgers', count: (db) => db.ledgers.length }, { key: 'expensetype', label: 'Expense types', count: (db) => db.expenseTypes.length }, { key: 'railfreight', label: 'Railway freight', route: 'rail/freight', count: (db) => db.railFreight.length }, { key: 'transrate', label: 'Transporter rates', route: 'cust/transporter-rates', count: (db) => db.transRates.length }, { key: 'hamali', label: 'Hamali rates', route: 'cust/hamali-rates', count: (db) => db.hamaliRates.length }, { key: 'ratecontract', label: 'Rate contracts', route: 'cust/rate-contracts', count: (db) => db.rateContracts.length }] },
  { title: 'Documents & access', icon: FileText, items: [{ key: 'document', label: 'Documents', route: 'cust/documents', count: (db) => db.documents.length }, { key: 'agreement', label: 'Agreements', route: 'cust/agreements', count: (db) => db.agreements.length }, { key: 'users', label: 'Users', route: 'access/users', count: (db) => db.users.length }, { key: 'roles', label: 'Roles', route: 'access/roles', count: (db) => db.roles.length }] },
];

export function MastersHub() {
  const db = useDB();
  const route = useUI((s) => s.route);
  const nav = useUI((s) => s.nav);
  const [q, setQ] = useState('');
  const key = route.split('/')[1];
  if (key && DEFS[key]) return <CrudPage def={key === 'company' ? { ...DEFS.company, coll: 'companiesList' } : DEFS[key]} />;
  return (
    <div>
      <PageHeader eyebrow="Configuration" title="Masters" subtitle="Reference data used across operations, fleet, finance and workshop. Every legacy MasterPages screen is available here." actions={<div className="relative w-full sm:w-64"><Search size={14} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-faint" /><input className="input pl-8" placeholder="Find a master…" value={q} onChange={(e) => setQ(e.target.value)} /></div>} />
      <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">
        {MASTER_GROUPS.map((g) => { const I = g.icon; const items = g.items.filter((i) => i.label.toLowerCase().includes(q.toLowerCase())); if (!items.length) return null; return (
          <Card key={g.title} title={g.title} icon={I} pad={false}>
            <ul className="divide-y divide-line">{items.map((i) => <li key={i.key}><button onClick={() => nav(i.route || `masters/${i.key}`)} className="w-full flex items-center gap-3 px-4 py-2.5 hover:bg-surface2 text-left"><span className="flex-1 text-[13px] font-medium">{i.label}</span><span className="text-[12px] text-muted tnum">{i.count(db)}</span><ArrowRight size={14} className="text-faint" /></button></li>)}</ul>
          </Card>); })}
      </div>
    </div>
  );
}
