import React, { useEffect, useMemo, useState } from 'react';
import { useDB, useUI, A, lookup, stockQty, truckStatus, defLedger } from '../store/store';
import { PageHeader, KPI, StatusBadge, Field, Input, Select, Textarea, Radio, FormSection, DocNo, Card, Check, Stat, EmptyState, Tabs, Progress, Segmented } from '../components/ui';
import { DataTable } from '../components/DataTable';
import { Drawer, Modal } from '../components/overlays';
import { CrudPage, EntityDef } from './masters';
import { ChartCard, Bars } from '../components/charts';
import { fmtDate, ymd, hm, sum, inr, num, cls, daysBetween, groupBy } from '../lib/util';
import { Plus, Printer, Eye, Pencil, Trash2, Wrench, BadgeCheck, Package, ShoppingCart, ArrowDownToLine, Repeat, Receipt, Banknote, ListChecks, AlertTriangle, CheckCircle2, Send, Undo2 } from 'lucide-react';

const mechOpts = (db: any) => db.labours.filter((l: any) => l.type === 'Mechanic').map((l: any) => ({ value: l.id, label: l.name }));

// ---------------- Truck checklist ----------------
export function TruckChecklist() {
  const db = useDB();
  const { openPrint } = useUI.getState();
  const blank = () => ({ truckId: '', driverId: '', openingKm: '', date: ymd(), jobCardNo: '', items: db.checklistParticulars.map((p: string) => ({ particular: p, ok: true, status: 'OK', action: '', remark: '' })), preparedBy: '', checkedBy: '', authorisedBy: '' });
  const [f, setF] = useState<any>(null);
  const issues = f ? f.items.filter((i: any) => !i.ok).length : 0;
  return (
    <div>
      <PageHeader eyebrow="Workshop & Inventory" title="Truck maintenance checklist" subtitle="20-point pre-trip / periodic inspection. Failed points can be turned straight into a job card." actions={<button className="btn-primary" onClick={() => setF(blank())}><Plus size={15} /> New checklist</button>} />
      <DataTable id="checklists" rows={db.checklists.slice().reverse()} onRow={(r) => setF(structuredClone(r))} cols={[{ key: 'no', label: 'Checklist', render: (r) => <DocNo>{r.no}</DocNo>, mobile: 'title' }, { key: 'truck', label: 'Truck no.', value: (r) => lookup.truckNo(db, r.truckId), mobile: 'sub' }, { key: 'jobCardNo', label: 'Job card no.' }, { key: 'driver', label: 'Driver name', value: (r) => lookup.driverName(db, r.driverId) }, { key: 'openingKm', label: 'Opening km', align: 'right', render: (r) => num(r.openingKm) }, { key: 'date', label: 'Date', render: (r) => fmtDate(r.date) }, { key: 'issues', label: 'Issues', value: (r) => r.items.filter((i: any) => !i.ok).length, render: (r) => { const n = r.items.filter((i: any) => !i.ok).length; return n ? <StatusBadge s={`${n} issues`} tone="warn" /> : <StatusBadge s="All OK" tone="ok" />; }, mobile: 'meta' }]} rowActions={(r: any) => [{ label: 'Print', icon: Printer, onClick: () => openPrint('maintenance', r.id) }, { label: 'Edit', icon: Pencil, onClick: () => setF(structuredClone(r)) }, { label: 'Delete', icon: Trash2, tone: 'bad', onClick: () => A.remove('checklists', r.id, 'Checklist') }]} />
      {f && <Drawer open onClose={() => setF(null)} title={f.no ? `Checklist ${f.no}` : 'Truck maintenance checklist'} subtitle="Legacy: Inventory/TruckCheckList.aspx" width="max-w-4xl" footer={<>{issues > 0 && <button className="btn-ghost" onClick={() => { setF(null); useUI.getState().nav('ws/jobcards', { new: 1, truckId: f.truckId }); }}><Wrench size={14} /> Create job card</button>}<button className="btn-ghost" onClick={() => setF(null)}>Cancel</button><button className="btn-primary" onClick={() => { if (!f.truckId) return useUI.getState().toast('Select truck', 'bad'); A.saveChecklist({ ...f, openingKm: Number(f.openingKm) }); setF(null); }}>Save checklist</button></>}>
        <div className="p-4 sm:p-5 grid gap-5">
          <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">
            <Field label="Truck no." required><Select value={f.truckId} onChange={(e) => { const t = lookup.truck(db, e.target.value); setF({ ...f, truckId: e.target.value, driverId: t?.driverId, openingKm: t?.odometer }); }} placeholder="Select" options={db.trucks.filter((t: any) => t.type === 'Own').map((t: any) => ({ value: t.id, label: t.number }))} /></Field>
            <Field label="Driver"><Select value={f.driverId} onChange={(e) => setF({ ...f, driverId: e.target.value })} options={db.drivers.map((d: any) => ({ value: d.id, label: d.name }))} placeholder="Select" /></Field>
            <Field label="Opening KM"><Input type="number" value={f.openingKm} onChange={(e) => setF({ ...f, openingKm: e.target.value })} /></Field>
            <Field label="Date"><Input type="date" value={f.date} onChange={(e) => setF({ ...f, date: e.target.value })} /></Field>
            <Field label="Job card no."><Input value={f.jobCardNo} onChange={(e) => setF({ ...f, jobCardNo: e.target.value })} /></Field>
          </div>
          <div className="border border-line rounded-lg overflow-x-auto"><table className="w-full text-[12.5px] min-w-[700px]"><thead className="bg-surface2"><tr className="text-[10.5px] text-muted uppercase"><th className="text-left px-3 py-2">Check point</th><th className="px-2 w-12">OK</th><th className="px-2">Status</th><th className="px-2">Action</th><th className="px-3">Remark</th></tr></thead>
            <tbody>{f.items.map((it: any, k: number) => { const up = (p: any) => setF({ ...f, items: f.items.map((x: any, j: number) => (j === k ? { ...x, ...p } : x)) }); return <tr key={k} className={cls('border-t border-line', !it.ok && 'bg-warn/[.06]')}><td className="px-3 py-1.5 font-medium">{it.particular}</td><td className="px-2 text-center"><input type="checkbox" aria-label="OK" checked={it.ok} onChange={(e) => up({ ok: e.target.checked, status: e.target.checked ? 'OK' : '' })} /></td><td className="px-2"><input className="input h-7" aria-label="Status" value={it.status} onChange={(e) => up({ status: e.target.value })} /></td><td className="px-2"><select className="input h-7" aria-label="Action" value={it.action} onChange={(e) => up({ action: e.target.value })}><option value="">—</option>{['Replace', 'Repair', 'Top-up', 'Tighten', 'Adjust', 'Clean'].map((a) => <option key={a}>{a}</option>)}</select></td><td className="px-3"><input className="input h-7" aria-label="Remark" value={it.remark} onChange={(e) => up({ remark: e.target.value })} /></td></tr>; })}</tbody></table></div>
          <div className="grid sm:grid-cols-3 gap-3"><Field label="Prepared by"><Input value={f.preparedBy} onChange={(e) => setF({ ...f, preparedBy: e.target.value })} /></Field><Field label="Checked by"><Input value={f.checkedBy} onChange={(e) => setF({ ...f, checkedBy: e.target.value })} /></Field><Field label="Authorised by"><Input value={f.authorisedBy} onChange={(e) => setF({ ...f, authorisedBy: e.target.value })} /></Field></div>
          {issues > 0 && <div className="rounded-lg bg-warn/10 text-warn px-3 py-2 text-[12.5px] flex gap-2"><AlertTriangle size={15} />{issues} check points need attention.</div>}
        </div>
      </Drawer>}
    </div>
  );
}

// ---------------- Job cards ----------------
export function JobCards() {
  const db = useDB();
  const params = useUI((s) => s.params);
  const { openRecord, openPrint } = useUI.getState();
  const [form, setForm] = useState<any>(null);
  useEffect(() => { if (params.new) setForm({ truckId: params.truckId || '' }); if (params.id) setForm(db.jobcards.find((j: any) => j.id === params.id)); }, [params.new, params.id]);
  const rows = db.jobcards.slice().reverse();
  return (
    <div>
      <PageHeader eyebrow="Workshop & Inventory" title="Job cards" subtitle="Repair orders for own trucks: parts issued from stock and outside services. Approval is required before work; finalising issues stock and releases the truck with a gate pass." actions={<button className="btn-primary" onClick={() => setForm({})}><Plus size={15} /> New job card</button>} />
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-4">
        <KPI label="Trucks in workshop" value={db.jobcards.filter((j: any) => j.status !== 'Finalised').length} icon={Wrench} tone="warn" />
        <KPI label="Awaiting approval" value={db.jobcards.filter((j: any) => j.status === 'Pending Approval').length} icon={BadgeCheck} tone="brand" onClick={() => useUI.getState().nav('ws/jobcard-approval')} />
        <KPI label="Spend (30d)" value={inr(sum(db.jobcards.filter((j: any) => daysBetween(j.inDate) <= 30), (j: any) => j.net))} />
        <KPI label="Avg downtime" value={`${(sum(db.jobcards.filter((j: any) => j.outDate), (j: any) => daysBetween(j.inDate, j.outDate)) / Math.max(1, db.jobcards.filter((j: any) => j.outDate).length)).toFixed(1)} d`} />
      </div>
      <DataTable id="jobcards" rows={rows} onRow={(r) => openRecord('jobcard', r.id)} quickFilters={[{ key: 'o', label: 'Open', fn: (r: any) => r.status !== 'Finalised' }, { key: 'f', label: 'Finalised', fn: (r: any) => r.status === 'Finalised' }]} cols={[{ key: 'no', label: 'Job card number', render: (r) => <DocNo>{r.no}</DocNo>, mobile: 'title' }, { key: 'truck', label: 'Truck no.', value: (r) => lookup.truckNo(db, r.truckId), filter: true, mobile: 'sub' }, { key: 'driver', label: 'Driver name', value: (r) => lookup.driverName(db, r.driverId) }, { key: 'inDate', label: 'Date', render: (r) => fmtDate(r.inDate) }, { key: 'openingKm', label: 'Opening km', align: 'right', render: (r) => num(r.openingKm) }, { key: 'remark', label: 'Complaint' }, { key: 'net', label: 'Total amt', align: 'right', render: (r) => inr(r.net), mobile: 'right' }, { key: 'status', label: 'Status', filter: true, render: (r) => <StatusBadge s={r.status} />, mobile: 'meta' }]} rowActions={(r: any) => [{ label: 'Open', icon: Pencil, onClick: () => setForm(r), hidden: r.status === 'Finalised' }, { label: 'View', icon: Eye, onClick: () => openRecord('jobcard', r.id) }, { label: 'Print job card', icon: Printer, onClick: () => openPrint('jobcard', r.id) }, { label: 'Gate pass', icon: Printer, onClick: () => openPrint('gatepass', r.id), hidden: r.status !== 'Finalised' }]} />
      {form && <JobCardForm init={form} onClose={() => { setForm(null); useUI.getState().set({ params: {} }); }} />}
    </div>
  );
}
function JobCardForm({ init, onClose }: { init: any; onClose: () => void }) {
  const db = useDB();
  const [f, setF] = useState<any>(() => init.id ? structuredClone(init) : { truckStatus: 'At Jalgaon', truckId: init.truckId || '', driverId: lookup.truck(db, init.truckId)?.driverId || '', inDate: ymd(), inTime: hm(), outDate: '', outTime: '', openingKm: lookup.truck(db, init.truckId)?.odometer || '', parts: [], services: [], remark: '' });
  const [p, setP] = useState<any>({ cat: '', spareId: '', qty: 1, rate: '', mechanicId: '', description: '', disposal: '' });
  const [s, setS] = useState<any>({ supplierId: '', cat: '', spareId: '', qty: 1, rate: '', mechanicId: '', description: '' });
  const net = sum(f.parts, (x: any) => x.qty * x.rate) + sum(f.services, (x: any) => x.qty * x.rate);
  const locked = ['Approved', 'Finalised'].includes(f.status);
  const spare = lookup.spare(db, p.spareId);
  const lot = db.stock.find((x: any) => x.spareId === p.spareId && x.qty > 0);
  const addPart = () => { if (!p.spareId) return; if (stockQty(db, p.spareId) < Number(p.qty)) return useUI.getState().toast(`Only ${stockQty(db, p.spareId)} in stock`, 'bad', 'Raise a purchase order or reduce quantity'); setF({ ...f, parts: [...f.parts, { spareId: p.spareId, stockId: lot?.id, batch: lot?.batch || '', qty: Number(p.qty), rate: Number(p.rate || lot?.rate || spare?.rate), mechanicId: p.mechanicId, description: p.description, disposal: spare?.recyclable ? p.disposal || 'Recycle' : '' }] }); setP({ ...p, spareId: '', qty: 1, rate: '', description: '' }); };
  const addSvc = () => { if (!s.spareId || !s.supplierId) return; setF({ ...f, services: [...f.services, { supplierId: s.supplierId, spareId: s.spareId, qty: Number(s.qty), rate: Number(s.rate || lookup.spare(db, s.spareId)?.rate), mechanicId: s.mechanicId, description: s.description, serviceBillId: '' }] }); setS({ ...s, spareId: '', rate: '', description: '' }); };
  return (
    <Drawer open onClose={onClose} title={f.no ? `Job card ${f.no}` : 'Generate job card'} subtitle={f.status ? <StatusBadge s={f.status} /> : 'Legacy: Inventory/GenerateJobCard.aspx'} width="max-w-5xl" footer={<>
      <button className="btn-ghost" onClick={onClose}>Cancel</button>
      {!locked && <><button className="btn-ghost" onClick={() => { if (!f.truckId) return useUI.getState().toast('Select truck', 'bad'); A.saveJobCard({ ...f, openingKm: Number(f.openingKm) }, false); onClose(); }}>Save draft</button><button className="btn-primary" onClick={() => { if (!f.truckId || (!f.parts.length && !f.services.length)) return useUI.getState().toast('Select truck and add parts or services', 'bad'); A.saveJobCard({ ...f, openingKm: Number(f.openingKm) }, true); onClose(); }}><Send size={14} /> Submit for approval</button></>}
      {f.status === 'Approved' && <button className="btn-ok" onClick={() => { A.finaliseJobCard(f.id, { outDate: f.outDate || ymd(), outTime: f.outTime || hm() }); onClose(); useUI.getState().openPrint('gatepass', f.id); }}><CheckCircle2 size={14} /> Finalise & gate pass</button>}
    </>}>
      <div className="p-4 sm:p-5 grid gap-5">
        <FormSection title="Vehicle" cols={4}>
          <Field label="Truck status" className="col-span-2"><Radio options={['At Jalgaon', 'In Transit']} value={f.truckStatus} onChange={(v) => setF({ ...f, truckStatus: v })} /></Field>
          <Field label="Truck no." required><Select value={f.truckId} disabled={locked} onChange={(e) => { const t = lookup.truck(db, e.target.value); setF({ ...f, truckId: e.target.value, driverId: t?.driverId, openingKm: t?.odometer }); }} placeholder="Select" options={db.trucks.filter((t: any) => t.type === 'Own').map((t: any) => ({ value: t.id, label: `${t.number} · ${truckStatus(db, t)}` }))} /></Field>
          <Field label="Driver name"><Select value={f.driverId} onChange={(e) => setF({ ...f, driverId: e.target.value })} options={db.drivers.map((d: any) => ({ value: d.id, label: d.name }))} placeholder="Select" /></Field>
          <Field label="In date"><Input type="date" value={f.inDate} onChange={(e) => setF({ ...f, inDate: e.target.value })} /></Field><Field label="In time"><Input type="time" value={f.inTime} onChange={(e) => setF({ ...f, inTime: e.target.value })} /></Field>
          <Field label="Out date"><Input type="date" value={f.outDate} onChange={(e) => setF({ ...f, outDate: e.target.value })} /></Field><Field label="Out time"><Input type="time" value={f.outTime} onChange={(e) => setF({ ...f, outTime: e.target.value })} /></Field>
          <Field label="Opening KM"><Input type="number" value={f.openingKm} onChange={(e) => setF({ ...f, openingKm: e.target.value })} /></Field>
          <Field label="Complaint / remark" className="col-span-2 lg:col-span-3"><Input value={f.remark} onChange={(e) => setF({ ...f, remark: e.target.value })} /></Field>
        </FormSection>
        <FormSection title="Part detail" cols={1}>
          {!locked && <div className="grid grid-cols-2 lg:grid-cols-7 gap-2 items-end">
            <Field label="Category"><Select value={p.cat} onChange={(e) => setP({ ...p, cat: e.target.value, spareId: '' })} placeholder="All" options={db.spareCategories.filter((c: any) => c.type === 'Item').map((c: any) => ({ value: c.id, label: c.name }))} /></Field>
            <Field label="Part" className="col-span-2"><Select value={p.spareId} onChange={(e) => setP({ ...p, spareId: e.target.value, rate: lookup.spare(db, e.target.value)?.rate })} placeholder="Select part" options={db.spares.filter((x: any) => x.type === 'Item' && (!p.cat || x.categoryId === p.cat)).map((x: any) => ({ value: x.id, label: `${x.name} (stock ${stockQty(db, x.id)})` }))} /></Field>
            <Field label="Qty"><Input type="number" value={p.qty} onChange={(e) => setP({ ...p, qty: e.target.value })} /></Field>
            <Field label="Rate"><Input type="number" value={p.rate} onChange={(e) => setP({ ...p, rate: e.target.value })} /></Field>
            <Field label="Mechanic"><Select value={p.mechanicId} onChange={(e) => setP({ ...p, mechanicId: e.target.value })} placeholder="Select" options={mechOpts(db)} /></Field>
            <button className="btn-violet h-9" onClick={addPart}><Plus size={14} /> Add part</button>
            {spare?.recyclable && <Field label="Old part"><Radio options={['Recycle', 'Scrap']} value={p.disposal || 'Recycle'} onChange={(v) => setP({ ...p, disposal: v })} /></Field>}
          </div>}
          {f.parts.length > 0 && <div className="border border-line rounded-lg overflow-x-auto"><table className="w-full text-[12.5px] min-w-[620px]"><thead className="bg-surface2"><tr className="text-[10.5px] text-muted uppercase"><th className="text-left px-3 py-2">Part name</th><th className="px-2">Batch</th><th className="text-right px-2">Qty</th><th className="text-right px-2">Rate</th><th className="text-right px-2">Amount</th><th className="text-left px-2">Mechanic</th><th className="px-2">Recycle/Scrap</th><th className="w-9" /></tr></thead><tbody>{f.parts.map((x: any, k: number) => <tr key={k} className="border-t border-line"><td className="px-3 py-1.5">{lookup.spare(db, x.spareId)?.name}</td><td className="px-2 text-muted">{x.batch}</td><td className="px-2 text-right tnum">{x.qty}</td><td className="px-2 text-right tnum">{num(x.rate)}</td><td className="px-2 text-right tnum">{num(x.qty * x.rate)}</td><td className="px-2">{lookup.labour(db, x.mechanicId)}</td><td className="px-2">{x.disposal || '—'}</td><td className="pr-2">{!locked && <button className="btn-icon h-7 w-7 hover:text-bad" aria-label="Remove" onClick={() => setF({ ...f, parts: f.parts.filter((_: any, j: number) => j !== k) })}><Trash2 size={13} /></button>}</td></tr>)}</tbody></table></div>}
        </FormSection>
        <FormSection title="Service detail" cols={1}>
          {!locked && <div className="grid grid-cols-2 lg:grid-cols-7 gap-2 items-end">
            <Field label="Service provider" className="col-span-2"><Select value={s.supplierId} onChange={(e) => setS({ ...s, supplierId: e.target.value })} placeholder="Select" options={db.suppliers.filter((x: any) => x.type === 'Service').map((x: any) => ({ value: x.id, label: x.name }))} /></Field>
            <Field label="Service" className="col-span-2"><Select value={s.spareId} onChange={(e) => setS({ ...s, spareId: e.target.value, rate: lookup.spare(db, e.target.value)?.rate })} placeholder="Select service" options={db.spares.filter((x: any) => x.type === 'Service').map((x: any) => ({ value: x.id, label: x.name }))} /></Field>
            <Field label="Qty"><Input type="number" value={s.qty} onChange={(e) => setS({ ...s, qty: e.target.value })} /></Field>
            <Field label="Rate"><Input type="number" value={s.rate} onChange={(e) => setS({ ...s, rate: e.target.value })} /></Field>
            <button className="btn-violet h-9" onClick={addSvc}><Plus size={14} /> Add service</button>
          </div>}
          {f.services.length > 0 && <div className="border border-line rounded-lg overflow-x-auto"><table className="w-full text-[12.5px] min-w-[560px]"><thead className="bg-surface2"><tr className="text-[10.5px] text-muted uppercase"><th className="text-left px-3 py-2">Service</th><th className="text-left px-2">Service provider</th><th className="text-right px-2">Qty</th><th className="text-right px-2">Amount</th><th className="px-2">Bill</th><th className="w-9" /></tr></thead><tbody>{f.services.map((x: any, k: number) => <tr key={k} className="border-t border-line"><td className="px-3 py-1.5">{lookup.spare(db, x.spareId)?.name}</td><td className="px-2">{lookup.supplier(db, x.supplierId)}</td><td className="px-2 text-right tnum">{x.qty}</td><td className="px-2 text-right tnum">{num(x.qty * x.rate)}</td><td className="px-2">{x.serviceBillId ? <StatusBadge s="Billed" /> : <span className="text-faint">—</span>}</td><td className="pr-2">{!locked && <button className="btn-icon h-7 w-7 hover:text-bad" aria-label="Remove" onClick={() => setF({ ...f, services: f.services.filter((_: any, j: number) => j !== k) })}><Trash2 size={13} /></button>}</td></tr>)}</tbody></table></div>}
        </FormSection>
        <div className="flex justify-end"><div className="rounded-lg bg-surface2 border border-line px-4 py-2 text-right"><div className="text-[11px] text-muted font-semibold">Net amount</div><div className="font-display text-[20px] font-semibold tnum">{inr(net)}</div></div></div>
      </div>
    </Drawer>
  );
}

export function JobCardApproval() {
  const db = useDB();
  const { openRecord, openPrint } = useUI.getState();
  const rows = db.jobcards.filter((j: any) => j.status === 'Pending Approval');
  return (
    <div>
      <PageHeader eyebrow="Workshop & Inventory" title="Approve job card" subtitle="Approve workshop estimates before parts are issued. Returning a job card sends it back to draft." />
      <DataTable id="jc-approve" rows={rows} onRow={(r) => openRecord('jobcard', r.id)} bulkActions={[{ label: 'Approve', icon: BadgeCheck, onClick: (rs) => rs.forEach((r: any) => A.approveJobCard(r.id)) }]} expand={(r: any) => <div className="text-[12.5px] grid gap-1">{r.parts.map((p: any, k: number) => <div key={k}>{lookup.spare(db, p.spareId)?.name} × {p.qty} = {inr(p.qty * p.rate)} <span className="text-muted">(stock {stockQty(db, p.spareId)})</span></div>)}{r.services.map((p: any, k: number) => <div key={'s' + k}>{lookup.spare(db, p.spareId)?.name} by {lookup.supplier(db, p.supplierId)} = {inr(p.qty * p.rate)}</div>)}</div>} cols={[{ key: 'no', label: 'Job card no', render: (r) => <DocNo>{r.no}</DocNo>, mobile: 'title' }, { key: 'truck', label: 'Truck no', value: (r) => lookup.truckNo(db, r.truckId), mobile: 'sub' }, { key: 'driver', label: 'Driver name', value: (r) => lookup.driverName(db, r.driverId) }, { key: 'remark', label: 'Complaint' }, { key: 'net', label: 'Estimated amt', align: 'right', render: (r) => inr(r.net), mobile: 'right' }, { key: 'by', label: 'Created by' }]} rowActions={(r: any) => [{ label: 'Approve', icon: BadgeCheck, onClick: () => A.approveJobCard(r.id) }, { label: 'Return to workshop', icon: Undo2, onClick: () => A.approveJobCard(r.id, false) }, { label: 'View', icon: Eye, onClick: () => openRecord('jobcard', r.id) }, { label: 'Print', icon: Printer, onClick: () => openPrint('jobcard', r.id) }]} empty={<EmptyState icon={BadgeCheck} title="No job cards awaiting approval" />} />
    </div>
  );
}

// ---------------- Stock ----------------
export function SparesStock() {
  const db = useDB();
  const { nav } = useUI.getState();
  const items = db.spares.filter((s: any) => s.type === 'Item').map((s: any) => { const q = stockQty(db, s.id); const used = sum(db.jobcards.filter((j: any) => j.status === 'Finalised').flatMap((j: any) => j.parts).filter((p: any) => p.spareId === s.id), (p: any) => p.qty); return { ...s, q, value: sum(db.stock.filter((x: any) => x.spareId === s.id), (x: any) => x.qty * x.rate), used, state: q === 0 ? 'Out of stock' : q < s.minStock ? 'Low' : 'OK' }; });
  return (
    <div>
      <PageHeader eyebrow="Workshop & Inventory" title="Spares stock" subtitle="Current stock by part with minimum levels, value and consumption. Low items can be ordered straight from here." actions={<button className="btn-primary" onClick={() => nav('ws/po', { new: 1 })}><ShoppingCart size={15} /> Raise PO</button>} />
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-4">
        <KPI label="Stock value" value={inr(sum(items, (i: any) => i.value))} icon={Package} />
        <KPI label="Parts below minimum" value={items.filter((i: any) => i.state !== 'OK').length} icon={AlertTriangle} tone="bad" />
        <KPI label="Batches" value={db.stock.filter((s: any) => s.qty > 0).length} />
        <KPI label="Under warranty" value={db.inwards.flatMap((i: any) => i.items).filter((x: any) => x.warranty && x.wExp >= ymd()).length} tone="ok" />
      </div>
      <div className="grid lg:grid-cols-[1fr_380px] gap-4">
        <DataTable id="spares-stock" rows={items} quickFilters={[{ key: 'low', label: 'Below minimum', fn: (r: any) => r.state !== 'OK' }]} expand={(r: any) => <div className="text-[12.5px] grid gap-1">{db.stock.filter((x: any) => x.spareId === r.id && x.qty > 0).map((x: any) => <div key={x.id}>Batch <span className="docno">{x.batch}</span> · {x.qty} @ {inr(x.rate)} {x.isNew ? '' : '(retreaded / recycled)'}</div>)}</div>} cols={[{ key: 'name', label: 'Part name', mobile: 'title' }, { key: 'cat', label: 'Category', value: (r) => db.spareCategories.find((c: any) => c.id === r.categoryId)?.name, filter: true, mobile: 'sub' }, { key: 'q', label: 'Stock qty', align: 'right', render: (r) => `${r.q} ${r.unit}`, mobile: 'right' }, { key: 'minStock', label: 'Min stock', align: 'right' }, { key: 'value', label: 'Value', align: 'right', render: (r) => inr(r.value) }, { key: 'used', label: 'Consumed', align: 'right' }, { key: 'state', label: 'Status', filter: true, render: (r) => <StatusBadge s={r.state} tone={r.state === 'OK' ? 'ok' : 'bad'} />, mobile: 'meta' }]} />
        <ChartCard title="Consumption" subtitle="Qty issued on finalised job cards" height={320}><Bars data={items.filter((i: any) => i.used).sort((a: any, b: any) => b.used - a.used).slice(0, 8).map((i: any) => ({ x: i.name.slice(0, 16), Qty: i.used }))} keys={[{ key: 'Qty', label: 'Qty' }]} horizontal /></ChartCard>
      </div>
    </div>
  );
}

const SPARE_DEF: EntityDef = { key: 'spare', coll: 'spares', title: 'Spares & services', singular: 'Part / service', group: 'Workshop', eyebrow: 'Workshop & Inventory', legacy: ['Inventory/SpareList', 'SpareDetail'], desc: 'Parts (stocked items) and outside services with standard rate, unit, minimum stock and recyclability.', quick: [{ key: 'i', label: 'Parts', fn: (r) => r.type === 'Item' }, { key: 's', label: 'Services', fn: (r) => r.type === 'Service' }], defaults: () => ({ type: 'Item', minStock: 0, unit: 'Nos' }),
  fields: [{ k: 'name', l: 'Part / service name', req: true }, { k: 'type', l: 'Type', t: 'radio', opts: ['Item', 'Service'] }, { k: 'categoryId', l: 'Category', t: 'select', opts: (db) => db.spareCategories.map((c: any) => ({ value: c.id, label: `${c.name} (${c.type})` })), req: true }, { k: 'rate', l: 'Rate (₹)', t: 'number', req: true }, { k: 'minStock', l: 'Min stock count', t: 'number' }, { k: 'unit', l: 'Unit', t: 'select', opts: ['Nos', 'Ltr', 'Kg', 'Set', 'Job'] }, { k: 'recyclable', l: 'Is recyclable', t: 'bool' }, { k: 'batch', l: 'Track batch no.', t: 'bool' }, { k: 'description', l: 'Description', t: 'textarea', span: 2 }],
  cols: (db) => [{ key: 'name', label: 'Part name', mobile: 'title' }, { key: 'type', label: 'Type', filter: true, render: (r) => <StatusBadge s={r.type} tone={r.type === 'Item' ? 'violet' : 'info'} dot={false} />, mobile: 'meta' }, { key: 'cat', label: 'Category', value: (r) => db.spareCategories.find((c: any) => c.id === r.categoryId)?.name, filter: true, mobile: 'sub' }, { key: 'rate', label: 'Rate', align: 'right', render: (r) => inr(r.rate), mobile: 'right' }, { key: 'minStock', label: 'Min stock count', align: 'right' }, { key: 'stock', label: 'Stock', align: 'right', value: (r) => (r.type === 'Item' ? stockQty(db, r.id) : '—') }] };
const CAT_DEF: EntityDef = { key: 'spcat', coll: 'spareCategories', title: 'Categories', singular: 'Category', group: 'Workshop', eyebrow: 'Workshop & Inventory', legacy: ['Inventory/CategoryList', 'CategoryDetail'], desc: '', defaults: () => ({ type: 'Item' }), fields: [{ k: 'name', l: 'Category name', req: true }, { k: 'type', l: 'Type', t: 'radio', opts: ['Item', 'Service'] }, { k: 'description', l: 'Description', t: 'textarea', span: 2 }], cols: () => [{ key: 'name', label: 'Category', mobile: 'title' }, { key: 'type', label: 'Type', filter: true, mobile: 'meta' }, { key: 'description', label: 'Description', mobile: 'sub' }] };
export function SparesMaster() { const [t, setT] = useState('spares'); return <div><Tabs value={t} onChange={setT} className="mb-4" tabs={[{ key: 'spares', label: 'Parts & services' }, { key: 'cat', label: 'Categories' }]} />{t === 'spares' ? <CrudPage def={SPARE_DEF} /> : <CrudPage def={CAT_DEF} />}</div>; }

const SUP_DEF: EntityDef = { key: 'supplier', coll: 'suppliers', title: 'Suppliers & service providers', singular: 'Supplier', group: 'Workshop', eyebrow: 'Workshop & Inventory', legacy: ['Inventory/SupplierList', 'SupplierDetail'], desc: 'Spare-part sellers and workshop service providers with tax details.', quick: [{ key: 's', label: 'Sellers', fn: (r) => r.type === 'Seller' }, { key: 'v', label: 'Service providers', fn: (r) => r.type === 'Service' }], defaults: () => ({ type: 'Seller' }),
  fields: [{ k: 'name', l: 'Supplier name', req: true }, { k: 'type', l: 'Supplier type', t: 'select', opts: ['Seller', 'Service'], req: true }, { k: 'shop', l: 'Shop name' }, { k: 'city', l: 'City', t: 'select', opts: (db) => db.cities.map((c: any) => ({ value: c.id, label: c.name })) }, { k: 'address', l: 'Address', t: 'textarea', span: 2 }, { k: 'contactPerson', l: 'Contact person' }, { k: 'contact', l: 'Contact no.' }, { k: 'mobile', l: 'Mobile no.' }, { k: 'email', l: 'Email id', t: 'email' }, { k: 'vat', l: 'VAT / TIN / GST no.' }, { k: 'pan', l: 'PAN no.' }],
  cols: (db) => [{ key: 'shop', label: 'Shop name', mobile: 'title' }, { key: 'name', label: 'Supplier' }, { key: 'type', label: 'Type', filter: true, mobile: 'meta' }, { key: 'mobile', label: 'Mobile no.', mobile: 'sub' }, { key: 'contact', label: 'Contact no.' }, { key: 'city', label: 'City', value: (r) => lookup.cityName(db, r.city) }, { key: 'pend', label: 'Payable', align: 'right', value: (r) => sum(db.inwards.filter((i: any) => i.supplierId === r.id), (i: any) => i.pending) + sum(db.serviceBills.filter((b: any) => b.supplierId === r.id), (b: any) => b.pending), render: (r) => inr(sum(db.inwards.filter((i: any) => i.supplierId === r.id), (i: any) => i.pending) + sum(db.serviceBills.filter((b: any) => b.supplierId === r.id), (b: any) => b.pending)) }] };
export const Suppliers = () => <CrudPage def={SUP_DEF} />;

// ---------------- Purchase orders ----------------
export function PurchaseOrders() {
  const db = useDB();
  const params = useUI((s) => s.params);
  const { openRecord, openPrint } = useUI.getState();
  const [form, setForm] = useState<any>(params.new ? {} : null);
  return (
    <div>
      <PageHeader eyebrow="Workshop & Inventory" title="Purchase orders" subtitle="Order parts from sellers. POs need approval before stock can be inwarded against them." actions={<button className="btn-primary" onClick={() => setForm({})}><Plus size={15} /> Generate PO</button>} />
      <DataTable id="pos" rows={db.pos.slice().reverse()} onRow={(r) => openRecord('po', r.id)} cols={[{ key: 'no', label: 'PO number', render: (r) => <DocNo>{r.no}</DocNo>, mobile: 'title' }, { key: 's', label: 'Supplier', value: (r) => lookup.supplier(db, r.supplierId), filter: true, mobile: 'sub' }, { key: 'date', label: 'Date', render: (r) => fmtDate(r.date) }, { key: 'items', label: 'Parts', value: (r) => r.items.length, align: 'right' }, { key: 'net', label: 'Estimated amt', align: 'right', render: (r) => inr(r.net), mobile: 'right' }, { key: 'status', label: 'Approval status', filter: true, render: (r) => <StatusBadge s={r.status} />, mobile: 'meta' }]} rowActions={(r: any) => [{ label: 'Edit', icon: Pencil, onClick: () => setForm(r), hidden: r.status !== 'Pending Approval' }, { label: 'Print PO', icon: Printer, onClick: () => openPrint('po', r.id) }, { label: 'Delete', icon: Trash2, tone: 'bad', hidden: r.status !== 'Pending Approval', onClick: () => A.remove('pos', r.id, 'PO') }]} />
      {form && <POForm init={form} onClose={() => { setForm(null); useUI.getState().set({ params: {} }); }} />}
    </div>
  );
}
function POForm({ init, onClose }: any) {
  const db = useDB();
  const low = db.spares.filter((s: any) => s.type === 'Item' && stockQty(db, s.id) < s.minStock);
  const [f, setF] = useState<any>(() => init.id ? structuredClone(init) : { supplierId: '', date: ymd(), remark: '', items: low.slice(0, 3).map((s: any) => ({ spareId: s.id, qty: Math.max(1, s.minStock * 2 - stockQty(db, s.id)), rate: s.rate })) });
  const [p, setP] = useState<any>({ cat: '', spareId: '', qty: 1 });
  return (
    <Drawer open onClose={onClose} title={init.id ? `Edit ${init.no}` : 'Generate purchase order'} subtitle={!init.id && low.length ? `Pre-filled with ${Math.min(3, low.length)} parts below minimum stock` : 'Legacy: Inventory/GeneratePurchaseOrder.aspx'} footer={<><button className="btn-ghost" onClick={onClose}>Cancel</button><button className="btn-primary" onClick={() => { if (!f.supplierId || !f.items.length) return useUI.getState().toast('Select supplier and add parts', 'bad'); A.savePO(f); onClose(); }}>Save & send for approval</button></>}>
      <div className="p-4 sm:p-5 grid gap-5">
        <div className="grid sm:grid-cols-2 gap-3"><Field label="Supplier name" required><Select value={f.supplierId} onChange={(e) => setF({ ...f, supplierId: e.target.value })} placeholder="Select" options={db.suppliers.filter((s: any) => s.type === 'Seller').map((s: any) => ({ value: s.id, label: s.name }))} /></Field><Field label="Date"><Input type="date" value={f.date} onChange={(e) => setF({ ...f, date: e.target.value })} /></Field></div>
        <div className="grid grid-cols-2 sm:grid-cols-[1fr_1.4fr_90px_auto] gap-2 items-end"><Field label="Category"><Select value={p.cat} onChange={(e) => setP({ ...p, cat: e.target.value })} placeholder="All" options={db.spareCategories.filter((c: any) => c.type === 'Item').map((c: any) => ({ value: c.id, label: c.name }))} /></Field><Field label="Part"><Select value={p.spareId} onChange={(e) => setP({ ...p, spareId: e.target.value })} placeholder="Select" options={db.spares.filter((s: any) => s.type === 'Item' && (!p.cat || s.categoryId === p.cat)).map((s: any) => ({ value: s.id, label: s.name }))} /></Field><Field label="Qty"><Input type="number" value={p.qty} onChange={(e) => setP({ ...p, qty: Number(e.target.value) })} /></Field><button className="btn-violet h-9" onClick={() => { if (!p.spareId) return; setF({ ...f, items: [...f.items, { spareId: p.spareId, qty: p.qty, rate: lookup.spare(db, p.spareId).rate }] }); setP({ ...p, spareId: '' }); }}><Plus size={14} /> Add part</button></div>
        {f.items.length > 0 && <div className="border border-line rounded-lg overflow-hidden"><table className="w-full text-[12.5px]"><thead className="bg-surface2"><tr className="text-[10.5px] text-muted uppercase"><th className="text-left px-3 py-2">Part</th><th className="px-2 w-20">Qty</th><th className="px-2 w-24">Rate</th><th className="text-right px-2">Amount</th><th className="w-9" /></tr></thead><tbody>{f.items.map((it: any, k: number) => <tr key={k} className="border-t border-line"><td className="px-3 py-1.5">{lookup.spare(db, it.spareId)?.name}<div className="text-[11px] text-muted">stock {stockQty(db, it.spareId)} · min {lookup.spare(db, it.spareId)?.minStock}</div></td><td className="px-2"><input className="input h-7 text-right" type="number" aria-label="Qty" value={it.qty} onChange={(e) => setF({ ...f, items: f.items.map((x: any, j: number) => (j === k ? { ...x, qty: Number(e.target.value) } : x)) })} /></td><td className="px-2"><input className="input h-7 text-right" type="number" aria-label="Rate" value={it.rate} onChange={(e) => setF({ ...f, items: f.items.map((x: any, j: number) => (j === k ? { ...x, rate: Number(e.target.value) } : x)) })} /></td><td className="px-2 text-right tnum">{num(it.qty * it.rate)}</td><td className="pr-2"><button className="btn-icon h-7 w-7 hover:text-bad" aria-label="Remove" onClick={() => setF({ ...f, items: f.items.filter((_: any, j: number) => j !== k) })}><Trash2 size={13} /></button></td></tr>)}</tbody></table></div>}
        <div className="grid sm:grid-cols-[1fr_200px] gap-3 items-end"><Field label="Remark"><Input value={f.remark} onChange={(e) => setF({ ...f, remark: e.target.value })} /></Field><Stat label="Net amount" value={inr(sum(f.items, (x: any) => x.qty * x.rate))} /></div>
      </div>
    </Drawer>
  );
}
export function POApproval() {
  const db = useDB();
  const { openRecord, openPrint } = useUI.getState();
  return (
    <div>
      <PageHeader eyebrow="Workshop & Inventory" title="Approve purchase order" subtitle="Approved POs become available for stock inward." />
      <DataTable id="po-approve" rows={db.pos.filter((p: any) => p.status === 'Pending Approval')} onRow={(r) => openRecord('po', r.id)} bulkActions={[{ label: 'Approve', icon: BadgeCheck, onClick: (rs) => rs.forEach((r: any) => A.approvePO(r.id)) }]} cols={[{ key: 'no', label: 'PO number', render: (r) => <DocNo>{r.no}</DocNo>, mobile: 'title' }, { key: 's', label: 'Supplier', value: (r) => lookup.supplier(db, r.supplierId), mobile: 'sub' }, { key: 'date', label: 'Date', render: (r) => fmtDate(r.date) }, { key: 'net', label: 'Estimated amt', align: 'right', render: (r) => inr(r.net), mobile: 'right' }]} rowActions={(r: any) => [{ label: 'Approve', icon: BadgeCheck, onClick: () => A.approvePO(r.id) }, { label: 'View', icon: Eye, onClick: () => openRecord('po', r.id) }, { label: 'Print', icon: Printer, onClick: () => openPrint('po', r.id) }]} empty={<EmptyState icon={BadgeCheck} title="No POs awaiting approval" />} />
    </div>
  );
}

// ---------------- Inward & inventory payments ----------------
export function Inward() {
  const db = useDB();
  const params = useUI((s) => s.params);
  const [tab, setTab] = useState('inward');
  const [poId, setPoId] = useState(params.poId || '');
  const po = db.pos.find((p: any) => p.id === poId);
  const [f, setF] = useState<any>({ billNo: '', billDate: ymd(), discount: 0, remark: '', items: [] });
  useEffect(() => { if (po) setF((x: any) => ({ ...x, items: po.items.map((i: any) => ({ ...i, batch: `B${Math.floor(1000 + Math.random() * 9000)}`, warranty: false, wExp: '', guarantee: false, gExp: '' })) })); }, [poId]);
  const net = sum(f.items, (i: any) => i.qty * i.rate);
  const [pay, setPay] = useState<any>(null);
  const [pf, setPf] = useState<any>({});
  return (
    <div>
      <PageHeader eyebrow="Workshop & Inventory" title="Stock inward" subtitle="Receive parts against approved POs with supplier bill, batch numbers and warranty/guarantee expiry. Supplier bills then flow to inventory payment." />
      <Tabs value={tab} onChange={setTab} className="mb-4" tabs={[{ key: 'inward', label: 'Inward stock entry' }, { key: 'pay', label: 'Inventory payment entry', count: db.inwards.filter((i: any) => i.pending > 0).length }]} />
      {tab === 'inward' ? <>
        <Card><div className="grid gap-4">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Field label="PO number" required><Select value={poId} onChange={(e) => setPoId(e.target.value)} placeholder="Approved POs" options={db.pos.filter((p: any) => p.status === 'Approved').map((p: any) => ({ value: p.id, label: `${p.no} · ${lookup.supplier(db, p.supplierId)}` }))} /></Field><Field label="Supplier"><Input value={po ? lookup.supplier(db, po.supplierId) : ''} disabled /></Field><Field label="Bill no." required><Input value={f.billNo} onChange={(e) => setF({ ...f, billNo: e.target.value })} /></Field><Field label="Bill date"><Input type="date" value={f.billDate} onChange={(e) => setF({ ...f, billDate: e.target.value })} /></Field></div>
          {f.items.length > 0 && <div className="border border-line rounded-lg overflow-x-auto"><table className="w-full text-[12.5px] min-w-[860px]"><thead className="bg-surface2"><tr className="text-[10.5px] text-muted uppercase"><th className="text-left px-3 py-2">Part name</th><th className="px-1 w-20">Qty</th><th className="px-1 w-24">Rate</th><th className="px-1 w-28">Batch no.</th><th className="px-1">Warranty</th><th className="px-1">W. exp date</th><th className="px-1">Guaranty</th><th className="px-1">G. exp date</th></tr></thead><tbody>{f.items.map((it: any, k: number) => { const up = (p: any) => setF({ ...f, items: f.items.map((x: any, j: number) => (j === k ? { ...x, ...p } : x)) }); return <tr key={k} className="border-t border-line"><td className="px-3 py-1.5">{lookup.spare(db, it.spareId)?.name}</td><td className="px-1"><input className="input h-7 text-right" type="number" aria-label="Qty" value={it.qty} onChange={(e) => up({ qty: Number(e.target.value) })} /></td><td className="px-1"><input className="input h-7 text-right" type="number" aria-label="Rate" value={it.rate} onChange={(e) => up({ rate: Number(e.target.value) })} /></td><td className="px-1"><input className="input h-7 font-mono" aria-label="Batch" value={it.batch} onChange={(e) => up({ batch: e.target.value })} /></td><td className="px-1 text-center"><input type="checkbox" aria-label="Warranty" checked={it.warranty} onChange={(e) => up({ warranty: e.target.checked })} /></td><td className="px-1"><input className="input h-7" type="date" aria-label="Warranty expiry" disabled={!it.warranty} value={it.wExp} onChange={(e) => up({ wExp: e.target.value })} /></td><td className="px-1 text-center"><input type="checkbox" aria-label="Guarantee" checked={it.guarantee} onChange={(e) => up({ guarantee: e.target.checked })} /></td><td className="px-1"><input className="input h-7" type="date" aria-label="Guarantee expiry" disabled={!it.guarantee} value={it.gExp} onChange={(e) => up({ gExp: e.target.value })} /></td></tr>; })}</tbody></table></div>}
          <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 items-end"><Stat label="Net amount" value={inr(net)} /><Field label="Discount (₹)"><Input type="number" value={f.discount} onChange={(e) => setF({ ...f, discount: Number(e.target.value) })} /></Field><Stat label="Payable amount" value={inr(net - f.discount)} /><Field label="Remark"><Input value={f.remark} onChange={(e) => setF({ ...f, remark: e.target.value })} /></Field><button className="btn-primary h-9" disabled={!po || !f.billNo} onClick={() => { A.inward({ poId, supplierId: po.supplierId, billNo: f.billNo, billDate: f.billDate, items: f.items, net, discount: f.discount, payable: net - f.discount, remark: f.remark, isReplacement: false }); setPoId(''); setF({ billNo: '', billDate: ymd(), discount: 0, remark: '', items: [] }); }}><ArrowDownToLine size={15} /> Save inward</button></div>
        </div></Card>
        <div className="mt-6"><DataTable id="inwards" rows={db.inwards.slice().reverse()} cols={[{ key: 'no', label: 'Inward', render: (r) => <DocNo>{r.no}</DocNo>, mobile: 'title' }, { key: 'po', label: 'PO number', value: (r) => db.pos.find((p: any) => p.id === r.poId)?.no || (r.isReplacement ? 'Replacement' : '—') }, { key: 'billNo', label: 'Bill number' }, { key: 's', label: 'Supplier', value: (r) => lookup.supplier(db, r.supplierId), mobile: 'sub' }, { key: 'billDate', label: 'Date', render: (r) => fmtDate(r.billDate) }, { key: 'payable', label: 'Payable amt', align: 'right', render: (r) => inr(r.payable), mobile: 'right' }, { key: 'pending', label: 'Pending', align: 'right', render: (r) => inr(r.pending) }]} expand={(r: any) => <div className="text-[12.5px] grid gap-1">{r.items.map((i: any, k: number) => <div key={k}>{lookup.spare(db, i.spareId)?.name} · {i.qty} @ {inr(i.rate)} · batch <span className="docno">{i.batch}</span>{i.warranty && ` · warranty till ${fmtDate(i.wExp)}`}</div>)}</div>} /></div>
      </> : <DataTable id="inv-pay" rows={db.inwards.filter((i: any) => i.pending > 0)} onRow={(r) => { setPay(r); setPf({ date: ymd(), amount: r.pending - Math.round(r.pending * 0.01), tds: Math.round(r.pending * 0.01), discount: 0, paidBy: defLedger(db, 'l2'), mode: 'Bank' }); }} cols={[{ key: 's', label: 'Supplier', value: (r) => lookup.supplier(db, r.supplierId), mobile: 'title' }, { key: 'billNo', label: 'Bill no' }, { key: 'po', label: 'PO no', value: (r) => db.pos.find((p: any) => p.id === r.poId)?.no }, { key: 'billDate', label: 'Bill date', render: (r) => fmtDate(r.billDate), mobile: 'sub' }, { key: 'payable', label: 'Payable amt.', align: 'right', render: (r) => inr(r.payable) }, { key: 'paid', label: 'Paid amt.', align: 'right', value: (r) => sum(r.payments, (p: any) => p.amount) }, { key: 'pending', label: 'Pending', align: 'right', render: (r) => inr(r.pending), mobile: 'right' }]} empty={<EmptyState icon={CheckCircle2} title="All supplier bills paid" />} />}
      {pay && <Modal open onClose={() => setPay(null)} title={`Pay ${lookup.supplier(db, pay.supplierId)} · bill ${pay.billNo}`} footer={<><button className="btn-ghost" onClick={() => setPay(null)}>Back to bill list</button><button className="btn-primary" onClick={() => { A.payInward(pay.id, pf); setPay(null); }}>Confirm payment</button></>}><div className="text-[13px] mb-3">Pending {inr(pay.pending)}</div><div className="grid grid-cols-2 gap-3"><Field label="Paid date"><Input type="date" value={pf.date} onChange={(e) => setPf({ ...pf, date: e.target.value })} /></Field><Field label="Paid amount"><Input type="number" value={pf.amount} onChange={(e) => setPf({ ...pf, amount: Number(e.target.value) })} /></Field><Field label="Discount"><Input type="number" value={pf.discount} onChange={(e) => setPf({ ...pf, discount: Number(e.target.value) })} /></Field><Field label="TDS"><Input type="number" value={pf.tds} onChange={(e) => setPf({ ...pf, tds: Number(e.target.value) })} /></Field><Field label="Payment by"><Select value={pf.paidBy} onChange={(e) => setPf({ ...pf, paidBy: e.target.value })} options={db.ledgers.map((l: any) => ({ value: l.id, label: l.name }))} /></Field><Field label="Mode"><Radio options={['Cash', 'Cheque', 'Bank']} value={pf.mode} onChange={(v) => setPf({ ...pf, mode: v })} /></Field></div></Modal>}
    </div>
  );
}

export function Replacement() {
  const db = useDB();
  const { openPrint } = useUI.getState();
  const [tab, setTab] = useState('list');
  const [f, setF] = useState<any>({ supplierId: '', date: ymd(), inwardId: '', payable: false, items: [], remark: '' });
  const inws = db.inwards.filter((i: any) => i.supplierId === f.supplierId);
  const inw = db.inwards.find((i: any) => i.id === f.inwardId);
  const [rcv, setRcv] = useState<any>(null);
  const [rf, setRf] = useState<any>({ billNo: '', billDate: ymd(), rate: 0, qty: 1, batch: '' });
  return (
    <div>
      <PageHeader eyebrow="Workshop & Inventory" title="Spare replacement" subtitle="Return defective parts to the supplier under warranty (free) or as paid replacement, issue an RP gate pass, then receive the replacement back into stock." />
      <Tabs value={tab} onChange={setTab} className="mb-4" tabs={[{ key: 'list', label: 'Replacement list', count: db.replacements.length }, { key: 'new', label: 'New replacement' }]} />
      {tab === 'new' ? <Card><div className="grid gap-4">
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Field label="Supplier name"><Select value={f.supplierId} onChange={(e) => setF({ ...f, supplierId: e.target.value, inwardId: '', items: [] })} placeholder="Select" options={db.suppliers.filter((s: any) => s.type === 'Seller').map((s: any) => ({ value: s.id, label: s.name }))} /></Field><Field label="Date"><Input type="date" value={f.date} onChange={(e) => setF({ ...f, date: e.target.value })} /></Field><Field label="Bill no."><Select value={f.inwardId} onChange={(e) => setF({ ...f, inwardId: e.target.value, items: [] })} placeholder="Select bill" options={inws.map((i: any) => ({ value: i.id, label: `${i.billNo} · ${fmtDate(i.billDate)}` }))} /></Field><Field label="Type"><Radio options={['Free', 'Payable']} value={f.payable ? 'Payable' : 'Free'} onChange={(v) => setF({ ...f, payable: v === 'Payable' })} /></Field></div>
        {inw && <div className="border border-line rounded-lg overflow-x-auto"><table className="w-full text-[12.5px] min-w-[560px]"><thead className="bg-surface2"><tr className="text-[10.5px] text-muted uppercase"><th className="text-left px-3 py-2">Part name</th><th className="px-2">Batch no</th><th className="text-right px-2">Rate</th><th className="text-right px-2">Stock qty</th><th className="px-3 w-24">Qty</th></tr></thead><tbody>{inw.items.map((it: any, k: number) => { const lot = db.stock.find((s: any) => s.inwardId === inw.id && s.spareId === it.spareId); const cur = f.items.find((x: any) => x.spareId === it.spareId); return <tr key={k} className="border-t border-line"><td className="px-3 py-1.5">{lookup.spare(db, it.spareId)?.name}</td><td className="px-2 docno">{it.batch}</td><td className="px-2 text-right tnum">{num(it.rate)}</td><td className="px-2 text-right tnum">{lot?.qty ?? 0}</td><td className="px-3"><input className="input h-7 text-right" type="number" aria-label="Qty" value={cur?.qty || ''} placeholder="0" onChange={(e) => { const q = Number(e.target.value); const others = f.items.filter((x: any) => x.spareId !== it.spareId); setF({ ...f, items: q ? [...others, { inwardId: inw.id, spareId: it.spareId, batch: it.batch, qty: q }] : others }); }} /></td></tr>; })}</tbody></table></div>}
        <Field label="Remark"><Input value={f.remark} onChange={(e) => setF({ ...f, remark: e.target.value })} placeholder="Defect description" /></Field>
        <div className="flex justify-end"><button className="btn-primary" disabled={!f.items.length} onClick={() => { const r = A.createReplacement(f); setTab('list'); openPrint('rpgatepass', r.id); setF({ ...f, items: [], inwardId: '' }); }}><Repeat size={15} /> Add & print gate pass</button></div>
      </div></Card>
        : <DataTable id="replacements" rows={db.replacements.slice().reverse()} cols={[{ key: 'no', label: 'Replacement no', render: (r) => <DocNo>{r.no}</DocNo>, mobile: 'title' }, { key: 's', label: 'Supplier', value: (r) => lookup.supplier(db, r.supplierId), mobile: 'sub' }, { key: 'date', label: 'Date', render: (r) => fmtDate(r.date) }, { key: 'parts', label: 'Parts', value: (r) => r.items.map((i: any) => `${lookup.spare(db, i.spareId)?.name} × ${i.qty}`).join(', ') }, { key: 'payable', label: 'Type', value: (r) => (r.payable ? 'Payable' : 'Free') }, { key: 'status', label: 'Status', render: (r) => <StatusBadge s={r.status} />, mobile: 'meta' }]} rowActions={(r: any) => [{ label: 'Gate pass', icon: Printer, onClick: () => openPrint('rpgatepass', r.id) }, { label: 'Receive replacement', icon: ArrowDownToLine, hidden: r.status !== 'Sent', onClick: () => { setRcv(r); setRf({ billNo: '', billDate: ymd(), rate: 0, qty: r.items[0]?.qty || 1, batch: `R${Math.floor(1000 + Math.random() * 9000)}` }); } }]} />}
      {rcv && <Modal open onClose={() => setRcv(null)} title={`Replacement inward · ${rcv.no}`} footer={<><button className="btn-ghost" onClick={() => setRcv(null)}>Cancel</button><button className="btn-primary" onClick={() => { A.inward({ poId: '', replacementId: rcv.id, supplierId: rcv.supplierId, billNo: rf.billNo || 'FREE', billDate: rf.billDate, items: rcv.items.map((i: any) => ({ spareId: i.spareId, qty: rf.qty, rate: rcv.payable ? rf.rate : 0, batch: rf.batch, warranty: false })), net: rcv.payable ? rf.rate * rf.qty : 0, discount: 0, payable: rcv.payable ? rf.rate * rf.qty : 0, remark: 'Replacement inward', isReplacement: true }); setRcv(null); }}>Save inward</button></>}><div className="grid grid-cols-2 gap-3"><Field label="Bill no."><Input value={rf.billNo} onChange={(e) => setRf({ ...rf, billNo: e.target.value })} placeholder={rcv.payable ? '' : 'Free replacement'} /></Field><Field label="Bill date"><Input type="date" value={rf.billDate} onChange={(e) => setRf({ ...rf, billDate: e.target.value })} /></Field><Field label="Qty"><Input type="number" value={rf.qty} onChange={(e) => setRf({ ...rf, qty: Number(e.target.value) })} /></Field><Field label="Batch no."><Input value={rf.batch} onChange={(e) => setRf({ ...rf, batch: e.target.value })} /></Field>{rcv.payable && <Field label="Rate"><Input type="number" value={rf.rate} onChange={(e) => setRf({ ...rf, rate: Number(e.target.value) })} /></Field>}</div></Modal>}
    </div>
  );
}

export function ServiceBills() {
  const db = useDB();
  const [sid, setSid] = useState('');
  const pending = db.jobcards.filter((j: any) => j.status === 'Finalised' || j.status === 'Approved').flatMap((j: any) => j.services.map((s: any, idx: number) => ({ j, s, idx }))).filter((x: any) => !x.s.serviceBillId && (!sid || x.s.supplierId === sid));
  const [pick, setPick] = useState<Set<string>>(new Set());
  const [f, setF] = useState({ billNo: '', billDate: ymd(), discount: 0, remark: '' });
  const total = sum(pending.filter((x: any) => pick.has(x.j.id + x.idx)), (x: any) => x.s.qty * x.s.rate);
  return (
    <div>
      <PageHeader eyebrow="Workshop & Inventory" title="Service bills" subtitle="Record service-provider bills against job-card services. Bills then appear in service payment entry." />
      <Card><div className="grid gap-4">
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Field label="Service provider"><Select value={sid} onChange={(e) => { setSid(e.target.value); setPick(new Set()); }} placeholder="All" options={db.suppliers.filter((s: any) => s.type === 'Service').map((s: any) => ({ value: s.id, label: s.name }))} /></Field><Field label="Bill no."><Input value={f.billNo} onChange={(e) => setF({ ...f, billNo: e.target.value })} /></Field><Field label="Bill date"><Input type="date" value={f.billDate} onChange={(e) => setF({ ...f, billDate: e.target.value })} /></Field><Field label="Discount (₹)"><Input type="number" value={f.discount} onChange={(e) => setF({ ...f, discount: Number(e.target.value) })} /></Field></div>
        {pending.length ? <div className="border border-line rounded-lg overflow-x-auto"><table className="w-full text-[12.5px] min-w-[600px]"><thead className="bg-surface2"><tr className="text-[10.5px] text-muted uppercase"><th className="w-8 px-3" /><th className="text-left px-2 py-2">Job card no.</th><th className="text-left px-2">Truck no.</th><th className="text-left px-2">Service</th><th className="text-left px-2">Service provider</th><th className="text-right px-3">Amount</th></tr></thead><tbody>{pending.map((x: any) => { const k = x.j.id + x.idx; return <tr key={k} className="border-t border-line"><td className="px-3"><input type="checkbox" aria-label="Select" checked={pick.has(k)} onChange={() => { const n = new Set(pick); n.has(k) ? n.delete(k) : n.add(k); setPick(n); if (!sid) setSid(x.s.supplierId); }} /></td><td className="px-2 py-1.5 docno">{x.j.no}</td><td className="px-2 docno">{lookup.truckNo(db, x.j.truckId)}</td><td className="px-2">{lookup.spare(db, x.s.spareId)?.name}</td><td className="px-2">{lookup.supplier(db, x.s.supplierId)}</td><td className="px-3 text-right tnum">{num(x.s.qty * x.s.rate)}</td></tr>; })}</tbody></table></div> : <EmptyState icon={Receipt} title="No unbilled services" />}
        <div className="flex flex-wrap items-center justify-end gap-4"><span className="text-[13px]">Total {inr(total)} · net payable <b>{inr(total - f.discount)}</b></span><button className="btn-primary" disabled={!pick.size || !f.billNo} onClick={() => { const items = pending.filter((x: any) => pick.has(x.j.id + x.idx)).map((x: any) => ({ jobCardId: x.j.id, serviceIdx: x.idx })); A.createServiceBill({ supplierId: sid, billNo: f.billNo, billDate: f.billDate, items, total, discount: f.discount, net: total - f.discount, remark: f.remark }); setPick(new Set()); setF({ ...f, billNo: '' }); }}>Submit</button></div>
      </div></Card>
      <div className="mt-6"><DataTable id="service-bills" rows={db.serviceBills.slice().reverse()} cols={[{ key: 'no', label: 'Ref', render: (r) => <DocNo>{r.no}</DocNo> }, { key: 'billNo', label: 'Bill no.', mobile: 'title' }, { key: 's', label: 'Service provider', value: (r) => lookup.supplier(db, r.supplierId), mobile: 'sub' }, { key: 'billDate', label: 'Bill date', render: (r) => fmtDate(r.billDate) }, { key: 'jc', label: 'Job cards', value: (r) => [...new Set(r.items.map((i: any) => db.jobcards.find((j: any) => j.id === i.jobCardId)?.no))].join(', ') }, { key: 'total', label: 'Total amt', align: 'right', render: (r) => inr(r.total) }, { key: 'discount', label: 'Discount', align: 'right', render: (r) => inr(r.discount) }, { key: 'net', label: 'Payable amt', align: 'right', render: (r) => inr(r.net), mobile: 'right' }, { key: 'st', label: 'Status', render: (r) => <StatusBadge s={r.pending <= 0 ? 'Paid' : 'Pending'} />, mobile: 'meta' }]} /></div>
    </div>
  );
}

export function ServicePayments() {
  const db = useDB();
  const [pay, setPay] = useState<any>(null);
  const [pf, setPf] = useState<any>({});
  return (
    <div>
      <PageHeader eyebrow="Workshop & Inventory" title="Job card service payment entry" subtitle="Pay service providers against recorded service bills." />
      <DataTable id="svc-pay" rows={db.serviceBills.slice().reverse()} quickFilters={[{ key: 'p', label: 'Pending', fn: (r: any) => r.pending > 0 }]} initialQuick="p" onRow={(r) => { if (r.pending > 0) { setPay(r); setPf({ date: ymd(), amount: r.pending, tds: 0, discount: 0, paidBy: defLedger(db, 'l4'), mode: 'Cash' }); } }} cols={[{ key: 'billNo', label: 'Bill no.', mobile: 'title' }, { key: 'billDate', label: 'Bill date', render: (r) => fmtDate(r.billDate) }, { key: 's', label: 'Service provider', value: (r) => lookup.supplier(db, r.supplierId), mobile: 'sub' }, { key: 'pd', label: 'Paid date', render: (r) => fmtDate(r.payments.at(-1)?.date) }, { key: 'net', label: 'Net amt.', align: 'right', render: (r) => inr(r.net) }, { key: 'paid', label: 'Paid amt.', align: 'right', value: (r) => sum(r.payments, (p: any) => p.amount), render: (r) => inr(sum(r.payments, (p: any) => p.amount)) }, { key: 'pending', label: 'Pending', align: 'right', render: (r) => inr(r.pending), mobile: 'right' }]} rowActions={(r: any) => [{ label: 'Record payment', icon: Banknote, hidden: r.pending <= 0, onClick: () => { setPay(r); setPf({ date: ymd(), amount: r.pending, tds: 0, discount: 0, paidBy: 'l4', mode: 'Cash' }); } }]} />
      {pay && <Modal open onClose={() => setPay(null)} title={`Pay ${lookup.supplier(db, pay.supplierId)} · bill ${pay.billNo}`} footer={<><button className="btn-ghost" onClick={() => setPay(null)}>Back to bill list</button><button className="btn-primary" onClick={() => { A.payServiceBill(pay.id, pf); setPay(null); }}>Confirm payment</button></>}><div className="grid grid-cols-2 gap-3"><Field label="Pending amount"><Input value={pay.pending} disabled /></Field><Field label="Paid date"><Input type="date" value={pf.date} onChange={(e) => setPf({ ...pf, date: e.target.value })} /></Field><Field label="Paid amount"><Input type="number" value={pf.amount} onChange={(e) => setPf({ ...pf, amount: Number(e.target.value) })} /></Field><Field label="Discount"><Input type="number" value={pf.discount} onChange={(e) => setPf({ ...pf, discount: Number(e.target.value) })} /></Field><Field label="TDS"><Input type="number" value={pf.tds} onChange={(e) => setPf({ ...pf, tds: Number(e.target.value) })} /></Field><Field label="Payment by"><Select value={pf.paidBy} onChange={(e) => setPf({ ...pf, paidBy: e.target.value })} options={db.ledgers.map((l: any) => ({ value: l.id, label: l.name }))} /></Field><Field label="Mode" className="col-span-2"><Radio options={['Cash', 'Cheque', 'Bank']} value={pf.mode} onChange={(v) => setPf({ ...pf, mode: v })} /></Field></div></Modal>}
    </div>
  );
}
