-- SK Translines legacy database (converted from SQL Server backup ERPdatabase20250608.bak)
-- Generated for PostgreSQL 14+. Original names are listed in name_map.csv.

CREATE SCHEMA IF NOT EXISTS legacy;
SET search_path TO legacy;

-- LGST_Accident: 0 rows
CREATE TABLE accident (
  accident_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  accident_no varchar(50),
  accident_date varchar(8),
  vehicle_no integer,
  driver_id integer,
  location_id integer,
  vehicle_part_loss varchar(100),
  vehicle_part_loss_desc varchar(500),
  human_loss varchar(100),
  human_loss_desc varchar(500),
  other_loss varchar(100),
  other_loss_desc varchar(500),
  reason_of_accident varchar(200),
  accident_responsible_person varchar(100),
  total_loss numeric(25,2),
  remark varchar(1000),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (accident_id)
);
COMMENT ON TABLE accident IS 'Legacy table LGST_Accident';

-- LGST_AccountLedger: 241432 rows
CREATE TABLE account_ledger (
  acc_ledger_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  client_id integer,
  transporter_id integer,
  ledger_id integer,
  branch_id integer,
  particular varchar(200),
  credit_amount numeric(10,2),
  debit_amount numeric(10,2),
  entry_date timestamp,
  voucher_type varchar(50),
  reference_type varchar(100),
  reference_id numeric(10,0),
  is_active smallint,
  created_date timestamp,
  createdby varchar(5),
  modified_date timestamp,
  modifiedby varchar(5),
  voucher_no varchar(20),
  reference_no varchar(500),
  ref_type varchar(20),
  tally_master_id numeric(10,0),
  ip_address varchar(20),
  is_ledger_entry smallint,
  PRIMARY KEY (acc_ledger_id)
);
COMMENT ON TABLE account_ledger IS 'Legacy table LGST_AccountLedger';

-- LGST_AccountLedger_History: 8328 rows
CREATE TABLE account_ledger_history (
  id integer,
  client_id integer,
  transporter_id integer,
  ledger_id integer,
  branch_id integer,
  particular varchar(200),
  credit_amount numeric(10,2),
  debit_amount numeric(10,2),
  entry_date timestamp,
  voucher_type varchar(50),
  reference_type varchar(100),
  reference_id numeric(10,0),
  is_active smallint,
  created_date timestamp,
  createdby varchar(5),
  deleted_date timestamp,
  deletedby varchar(5),
  voucher_no varchar(20),
  reference_no varchar(500),
  ref_type varchar(20),
  tally_master_id numeric(10,0),
  ip_address varchar(20),
  is_ledger_entry smallint
);
COMMENT ON TABLE account_ledger_history IS 'Legacy table LGST_AccountLedger_History';

-- LGST_Agreement: 34 rows
CREATE TABLE agreement (
  agreement_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  company_id integer,
  agreement_date varchar(8),
  start_date varchar(8),
  expiry_date varchar(8),
  client_id integer,
  city_id integer,
  rate_type varchar(2),
  rate numeric(25,2),
  rate_inclusive_tax varchar(1),
  detention_rate numeric(25,2),
  lead_generated_by_branch_id integer,
  agreement_commtted_trips integer,
  apply_rate_commited_buss_not_achieved varchar(1),
  approved_by integer,
  approved_on_date varchar(15),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  carrying_capacity numeric(20,2),
  PRIMARY KEY (agreement_id)
);
COMMENT ON TABLE agreement IS 'Legacy table LGST_Agreement';

-- LGST_Announcements: 110 rows
CREATE TABLE announcements (
  announcement_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title varchar(500),
  description varchar(5000),
  expiry_date timestamp,
  is_all_users smallint,
  branch_id varchar(50),
  role_id varchar(200),
  user_id varchar(200),
  createdby integer,
  created_date timestamp,
  modifiedby integer,
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (announcement_id)
);
COMMENT ON TABLE announcements IS 'Legacy table LGST_Announcements';

-- LGST_Announcements_Customer: 0 rows
CREATE TABLE announcements_customer (
  announcement_id integer,
  title varchar(500),
  description varchar(5000),
  start_date timestamp,
  end_date timestamp,
  customer_id text,
  created_by integer,
  created_date timestamp,
  modifiedby integer,
  modified_date timestamp,
  is_active smallint
);
COMMENT ON TABLE announcements_customer IS 'Legacy table LGST_Announcements_Customer';

-- LGST_BillDetail: 7645 rows
CREATE TABLE bill_detail (
  bill_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  bill_number varchar(20),
  transportation_type varchar(10),
  client_id integer,
  bill_date date,
  total_amt numeric(18,2),
  service_tax numeric(18,2),
  education_cess numeric(18,2),
  sh_educational_cess numeric(18,2),
  add_total numeric(18,2),
  sub_total numeric(18,2),
  net_amt numeric(18,2),
  remark varchar(500),
  createdby varchar(5),
  created_date timestamp,
  modifiedby varchar(5),
  modified_date timestamp,
  isactive smallint,
  pending_amt numeric(10,0),
  supply_state_id integer,
  PRIMARY KEY (bill_id)
);
COMMENT ON TABLE bill_detail IS 'Legacy table LGST_BillDetail';

-- LGST_BillDetail_09102017: 8447 rows
CREATE TABLE bill_detail_09102017 (
  bill_id integer,
  bill_number varchar(20),
  transportation_type varchar(10),
  client_id integer,
  bill_date date,
  total_amt numeric(18,2),
  service_tax numeric(18,2),
  education_cess numeric(18,2),
  sh_educational_cess numeric(18,2),
  add_total numeric(18,2),
  sub_total numeric(18,2),
  net_amt numeric(18,2),
  remark varchar(500),
  createdby varchar(5),
  created_date timestamp,
  modifiedby varchar(5),
  modified_date timestamp,
  isactive smallint,
  pending_amt numeric(10,0),
  supply_state_id integer
);
COMMENT ON TABLE bill_detail_09102017 IS 'Legacy table LGST_BillDetail_09102017';

-- LGST_BillDetail_Deleted: 459 rows
CREATE TABLE bill_detail_deleted (
  bill_id integer,
  bill_number varchar(20),
  transportation_type varchar(10),
  client_id integer,
  bill_date date,
  total_amt numeric(18,2),
  service_tax numeric(18,2),
  education_cess numeric(18,2),
  sh_educational_cess numeric(18,2),
  add_total numeric(18,2),
  sub_total numeric(18,2),
  net_amt numeric(18,2),
  remark varchar(500),
  createdby varchar(5),
  created_date timestamp,
  modifiedby varchar(5),
  modified_date timestamp,
  isactive smallint,
  pending_amt numeric(10,0),
  supply_state_id integer,
  deleted_by integer,
  deleted_date timestamp
);
COMMENT ON TABLE bill_detail_deleted IS 'Legacy table LGST_BillDetail_Deleted';

-- LGST_BillLR: 11384 rows
CREATE TABLE bill_lr (
  lr_bill_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  bill_id integer,
  lr_detail_id integer,
  total_freight numeric(18,2),
  service_tax numeric(18,2),
  education_cess numeric(18,2),
  sh_education_cess numeric(18,2),
  detn_wh numeric(18,2),
  detn_db numeric(18,2),
  toll_tax numeric(18,2),
  unload_charge numeric(18,2),
  multi_load_unload numeric(18,2),
  incentive numeric(18,2),
  freight_adj_add numeric(18,2),
  late_penalty numeric(18,2),
  damage numeric(18,2),
  freight_adj_sub numeric(18,2),
  createdby varchar(5),
  created_date timestamp,
  modifiedby varchar(5),
  modified_date timestamp,
  isactive smallint,
  add_total numeric(10,2),
  sub_total numeric(10,2),
  net_freight numeric(10,2),
  pending_freight numeric(10,2),
  reference_no varchar(50),
  delivery_date varchar(10),
  PRIMARY KEY (lr_bill_id)
);
COMMENT ON TABLE bill_lr IS 'Legacy table LGST_BillLR';

-- LGST_BillLR_Deleted: 1180 rows
CREATE TABLE bill_lr_deleted (
  lr_bill_id integer,
  bill_id integer,
  lr_detail_id integer,
  total_freight numeric(18,2),
  service_tax numeric(18,2),
  education_cess numeric(18,2),
  sh_education_cess numeric(18,2),
  detn_wh numeric(18,2),
  detn_db numeric(18,2),
  toll_tax numeric(18,2),
  unload_charge numeric(18,2),
  multi_load_unload numeric(18,2),
  incentive numeric(18,2),
  freight_adj_add numeric(18,2),
  late_penalty numeric(18,2),
  damage numeric(18,2),
  freight_adj_sub numeric(18,2),
  createdby varchar(5),
  created_date timestamp,
  modifiedby varchar(5),
  modified_date timestamp,
  isactive smallint,
  add_total numeric(10,2),
  sub_total numeric(10,2),
  net_freight numeric(10,2),
  pending_freight numeric(10,2),
  reference_no varchar(50),
  delivery_date varchar(10)
);
COMMENT ON TABLE bill_lr_deleted IS 'Legacy table LGST_BillLR_Deleted';

-- LGST_Branch: 22 rows
CREATE TABLE branch (
  branch_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  branch_code varchar(20),
  branch_short_code varchar(5),
  branch_name varchar(50),
  branch_address text,
  city_id integer,
  contact_name varchar(50),
  contact_phone varchar(15),
  branch_email varchar(50),
  godown_id integer,
  weekly_off_day varchar(3),
  working_hours numeric(15,2),
  company_id integer,
  allow_receipt varchar(3),
  allow_lr_create varchar(1),
  remarks_if_any varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  is_rail_head smallint,
  gst_no varchar(15),
  PRIMARY KEY (branch_id)
);
COMMENT ON TABLE branch IS 'Legacy table LGST_Branch';

-- LGST_City: 1013 rows
CREATE TABLE city (
  city_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  country_id integer,
  state_id integer,
  city_name varchar(50),
  description varchar(500),
  remarks_if_any varchar(200),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (city_id)
);
COMMENT ON TABLE city IS 'Legacy table LGST_City';

-- LGST_ClientPaymentReceivedEntry: 0 rows
CREATE TABLE client_payment_received_entry (
  client_payment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  bill_id integer,
  net_amt numeric(18,2),
  received_amt numeric(18,2),
  tds numeric(18,2),
  received_date date,
  pending_amt numeric(18,2),
  payment_mode varchar(20),
  bank_name varchar(100),
  acc_no_cheque_no varchar(20),
  cheque_date date,
  remark varchar(100),
  is_active smallint,
  created_date timestamp,
  createdby varchar(5),
  modified_date timestamp,
  modifiedby varchar(5),
  damage_amt numeric(10,0),
  rate_diff_amt numeric(10,0),
  PRIMARY KEY (client_payment_id)
);
COMMENT ON TABLE client_payment_received_entry IS 'Legacy table LGST_ClientPaymentReceivedEntry';

-- LGST_Company: 1 rows
CREATE TABLE company (
  company_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  company_name varchar(50),
  company_address text,
  city_id integer,
  state_id integer,
  country_id integer,
  establishment_year varchar(15),
  contact_phone varchar(15),
  company_pan varchar(15),
  company_tan varchar(15),
  company_main_logo varchar(200),
  company_inside_logo varchar(200),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (company_id)
);
COMMENT ON TABLE company IS 'Legacy table LGST_Company';

-- LGST_ComplaintCategory: 8 rows
CREATE TABLE complaint_category (
  category_id integer,
  category_name varchar(50),
  is_active smallint,
  created_date timestamp
);
COMMENT ON TABLE complaint_category IS 'Legacy table LGST_ComplaintCategory';

-- LGST_ComplaintReply: 0 rows
CREATE TABLE complaint_reply (
  reply_id integer,
  complaint_id integer,
  description text,
  attachment_url varchar(100),
  replied_by integer,
  replied_date timestamp,
  is_active smallint
);
COMMENT ON TABLE complaint_reply IS 'Legacy table LGST_ComplaintReply';

-- LGST_ComplaintSupport: 2 rows
CREATE TABLE complaint_support (
  complaint_id integer,
  ticket_no varchar(20),
  category_id integer,
  customer_id integer,
  description text,
  priority integer,
  attachment_url varchar(100),
  complaint_date timestamp,
  status integer,
  is_closed smallint,
  closed_by integer,
  closed_date timestamp
);
COMMENT ON TABLE complaint_support IS 'Legacy table LGST_ComplaintSupport';

-- LGST_Container: 3 rows
CREATE TABLE container (
  container_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  container_name varchar(100),
  description varchar(500),
  height numeric(25,2),
  width numeric(25,2),
  length numeric(25,2),
  weight numeric(25,2),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (container_id)
);
COMMENT ON TABLE container IS 'Legacy table LGST_Container';

-- LGST_Country: 21 rows
CREATE TABLE country (
  country_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  country_name varchar(50),
  description varchar(200),
  lr_booking_allowed smallint,
  remarks_if_any varchar(200),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (country_id)
);
COMMENT ON TABLE country IS 'Legacy table LGST_Country';

-- LGST_Courier: 17 rows
CREATE TABLE courier (
  courier_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  from_branch_id integer,
  to_branch_id integer,
  sent_date varchar(50),
  sent_time varchar(50),
  perticular varchar(50),
  received_date varchar(50),
  received_time varchar(50),
  docket_no varchar(50),
  courier_name varchar(100),
  courier_charges numeric(25,2),
  remark varchar(500),
  is_received smallint,
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  received_date_time timestamp,
  receivedby varchar(10),
  PRIMARY KEY (courier_id)
);
COMMENT ON TABLE courier IS 'Legacy table LGST_Courier';

-- LGST_Customer: 3089 rows
CREATE TABLE customer (
  customer_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_name varchar(100),
  customr_address text,
  short_name varchar(25),
  city_id integer,
  state_id integer,
  country_id integer,
  cst_no varchar(100),
  bst_no varchar(100),
  vat_no varchar(20),
  contact_name varchar(200),
  contact_phone varchar(15),
  credit_days integer,
  credit_limit numeric(18,2),
  customer_pan varchar(15),
  company_contact_person varchar(200),
  company_contact_mobile varchar(15),
  disallownew_lr_booking varchar(1),
  disallowed_branches varchar(500),
  intrest_ratefor_late_payment numeric(18,2),
  our_tds_deduction_rate numeric(18,2),
  primary_email varchar(50),
  secondary_email varchar(50),
  billing_email varchar(50),
  noti_email varchar(50),
  companywebsite varchar(200),
  contactemail varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  lr_credit_bal numeric(18,2),
  bill_format varchar(1),
  lr_format varchar(5),
  is_hide smallint,
  is_detention_bill smallint,
  is_bill_without_ack smallint,
  password varchar(500),
  gst_no varchar(15),
  PRIMARY KEY (customer_id)
);
COMMENT ON TABLE customer IS 'Legacy table LGST_Customer';

-- LGST_CustomerSuggestion: 1 rows
CREATE TABLE customer_suggestion (
  suggestion_id integer,
  customer_id integer,
  description text,
  posted_date timestamp,
  is_active smallint
);
COMMENT ON TABLE customer_suggestion IS 'Legacy table LGST_CustomerSuggestion';

-- LGST_Customer_CreditBal_History: 0 rows
CREATE TABLE customer_credit_bal_history (
  customer_credit_bal_history_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id integer,
  lr_detail_id integer,
  payment_id integer,
  amount numeric(10,2),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (customer_credit_bal_history_id)
);
COMMENT ON TABLE customer_credit_bal_history IS 'Legacy table LGST_Customer_CreditBal_History';

-- LGST_DCAcknowledgment: 4832 rows
CREATE TABLE dc_acknowledgment (
  dc_ack_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  d_challan_id integer,
  delivery_date varchar(10),
  delivery_time varchar(10),
  remark varchar(100),
  is_active smallint,
  createdby integer,
  created_date timestamp,
  modifiedby integer,
  modified_date timestamp,
  detention_days integer,
  detention_amt numeric(18,2),
  reporting_date varchar(10),
  reporting_time varchar(10),
  parking numeric(10,2),
  other_expenses numeric(10,2),
  supervisor_id integer,
  PRIMARY KEY (dc_ack_id)
);
COMMENT ON TABLE dc_acknowledgment IS 'Legacy table LGST_DCAcknowledgment';

-- LGST_DCAcknowledgmentClient: 3 rows
CREATE TABLE dc_acknowledgment_client (
  dc_ack_client_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  d_challan_id integer,
  reporting_date varchar(10),
  reporting_time varchar(10),
  unloading_date varchar(10),
  unloading_time varchar(10),
  detention_days integer,
  detention_amt numeric(10,2),
  damage_amt numeric(10,2),
  shortage_amt numeric(10,2),
  complaint_remark varchar(500),
  suggestion_remark varchar(500),
  is_active smallint,
  created_by integer,
  created_date timestamp,
  PRIMARY KEY (dc_ack_client_id)
);
COMMENT ON TABLE dc_acknowledgment_client IS 'Legacy table LGST_DCAcknowledgmentClient';

-- LGST_DCAcknowledgmentClientItems: 2 rows
CREATE TABLE dc_acknowledgment_client_items (
  dc_ack_client_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dc_ack_client_id integer,
  lr_detail_id integer,
  lr_item_id integer,
  total_qty integer,
  received_qty integer,
  damage_qty integer,
  PRIMARY KEY (dc_ack_client_item_id)
);
COMMENT ON TABLE dc_acknowledgment_client_items IS 'Legacy table LGST_DCAcknowledgmentClientItems';

-- LGST_DCAcknowledgmentCollection: 4622 rows
CREATE TABLE dc_acknowledgment_collection (
  dc_ack_collection_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  d_challan_id integer,
  delivery_date varchar(10),
  delivery_time varchar(10),
  collection_date varchar(10),
  reporting_date varchar(10),
  reporting_time varchar(10),
  transporter_id integer,
  detention_days integer,
  detention_amt numeric(10,2),
  damage_amt numeric(10,2),
  shortage_amt numeric(10,2),
  parking numeric(10,2),
  other_expenses numeric(10,2),
  labour_charge numeric(10,2),
  payment_mode varchar(20),
  remark varchar(100),
  dc_scan_image_url varchar(200),
  is_active smallint,
  createdby integer,
  created_date timestamp,
  modifiedby integer,
  modified_date timestamp,
  PRIMARY KEY (dc_ack_collection_id)
);
COMMENT ON TABLE dc_acknowledgment_collection IS 'Legacy table LGST_DCAcknowledgmentCollection';

-- LGST_DCAcknowledgmentCollectionItems: 7113 rows
CREATE TABLE dc_acknowledgment_collection_items (
  dc_ack_collection_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dc_ack_collection_id integer,
  lr_detail_id integer,
  lr_item_id integer,
  total_qty integer,
  received_qty integer,
  damage_qty integer,
  PRIMARY KEY (dc_ack_collection_item_id)
);
COMMENT ON TABLE dc_acknowledgment_collection_items IS 'Legacy table LGST_DCAcknowledgmentCollectionItems';

-- LGST_DCAcknowledgmentItems: 7580 rows
CREATE TABLE dc_acknowledgment_items (
  dc_ack_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dc_ack_id integer,
  lr_detail_id integer,
  lr_item_id integer,
  total_qty integer,
  received_qty integer,
  damage_qty integer,
  PRIMARY KEY (dc_ack_item_id)
);
COMMENT ON TABLE dc_acknowledgment_items IS 'Legacy table LGST_DCAcknowledgmentItems';

-- LGST_DCApproved: 4287 rows
CREATE TABLE dc_approved (
  dc_approve_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  transporter_id integer,
  d_challan_id integer,
  dc_ack_id integer,
  dc_ack_type varchar(20),
  freight numeric(10,2),
  advance numeric(10,2),
  detention_days integer,
  detention_amt numeric(10,2),
  labour_charge numeric(10,2),
  shortage_amt numeric(10,2),
  damage_amt numeric(10,2),
  parking_amt numeric(10,2),
  other_expenses numeric(10,2),
  freight_payable numeric(10,2),
  is_active smallint,
  createdby integer,
  created_date timestamp,
  PRIMARY KEY (dc_approve_id)
);
COMMENT ON TABLE dc_approved IS 'Legacy table LGST_DCApproved';

-- LGST_DCApproved_Deleted: 33 rows
CREATE TABLE dc_approved_deleted (
  dc_approve_id integer,
  transporter_id integer,
  d_challan_id integer,
  dc_ack_id integer,
  dc_ack_type varchar(20),
  freight numeric(10,2),
  advance numeric(10,2),
  detention_days integer,
  detention_amt numeric(10,2),
  labour_charge numeric(10,2),
  shortage_amt numeric(10,2),
  damage_amt numeric(10,2),
  parking_amt numeric(10,2),
  other_expenses numeric(10,2),
  freight_payable numeric(10,2),
  is_active smallint,
  createdby integer,
  created_date timestamp
);
COMMENT ON TABLE dc_approved_deleted IS 'Legacy table LGST_DCApproved_Deleted';

-- LGST_DCPaySlip: 376 rows
CREATE TABLE dc_pay_slip (
  dc_payslip_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dc_payslip_no varchar(15),
  transporter_id integer,
  total_freight_payable numeric(10,2),
  tds_amt numeric(10,2),
  net_payable_amt numeric(10,2),
  pending_amt numeric(10,2),
  date timestamp,
  remark varchar(500),
  is_active smallint,
  created_date timestamp,
  createdby integer,
  PRIMARY KEY (dc_payslip_id)
);
COMMENT ON TABLE dc_pay_slip IS 'Legacy table LGST_DCPaySlip';

-- LGST_DCPaymentEntry: 2610 rows
CREATE TABLE dc_payment_entry (
  dc_payment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dc_payslip_id integer,
  paid_amt numeric(10,2),
  paid_date timestamp,
  remark varchar(500),
  is_active smallint,
  created_by integer,
  created_date timestamp,
  PRIMARY KEY (dc_payment_id)
);
COMMENT ON TABLE dc_payment_entry IS 'Legacy table LGST_DCPaymentEntry';

-- LGST_DCPayslipChallan: 3381 rows
CREATE TABLE dc_payslip_challan (
  dc_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dc_payslip_id integer,
  dc_approve_id integer,
  created_by integer,
  created_date timestamp,
  d_challan_id integer,
  freight_payable numeric(10,2),
  pending_freight numeric(10,2),
  reference_no varchar(50),
  PRIMARY KEY (dc_id)
);
COMMENT ON TABLE dc_payslip_challan IS 'Legacy table LGST_DCPayslipChallan';

-- LGST_DCPayslipChallan_Deleted: 5 rows
CREATE TABLE dc_payslip_challan_deleted (
  dc_id integer,
  dc_payslip_id integer,
  dc_approve_id integer,
  created_by integer,
  created_date timestamp,
  d_challan_id integer,
  freight_payable numeric(10,2),
  pending_freight numeric(10,2),
  reference_no varchar(50)
);
COMMENT ON TABLE dc_payslip_challan_deleted IS 'Legacy table LGST_DCPayslipChallan_Deleted';

-- LGST_DC_WC: 302 rows
CREATE TABLE dc_wc (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vp_schedule_id integer,
  d_cper_hr numeric(18,2),
  dc_hrs_rk1 numeric(18,2),
  dc_hrs_rk2 numeric(18,2),
  dc_amt_rk1 numeric(18,2),
  dc_amt_rk2 numeric(18,2),
  total_dc_amount numeric(18,2),
  dc_letter_date varchar(10),
  is_wl_sent smallint,
  wl_send_date varchar(10),
  is_wl_approved smallint,
  wl_received_date varchar(10),
  dc_per numeric(18,2),
  waivel_amt numeric(18,2),
  dcw_received_date varchar(10),
  payment_mode varchar(20),
  bank_name varchar(100),
  cheque_acc_no varchar(20),
  cheque_date varchar(10),
  wherefare_charge numeric(18,2),
  created_date timestamp,
  created_by varchar(10),
  modified_date timestamp,
  modified_by varchar(10),
  is_active smallint,
  rk_id integer,
  PRIMARY KEY (id)
);
COMMENT ON TABLE dc_wc IS 'Legacy table LGST_DC_WC';

-- LGST_DGRNDetails: 6569 rows
CREATE TABLE dgrn_details (
  dgrn_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dgrn_no varchar(20),
  vp_schedule_id integer,
  wagon_id integer,
  vp_id integer,
  vp_no varchar(15),
  in_date varchar(10),
  in_time varchar(10),
  out_date varchar(10),
  out_time varchar(10),
  damage_by varchar(20),
  labour_charge numeric(18,2),
  labour_id integer,
  labour_count integer,
  supervisorid integer,
  remark varchar(100),
  createdby varchar(10),
  created_date timestamp,
  modifiedby varchar(10),
  modified_date varchar(10),
  is_active smallint,
  is_l_charge_paid smallint,
  payment_date timestamp,
  payment_no varchar(10),
  tds_per numeric(5,2),
  tds_amt numeric(10,0),
  payment_paid_by integer,
  PRIMARY KEY (dgrn_id)
);
COMMENT ON TABLE dgrn_details IS 'Legacy table LGST_DGRNDetails';

-- LGST_DGRNItems: 8908 rows
CREATE TABLE dgrn_items (
  dgrn_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dgrn_id integer,
  lr_detail_id integer,
  item_id integer,
  total_qty integer,
  received_qty integer,
  damage_qty integer,
  pending_qty integer,
  PRIMARY KEY (dgrn_item_id)
);
COMMENT ON TABLE dgrn_items IS 'Legacy table LGST_DGRNItems';

-- LGST_DGRNUploads: 0 rows
CREATE TABLE dgrn_uploads (
  fid integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dgrn_id integer,
  name varchar(50),
  caption varchar(50),
  path varchar(50),
  type varchar(10),
  size double precision,
  is_active smallint,
  createdby varchar(10),
  created_date timestamp,
  modifiedby varchar(10),
  modified_date timestamp,
  PRIMARY KEY (fid)
);
COMMENT ON TABLE dgrn_uploads IS 'Legacy table LGST_DGRNUploads';

-- LGST_DeliveryChallan: 7627 rows
CREATE TABLE delivery_challan (
  d_challan_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  d_challan_no varchar(20),
  vp_schedule_id integer,
  driver_name varchar(50),
  mobile_no varchar(10),
  loading_date varchar(10),
  loading_time varchar(10),
  advance numeric(18,2),
  payment_mode varchar(20),
  freight numeric(18,2),
  balance numeric(18,2),
  supervisor_id integer,
  createdby varchar(10),
  created_date timestamp,
  modifiedby varchar(10),
  modified_date timestamp,
  is_active smallint,
  transporter_id integer,
  truck_id integer,
  source_id integer,
  destination_id integer,
  delivery_address varchar(100),
  hamali numeric(18,2),
  remark varchar(200),
  is_self_delivery smallint,
  other_expenses numeric(10,0),
  other_deduction numeric(10,0),
  is_freight_paid numeric(10,0),
  payment_date timestamp,
  payment_no varchar(10),
  net_paid_amt numeric(10,0),
  payment_paid_by integer,
  td_sper numeric(5,2),
  tds_amt numeric(10,0),
  trip_id integer,
  is_connected smallint,
  truck_capacity varchar(50),
  weight varchar(50),
  adv_paid_transporter_id integer,
  PRIMARY KEY (d_challan_id)
);
COMMENT ON TABLE delivery_challan IS 'Legacy table LGST_DeliveryChallan';

-- LGST_DeliveryChallanComments: 1 rows
CREATE TABLE delivery_challan_comments (
  dc_comment_id integer,
  d_challan_id integer,
  comments varchar(500),
  created_by integer,
  created_date timestamp
);
COMMENT ON TABLE delivery_challan_comments IS 'Legacy table LGST_DeliveryChallanComments';

-- LGST_DeliveryChallanItems: 12238 rows
CREATE TABLE delivery_challan_items (
  d_challan_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  d_challan_id integer,
  dgrn_item_id integer,
  lr_detail_id integer,
  item_id integer,
  qty integer,
  pending_qty integer,
  vp_id integer,
  vp_no varchar(10),
  load_qty integer,
  old_d_challan_item_id integer,
  PRIMARY KEY (d_challan_item_id)
);
COMMENT ON TABLE delivery_challan_items IS 'Legacy table LGST_DeliveryChallanItems';

-- LGST_Department: 11 rows
CREATE TABLE department (
  department_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  department_name varchar(50),
  description text,
  branch_id integer,
  company_id integer,
  remarks_if_any varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (department_id)
);
COMMENT ON TABLE department IS 'Legacy table LGST_Department';

-- LGST_Designation: 27 rows
CREATE TABLE designation (
  designation_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  designation_name varchar(100),
  senior_mgmt_pos varchar(1),
  description text,
  exp_approval_limit numeric(10,2),
  powered_designation varchar(5),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (designation_id)
);
COMMENT ON TABLE designation IS 'Legacy table LGST_Designation';

-- LGST_Document: 9 rows
CREATE TABLE document (
  document_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  document_name varchar(50),
  document_type varchar(50),
  document_path varchar(500),
  remarks_if_any varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (document_id)
);
COMMENT ON TABLE document IS 'Legacy table LGST_Document';

-- LGST_Driver: 1240 rows
CREATE TABLE driver (
  driver_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  driver_name varchar(50),
  mobile_no varchar(15),
  alternate_mobile_no varchar(15),
  landline_permanent varchar(15),
  landline_correspondent varchar(15),
  pemanent_address varchar(500),
  pemanent_city_id integer,
  pemanent_state_id integer,
  pemanent_country_id integer,
  correspondence_address varchar(500),
  correspondence_city_id integer,
  correspondence_state_id integer,
  correspondence_country_id integer,
  is_on_leave varchar(1),
  salary numeric(10,5),
  license_no varchar(20),
  license_city_id integer,
  license_date varchar(8),
  expiry_date varchar(8),
  is_black_listed varchar(1),
  blood_group varchar(50),
  pan varchar(15),
  aadhar_card_number varchar(30),
  no_tds_apply_amount numeric(10,5),
  tds_rate numeric(10,5),
  birth_date varchar(15),
  anniversary_date varchar(15),
  particulars varchar(500),
  ref_person_name varchar(50),
  ref_contact_no varchar(15),
  driver_photo varchar(200),
  remarks_if_any varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  driver_type varchar(10),
  PRIMARY KEY (driver_id)
);
COMMENT ON TABLE driver IS 'Legacy table LGST_Driver';

-- LGST_Driver_Acc_History: 0 rows
CREATE TABLE driver_acc_history (
  acci_history_id integer NOT NULL,
  acci_driver_id integer,
  acci_date varchar(15),
  acci_details varchar(1000),
  acci_fir_recorded varchar(1),
  acci_created_by varchar(20),
  acci_created_date timestamp,
  acci_modified_by varchar(20),
  acci_modified_date timestamp,
  acci_is_active smallint,
  PRIMARY KEY (acci_history_id)
);
COMMENT ON TABLE driver_acc_history IS 'Legacy table LGST_Driver_Acc_History';

-- LGST_Driver_Leave_History: 0 rows
CREATE TABLE driver_leave_history (
  lv_leave_id integer NOT NULL,
  lv_driver_id integer,
  lv_from_date varchar(15),
  lv_to_date varchar(15),
  lv_reason varchar(500),
  lv_approved_by_employee_id integer,
  lv_created_by varchar(20),
  lv_created_date timestamp,
  lv_modified_by varchar(20),
  lv_modified_date timestamp,
  lv_is_active smallint,
  PRIMARY KEY (lv_leave_id)
);
COMMENT ON TABLE driver_leave_history IS 'Legacy table LGST_Driver_Leave_History';

-- LGST_Employee: 46 rows
CREATE TABLE employee (
  employee_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  salutation varchar(15),
  payroll_no varchar(20),
  first_name varchar(20),
  middle_name varchar(20),
  last_name varchar(20),
  perm_address text,
  perm_city_id integer,
  perm_state_id integer,
  perm_country_id integer,
  perm_pin varchar(50),
  corr_address text,
  corr_city_id integer,
  corr_state_id integer,
  corr_country_id integer,
  corr_pin varchar(50),
  gender varchar(1),
  department_id integer,
  designation_id integer,
  branch_id integer,
  dob varchar(8),
  marriatal_status smallint,
  joining_date varchar(8),
  is_black_listed varchar(1),
  blood_grp varchar(50),
  physical_appearance varchar(500),
  res_landline_number varchar(15),
  mobile_number varchar(15),
  facebook_id varchar(50),
  personal_email varchar(50),
  work_email varchar(50),
  aniversary_date varchar(8),
  photo varchar(200),
  total_exp integer,
  prev_employer varchar(100),
  promotion_record varchar(2000),
  company_id integer,
  caste varchar(3),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (employee_id)
);
COMMENT ON TABLE employee IS 'Legacy table LGST_Employee';

-- LGST_EmployeeDetails: 0 rows
CREATE TABLE employee_details (
  emp_details_id integer NOT NULL,
  employee_id integer,
  department_id integer,
  designation_id integer,
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (emp_details_id)
);
COMMENT ON TABLE employee_details IS 'Legacy table LGST_EmployeeDetails';

-- LGST_ExpenseType: 22 rows
CREATE TABLE expense_type (
  expense_type_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  expense_name varchar(200),
  expense_limit1 numeric(10,2),
  expense_limit2 numeric(10,2),
  expense_limit3 numeric(10,2),
  expense_limit4 numeric(10,2),
  expense_mode varchar(20),
  disallowed_branches varchar(500),
  expense_applicable varchar(500),
  expense_applicable_for varchar(500),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  ledger_name varchar(200),
  PRIMARY KEY (expense_type_id)
);
COMMENT ON TABLE expense_type IS 'Legacy table LGST_ExpenseType';

-- LGST_GRNDetails: 5421 rows
CREATE TABLE grn_details (
  gr_nid integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  grn_no varchar(50),
  lr_detail_id integer,
  gate_no integer,
  in_date varchar(10),
  in_time varchar(10),
  out_date varchar(10),
  out_time varchar(10),
  unloading_time integer,
  is_lr_copy boolean,
  lr_copy_rmk varchar(100),
  is_invoice_no boolean,
  invoice_no_rmk varchar(100),
  is_way_bill boolean,
  way_bill_rmk varchar(100),
  is_seal_no boolean,
  seal_no_rmk varchar(100),
  is_kata_receipt boolean,
  kata_receipt_rmk varchar(100),
  total_freight double precision,
  freight_per_mt double precision,
  detention_days integer,
  detention_amt double precision,
  gross_amt double precision,
  l_advance double precision,
  l_tds double precision,
  l_damage double precision,
  l_hamali double precision,
  l_stationary double precision,
  net_amt double precision,
  damageby varchar(20),
  labour_id integer,
  labour_count integer,
  labour_charge double precision,
  supervisorid integer,
  remark varchar(200),
  createdby varchar(10),
  created_date timestamp,
  modifiedby varchar(10),
  modified_date timestamp,
  is_active smallint,
  is_l_charge_paid smallint,
  payment_date timestamp,
  payment_no varchar(10),
  tds_per numeric(5,2),
  tds_amt numeric(10,0),
  branch_id integer,
  payment_paid_by integer,
  PRIMARY KEY (gr_nid)
);
COMMENT ON TABLE grn_details IS 'Legacy table LGST_GRNDetails';

-- LGST_GRNItems: 7336 rows
CREATE TABLE grn_items (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  gr_nid integer,
  lr_detail_id integer,
  lr_item_id integer,
  total_qty integer,
  received_qty integer,
  damage_qty integer,
  pending_qty integer,
  remark varchar(500),
  PRIMARY KEY (id)
);
COMMENT ON TABLE grn_items IS 'Legacy table LGST_GRNItems';

-- LGST_GRNUploads: 2 rows
CREATE TABLE grn_uploads (
  fid integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  gr_nid integer,
  name varchar(100),
  caption varchar(100),
  path varchar(300),
  type varchar(50),
  size double precision,
  PRIMARY KEY (fid)
);
COMMENT ON TABLE grn_uploads IS 'Legacy table LGST_GRNUploads';

-- LGST_Godowns: 3 rows
CREATE TABLE godowns (
  godown_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  godown_name varchar(200),
  godown_address varchar(500),
  city_id integer,
  state_id integer,
  country_id integer,
  contact_name varchar(200),
  contact_phone varchar(15),
  monthly_rent numeric(20,2),
  security_deposite numeric(20,2),
  agreement_date varchar(8),
  expiry_date varchar(8),
  godown_type integer,
  branch_id integer,
  length numeric(5,2),
  breadth numeric(5,2),
  width numeric(5,2),
  storage_capcity varchar(50),
  remarks_if_any varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  gate_no integer,
  PRIMARY KEY (godown_id)
);
COMMENT ON TABLE godowns IS 'Legacy table LGST_Godowns';

-- LGST_Goods: 496 rows
CREATE TABLE goods (
  goods_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  goods_name varchar(50),
  goods_description varchar(500),
  weight numeric(5,2),
  weight_unit_id integer,
  length numeric(5,2),
  width numeric(5,2),
  height numeric(5,2),
  storage_position varchar(50),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  good_category varchar(10),
  storage_layer varchar(50),
  is_stacking_allowed smallint,
  stack_allowed_category varchar(50),
  PRIMARY KEY (goods_id)
);
COMMENT ON TABLE goods IS 'Legacy table LGST_Goods';

-- LGST_Hamali: 12 rows
CREATE TABLE hamali (
  hamali_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  item_id integer,
  client_id integer,
  branch_id integer,
  unit_id integer,
  rate numeric(25,2),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  hamali_use varchar(50),
  PRIMARY KEY (hamali_id)
);
COMMENT ON TABLE hamali IS 'Legacy table LGST_Hamali';

-- LGST_InitiateOrder: 6243 rows
CREATE TABLE initiate_order (
  initiate_order_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  from_branch_id integer,
  from_branch_address varchar(500),
  to_branch_id integer,
  to_branch_address varchar(500),
  client_id integer,
  city_id integer,
  pickupdate varchar(15),
  instructions varchar(500),
  order_id varchar(50),
  order_status integer,
  company_id integer,
  person_name varchar(50),
  person_email varchar(50),
  person_phone_number varchar(20),
  billing_unit_id integer,
  order_by varchar(50),
  truck_quantity integer,
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  billing_amt numeric(25,2),
  remaining_truck_qty integer,
  is_lr_created boolean,
  is_order_completed smallint,
  PRIMARY KEY (initiate_order_id)
);
COMMENT ON TABLE initiate_order IS 'Legacy table LGST_InitiateOrder';

-- LGST_InitiateOrderItem: 9 rows
CREATE TABLE initiate_order_item (
  initiate_order_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  initiate_order_item_name integer,
  qty integer,
  unit integer,
  initiate_order_id integer,
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  remaining_qty integer,
  PRIMARY KEY (initiate_order_item_id)
);
COMMENT ON TABLE initiate_order_item IS 'Legacy table LGST_InitiateOrderItem';

-- LGST_InventoryCategory: 6 rows
CREATE TABLE inventory_category (
  category_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  category_name varchar(50),
  type varchar(50),
  description varchar(500),
  is_active smallint,
  created_by integer,
  created_date timestamp,
  modified_by integer,
  modified_date timestamp,
  PRIMARY KEY (category_id)
);
COMMENT ON TABLE inventory_category IS 'Legacy table LGST_InventoryCategory';

-- LGST_InventoryInward: 19 rows
CREATE TABLE inventory_inward (
  inward_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  po_id integer,
  bill_no varchar(20),
  net_amt integer,
  disscount_amt integer,
  payable_amt integer,
  pending_amt integer,
  remark varchar(500),
  is_active integer,
  created_by integer,
  created_date timestamp,
  modified_by integer,
  modified_date date,
  bill_date date,
  is_replacement smallint,
  replacement_id integer,
  supplier_id integer,
  PRIMARY KEY (inward_id)
);
COMMENT ON TABLE inventory_inward IS 'Legacy table LGST_InventoryInward';

-- LGST_InventoryInwardSpare: 63 rows
CREATE TABLE inventory_inward_spare (
  inward_spare_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inward_id integer,
  spare_id integer,
  batch_no varchar(50),
  qty numeric(10,2),
  rate numeric(10,2),
  is_warrenty smallint,
  is_guaranty smallint,
  warrenty_expiry_date varchar(10),
  guaranty_expiry_date varchar(10),
  is_active smallint,
  PRIMARY KEY (inward_spare_id)
);
COMMENT ON TABLE inventory_inward_spare IS 'Legacy table LGST_InventoryInwardSpare';

-- LGST_InventoryJobCard: 20 rows
CREATE TABLE inventory_job_card (
  jobcard_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  jobcard_number varchar(15),
  truck_id integer,
  driver_id integer,
  type varchar(10),
  in_date date,
  in_time varchar(10),
  out_date date,
  out_time varchar(10),
  opening_km integer,
  net_amt integer,
  is_approved smallint,
  is_finalised smallint,
  approved_by integer,
  remark varchar(500),
  finalised_by integer,
  is_active smallint,
  created_by integer,
  created_date timestamp,
  modified_by integer,
  modified_date timestamp,
  finalise_date timestamp,
  PRIMARY KEY (jobcard_id)
);
COMMENT ON TABLE inventory_job_card IS 'Legacy table LGST_InventoryJobCard';

-- LGST_InventoryJobCardItem: 64 rows
CREATE TABLE inventory_job_card_item (
  jobcard_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  jobcard_id integer,
  spare_id integer,
  stock_id integer,
  supplier_id integer,
  rate numeric(10,2),
  qty numeric(10,2),
  mechanic_id integer,
  description varchar(500),
  service_bill_id integer,
  PRIMARY KEY (jobcard_item_id)
);
COMMENT ON TABLE inventory_job_card_item IS 'Legacy table LGST_InventoryJobCardItem';

-- LGST_InventoryPOSpare: 88 rows
CREATE TABLE inventory_po_spare (
  po_spare_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  po_id integer,
  spare_id integer,
  qty numeric(10,2),
  rate numeric(10,2),
  PRIMARY KEY (po_spare_id)
);
COMMENT ON TABLE inventory_po_spare IS 'Legacy table LGST_InventoryPOSpare';

-- LGST_InventoryPaymentEntry: 0 rows
CREATE TABLE inventory_payment_entry (
  po_payment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inward_id integer,
  paid_amt integer,
  tds integer,
  paid_date date,
  is_active smallint,
  created_by integer,
  created_date timestamp,
  disscount_amt integer,
  PRIMARY KEY (po_payment_id)
);
COMMENT ON TABLE inventory_payment_entry IS 'Legacy table LGST_InventoryPaymentEntry';

-- LGST_InventoryPurchaseOrder: 25 rows
CREATE TABLE inventory_purchase_order (
  po_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  po_number varchar(15),
  supplier_id integer,
  date date,
  remark varchar(500),
  net_amt integer,
  is_approved smallint,
  approved_by integer,
  is_active smallint,
  created_by integer,
  created_date timestamp,
  modified_by integer,
  modified_date timestamp,
  PRIMARY KEY (po_id)
);
COMMENT ON TABLE inventory_purchase_order IS 'Legacy table LGST_InventoryPurchaseOrder';

-- LGST_InventoryReplacement: 0 rows
CREATE TABLE inventory_replacement (
  replacement_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  replacement_no varchar(15),
  supplier_id integer,
  is_payable smallint,
  date date,
  remark varchar(500),
  is_active smallint,
  created_by integer,
  created_date timestamp,
  modified_by integer,
  modified_date timestamp,
  PRIMARY KEY (replacement_id)
);
COMMENT ON TABLE inventory_replacement IS 'Legacy table LGST_InventoryReplacement';

-- LGST_InventoryReplacementItems: 0 rows
CREATE TABLE inventory_replacement_items (
  replacement_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  replacement_id integer,
  inward_id integer,
  inward_spare_id integer,
  spare_id integer,
  qty numeric(10,2),
  PRIMARY KEY (replacement_item_id)
);
COMMENT ON TABLE inventory_replacement_items IS 'Legacy table LGST_InventoryReplacementItems';

-- LGST_InventoryScrap: 0 rows
CREATE TABLE inventory_scrap (
  scrap_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  jobcard_id integer,
  spare_id integer,
  stock_id integer,
  PRIMARY KEY (scrap_id)
);
COMMENT ON TABLE inventory_scrap IS 'Legacy table LGST_InventoryScrap';

-- LGST_InventoryServiceBill: 0 rows
CREATE TABLE inventory_service_bill (
  service_bill_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  supplier_id integer,
  bill_number varchar(20),
  bill_date date,
  total_amt integer,
  disscount_amt integer,
  net_amt integer,
  pending_amt integer,
  is_active smallint,
  created_by integer,
  created_date timestamp,
  PRIMARY KEY (service_bill_id)
);
COMMENT ON TABLE inventory_service_bill IS 'Legacy table LGST_InventoryServiceBill';

-- LGST_InventoryServicePayment: 0 rows
CREATE TABLE inventory_service_payment (
  service_payment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  service_bill_id integer,
  paid_amt integer,
  tds integer,
  paid_date date,
  is_active smallint,
  created_by integer,
  created_date timestamp,
  disscount_amt integer,
  PRIMARY KEY (service_payment_id)
);
COMMENT ON TABLE inventory_service_payment IS 'Legacy table LGST_InventoryServicePayment';

-- LGST_InventorySpare: 131 rows
CREATE TABLE inventory_spare (
  spare_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  spare_name varchar(50),
  category_id integer,
  min_stock_count integer,
  rate numeric(10,2),
  description varchar(500),
  type varchar(10),
  is_active smallint,
  created_by integer,
  created_date timestamp,
  modified_by integer,
  modified_date timestamp,
  is_recyclable smallint,
  is_batch_no smallint,
  unit_id integer,
  PRIMARY KEY (spare_id)
);
COMMENT ON TABLE inventory_spare IS 'Legacy table LGST_InventorySpare';

-- LGST_InventoryStock: 63 rows
CREATE TABLE inventory_stock (
  stock_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inward_id integer,
  inward_spare_id integer,
  spare_id integer,
  qty numeric(10,2),
  rate numeric(10,2),
  is_new smallint,
  PRIMARY KEY (stock_id)
);
COMMENT ON TABLE inventory_stock IS 'Legacy table LGST_InventoryStock';

-- LGST_InventorySupplier: 18 rows
CREATE TABLE inventory_supplier (
  supplier_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  supplier_name varchar(50),
  supplier_type varchar(20),
  shop_name varchar(50),
  city_id integer,
  address varchar(100),
  contact_no varchar(15),
  contact_person varchar(50),
  mobile_no varchar(10),
  email_id varchar(50),
  vat_tinno varchar(20),
  pan_no varchar(15),
  is_active smallint,
  created_by integer,
  created_date timestamp,
  modified_by integer,
  modified_date timestamp,
  PRIMARY KEY (supplier_id)
);
COMMENT ON TABLE inventory_supplier IS 'Legacy table LGST_InventorySupplier';

-- LGST_InventoryTruckMaintenance: 3145 rows
CREATE TABLE inventory_truck_maintenance (
  maintenance_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  jobcard_id integer,
  truck_id integer,
  driver_id integer,
  posting_date date,
  opening_km integer,
  preparedby varchar(100),
  checkedby varchar(100),
  authorisedby varchar(100),
  remark varchar(500),
  is_active smallint,
  createdby integer,
  created_date timestamp,
  modifiedby integer,
  modified_date timestamp,
  PRIMARY KEY (maintenance_id)
);
COMMENT ON TABLE inventory_truck_maintenance IS 'Legacy table LGST_InventoryTruckMaintenance';

-- LGST_InventoryTruckMaintenanceCheckList: 69234 rows
CREATE TABLE inventory_truck_maintenance_check_list (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  maintenance_id integer,
  particular integer,
  is_checked smallint,
  current_status varchar(50),
  regarding_action varchar(50),
  remark varchar(100),
  PRIMARY KEY (id)
);
COMMENT ON TABLE inventory_truck_maintenance_check_list IS 'Legacy table LGST_InventoryTruckMaintenanceCheckList';

-- LGST_Itemold: 4 rows
CREATE TABLE itemold (
  item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  item_name varchar(50),
  party_name integer,
  item_description text,
  item_length double precision,
  item_width double precision,
  item_height double precision,
  item_weight double precision,
  item_type_id integer,
  item_packing varchar(50),
  item_storage_position varchar(1),
  remarks_if_any varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (item_id)
);
COMMENT ON TABLE itemold IS 'Legacy table LGST_Itemold';

-- LGST_LRAcknowledgment: 9104 rows
CREATE TABLE lr_acknowledgment (
  lr_ackid integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lr_detail_id integer,
  received_date varchar(10),
  received_time varchar(10),
  docket_no varchar(50),
  courier_name varchar(500),
  courier_charge double precision,
  detention_days integer,
  detention_amt double precision,
  damage_amt numeric(18,2),
  remark varchar(500),
  createdby varchar(50),
  created_date timestamp,
  is_active smallint,
  modified_by varchar(10),
  modified_date timestamp,
  PRIMARY KEY (lr_ackid)
);
COMMENT ON TABLE lr_acknowledgment IS 'Legacy table LGST_LRAcknowledgment';

-- LGST_LRAcknowledgmentItems: 10448 rows
CREATE TABLE lr_acknowledgment_items (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lr_ackid integer,
  lr_detail_id integer,
  lr_item_id integer,
  total_qty integer,
  received_qty integer,
  damage_qty integer,
  PRIMARY KEY (id)
);
COMMENT ON TABLE lr_acknowledgment_items IS 'Legacy table LGST_LRAcknowledgmentItems';

-- LGST_LRAcknowledgmentUploads: 1 rows
CREATE TABLE lr_acknowledgment_uploads (
  fid integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lr_ackid integer,
  name varchar(100),
  caption varchar(100),
  path varchar(300),
  type varchar(50),
  size double precision,
  PRIMARY KEY (fid)
);
COMMENT ON TABLE lr_acknowledgment_uploads IS 'Legacy table LGST_LRAcknowledgmentUploads';

-- LGST_LRCharges: 2 rows
CREATE TABLE lr_charges (
  lr_charges_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lr_detail_id integer,
  total_amt_a numeric(25,2),
  service_tax numeric(25,2),
  education_coss numeric(25,2),
  high_edu numeric(25,2),
  total_service_tax_b numeric(25,2),
  detection_inwarehouse numeric(25,2),
  detection_for_direct_bill numeric(25,2),
  total_tax numeric(25,2),
  unloading_charges numeric(25,2),
  multipoint_load numeric(25,2),
  incentive numeric(25,2),
  freight_adjustment_add numeric(25,2),
  total_c numeric(25,2),
  late_penaulty numeric(25,2),
  damage numeric(25,2),
  freight_adjustment_sub numeric(25,2),
  total_d numeric(25,2),
  total_bill_amount numeric(25,2),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (lr_charges_id)
);
COMMENT ON TABLE lr_charges IS 'Legacy table LGST_LRCharges';

-- LGST_LRCheckList: 3 rows
CREATE TABLE lr_check_list (
  lr_check_list_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lr_detail_id integer,
  islr_copy smallint,
  is_invoice smallint,
  is_way_to_bill smallint,
  is_seal_no smallint,
  is_kata_receipt smallint,
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  detention_days integer,
  detention_value numeric(25,2),
  trans_port_payment_entry_id integer,
  PRIMARY KEY (lr_check_list_id)
);
COMMENT ON TABLE lr_check_list IS 'Legacy table LGST_LRCheckList';

-- LGST_LRDelivered: 5946 rows
CREATE TABLE lr_delivered (
  lr_delivered_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lr_detail_id integer,
  delivery_date varchar(50),
  delivery_time varchar(10),
  remark varchar(500),
  unloading_charges numeric(25,2),
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (lr_delivered_id)
);
COMMENT ON TABLE lr_delivered IS 'Legacy table LGST_LRDelivered';

-- LGST_LRDetail: 12388 rows
CREATE TABLE lr_detail (
  lr_detail_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lr_number varchar(50),
  order_by integer,
  place_date varchar(15),
  place_time varchar(10),
  due_date varchar(15),
  due_time varchar(10),
  consigner_id integer,
  consigner_address varchar(500),
  consignee_id integer,
  consignee_address varchar(500),
  total_pakages integer,
  total_weight numeric(18,2),
  godown_id integer,
  invoices varchar(300),
  total_freight numeric(25,2),
  detention_amt numeric(10,2),
  total_advance_paid numeric(10,2),
  total_expenses numeric(10,2),
  net_freight numeric(10,2),
  order_id varchar(50),
  initiate_order_id integer,
  order_status integer,
  truck_id integer,
  transport_by varchar(1),
  indurance smallint,
  indurance_no varchar(50),
  indurance_comp_name varchar(50),
  indurance_start_date varchar(15),
  indurance_end_date varchar(15),
  transpor_type varchar(50),
  weight_unit_id integer,
  billing_unit_id integer,
  company_id integer,
  destination_party_name varchar(50),
  delivery_at_address varchar(500),
  order_preclosed varchar(1),
  goods_total_value varchar(15),
  risk_type varchar(1),
  delivery_type varchar(50),
  servicetax_paymentmode varchar(50),
  seal_number varchar(50),
  paymentmode varchar(50),
  branch_id integer,
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  priority varchar(50),
  opeing_kmoftruck numeric(20,2),
  driver_id integer,
  trip_id integer,
  billing_amt numeric(25,2),
  to_branch integer,
  pickup_loc integer,
  is_freight_return smallint,
  client_freight numeric(25,2),
  client_hamali numeric(25,2),
  client_advance numeric(25,2),
  client_tds numeric(25,2),
  client_commision numeric(25,2),
  client_net_balance_freight numeric(25,2),
  client_total_freight_advance numeric(25,2),
  challan_no varchar(50),
  lr_date timestamp,
  is_grn boolean,
  is_final_lr smallint,
  std_time numeric(18,2),
  is_via_ho smallint,
  rp_number varchar(500),
  remark varchar(300),
  chargable_weight numeric(10,2),
  is_multi_lr smallint,
  freight_updated_by integer,
  freight_updated_date timestamp,
  ip_address varchar(20),
  to_rail_head integer,
  is_urgent smallint,
  is_to_pay_tax smallint,
  PRIMARY KEY (lr_detail_id)
);
COMMENT ON TABLE lr_detail IS 'Legacy table LGST_LRDetail';

-- LGST_LRDetails_Status_History: 22117 rows
CREATE TABLE lr_details_status_history (
  lr_detail_history_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lr_detail_id integer,
  order_status integer,
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (lr_detail_history_id)
);
COMMENT ON TABLE lr_details_status_history IS 'Legacy table LGST_LRDetails_Status_History';

-- LGST_LRDetails_Status_History_20140929: 587 rows
CREATE TABLE lr_details_status_history_20140929 (
  lr_detail_history_id integer,
  lr_detail_id integer,
  order_status integer,
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint
);
COMMENT ON TABLE lr_details_status_history_20140929 IS 'Legacy table LGST_LRDetails_Status_History_20140929';

-- LGST_LRItem: 14302 rows
CREATE TABLE lr_item (
  lr_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lr_item_name integer,
  qty integer,
  unit integer,
  lr_detail_id integer,
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  shortage_qty integer,
  damage_qty integer,
  remark varchar(200),
  initiate_order_item_id integer,
  pendingqty integer,
  PRIMARY KEY (lr_item_id)
);
COMMENT ON TABLE lr_item IS 'Legacy table LGST_LRItem';

-- LGST_LRTransport: 0 rows
CREATE TABLE lr_transport (
  lr_transport_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  transport_name varchar(50),
  driver_name varchar(50),
  driver_ph_number varchar(15),
  permit_no varchar(50),
  lr_detail_id integer,
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (lr_transport_id)
);
COMMENT ON TABLE lr_transport IS 'Legacy table LGST_LRTransport';

-- LGST_Labour: 98 rows
CREATE TABLE labour (
  labour_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  labour_name varchar(20),
  labour_address text,
  city_id integer,
  contact_name varchar(50),
  contact_phone varchar(15),
  mobile_pbone varchar(15),
  ref_person_name varchar(50),
  ref_contact_no varchar(15),
  photo varchar(200),
  start_date varchar(15),
  pan varchar(15),
  tds_rate numeric(10,2),
  no_tds_apply_amount numeric(10,0),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  type varchar(50),
  branch_id integer,
  PRIMARY KEY (labour_id)
);
COMMENT ON TABLE labour IS 'Legacy table LGST_Labour';

-- LGST_LedgerMaster: 3481 rows
CREATE TABLE ledger_master (
  ledger_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ledger_name varchar(100),
  ledger_type varchar(50),
  company_id integer,
  branch_id integer,
  is_active smallint,
  created_date timestamp,
  PRIMARY KEY (ledger_id)
);
COMMENT ON TABLE ledger_master IS 'Legacy table LGST_LedgerMaster';

-- LGST_ListValues: 156 rows
CREATE TABLE list_values (
  list_value_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  type varchar(50),
  text varchar(50),
  value varchar(50),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (list_value_id)
);
COMMENT ON TABLE list_values IS 'Legacy table LGST_ListValues';

-- LGST_LogProcess: 16246 rows
CREATE TABLE log_process (
  log_process_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  log_slip_number varchar(50),
  truck_id integer,
  driver_id integer,
  opening_km numeric(25,2),
  closing_km numeric(25,2),
  start_date timestamp,
  end_date timestamp,
  previous_diesel_qty integer,
  diesel_rate numeric(10,2),
  is_process_completed integer,
  is_log_generated integer,
  remark varchar(500),
  createdby varchar(10),
  created_date timestamp,
  logslip_date timestamp,
  modified_by varchar(5),
  modified_date timestamp,
  PRIMARY KEY (log_process_id)
);
COMMENT ON TABLE log_process IS 'Legacy table LGST_LogProcess';

-- LGST_MR_RR: 652 rows
CREATE TABLE mr_rr (
  mrrr_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vp_schedule_id integer,
  from_date varchar(15),
  to_date varchar(15),
  wagon_count integer,
  rake_type varchar(50),
  created_date timestamp,
  created_by varchar(10),
  modified_date timestamp,
  modified_by varchar(10),
  is_active smallint,
  PRIMARY KEY (mrrr_id)
);
COMMENT ON TABLE mr_rr IS 'Legacy table LGST_MR_RR';

-- LGST_MR_RRWagons: 7038 rows
CREATE TABLE mr_rr_wagons (
  mr_wagon_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  mrrr_id integer,
  vp_schedule_id integer,
  wagon_type varchar(10),
  wagon_id integer,
  vp_id integer,
  vp_no varchar(20),
  mr_rr_no varchar(20),
  created_date timestamp,
  created_by varchar(10),
  modified_date timestamp,
  modified_by varchar(10),
  is_active smallint,
  seal_no varchar(100),
  railway_freight numeric(10,2),
  PRIMARY KEY (mr_wagon_id)
);
COMMENT ON TABLE mr_rr_wagons IS 'Legacy table LGST_MR_RRWagons';

-- LGST_Menu: 176 rows
CREATE TABLE menu (
  menu_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  menu_name varchar(50),
  url varchar(500),
  parent_menu_id integer,
  icon_class_name varchar(50),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  menu_order_id numeric(5,2),
  tooltip varchar(100),
  PRIMARY KEY (menu_id)
);
COMMENT ON TABLE menu IS 'Legacy table LGST_Menu';

-- LGST_MenuPerRole: 4969 rows
CREATE TABLE menu_per_role (
  menu_per_role_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  menu_id integer,
  role_id integer,
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  user_id integer,
  PRIMARY KEY (menu_per_role_id)
);
COMMENT ON TABLE menu_per_role IS 'Legacy table LGST_MenuPerRole';

-- LGST_Message: 3 rows
CREATE TABLE message (
  message_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code varchar(50),
  text varchar(500),
  description varchar(50),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (message_id)
);
COMMENT ON TABLE message IS 'Legacy table LGST_Message';

-- LGST_MonthlyFixedExpenses: 6805 rows
CREATE TABLE monthly_fixed_expenses (
  fixed_exp_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  truck_id integer,
  tax numeric(10,0),
  salary numeric(10,0),
  permit numeric(10,0),
  emi numeric(10,0),
  insurance numeric(10,0),
  month integer,
  year integer,
  fitness integer,
  PRIMARY KEY (fixed_exp_id)
);
COMMENT ON TABLE monthly_fixed_expenses IS 'Legacy table LGST_MonthlyFixedExpenses';

-- LGST_MonthlyVariableExpenses: 19023 rows
CREATE TABLE monthly_variable_expenses (
  monthly_variable_expenses_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  date varchar(8),
  vehicle_no integer,
  expense_type varchar(50),
  expenses_amt numeric(25,2),
  reponsible_person varchar(100),
  description varchar(500),
  modified_by varchar(20),
  created_date timestamp,
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (monthly_variable_expenses_id)
);
COMMENT ON TABLE monthly_variable_expenses IS 'Legacy table LGST_MonthlyVariableExpenses';

-- LGST_OrderExpense: 152662 rows
CREATE TABLE order_expense (
  order_expense_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  expense_paid_by_id integer,
  expense_type_id integer,
  amount numeric(10,2),
  lr_detail_id integer,
  trip_id integer,
  payment_mode varchar(50),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  city_id integer,
  pump_id integer,
  rate numeric(25,2),
  qty numeric(10,2),
  truck_id integer,
  logprocess_id integer,
  PRIMARY KEY (order_expense_id)
);
COMMENT ON TABLE order_expense IS 'Legacy table LGST_OrderExpense';

-- LGST_OwnVehicleRateContract: 21 rows
CREATE TABLE own_vehicle_rate_contract (
  own_vehicle_rate_contract_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id integer,
  from_date varchar(8),
  to_date varchar(8),
  remark varchar(500),
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (own_vehicle_rate_contract_id)
);
COMMENT ON TABLE own_vehicle_rate_contract IS 'Legacy table LGST_OwnVehicleRateContract';

-- LGST_OwnVehicleRateContract_History: 79 rows
CREATE TABLE own_vehicle_rate_contract_history (
  own_vehicle_rate_contract_history_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  own_vehicle_rate_contract_id integer,
  customer_id integer,
  from_date varchar(8),
  to_date varchar(8),
  remark varchar(500),
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (own_vehicle_rate_contract_history_id)
);
COMMENT ON TABLE own_vehicle_rate_contract_history IS 'Legacy table LGST_OwnVehicleRateContract_History';

-- LGST_OwnVehicleRateMatrix: 94 rows
CREATE TABLE own_vehicle_rate_matrix (
  own_vehicle_rate_matrix_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  own_vehicle_rate_contract_id integer,
  source_id integer,
  destination_id integer,
  truck_type varchar(50),
  tyres varchar(50),
  rate numeric(18,0),
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (own_vehicle_rate_matrix_id)
);
COMMENT ON TABLE own_vehicle_rate_matrix IS 'Legacy table LGST_OwnVehicleRateMatrix';

-- LGST_OwnVehicleRateMatrix_History: 245 rows
CREATE TABLE own_vehicle_rate_matrix_history (
  own_vehicle_rate_matrix_history_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  own_vehicle_rate_matrix_id integer,
  own_vehicle_rate_contract_id integer,
  source_id integer,
  destination_id integer,
  truck_type varchar(50),
  tyres varchar(50),
  rate numeric(25,2),
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (own_vehicle_rate_matrix_history_id)
);
COMMENT ON TABLE own_vehicle_rate_matrix_history IS 'Legacy table LGST_OwnVehicleRateMatrix_History';

-- LGST_Payment: 4 rows
CREATE TABLE payment (
  payment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id integer,
  lr_number varchar(50),
  amount numeric(10,2),
  payment_mode varchar(50),
  payment_as varchar(50),
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (payment_id)
);
COMMENT ON TABLE payment IS 'Legacy table LGST_Payment';

-- LGST_Pump: 931 rows
CREATE TABLE pump (
  pump_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pump_name varchar(50),
  pump_address text,
  city_id integer,
  state_id integer,
  country_id integer,
  contact_name varchar(50),
  contact_phone varchar(15),
  rate_last_updated varchar(15),
  current_diesel_rate numeric(20,2),
  vat_tin varchar(20),
  pan varchar(15),
  credit_limit numeric(20,2),
  bank_name varchar(50),
  account_name varchar(50),
  branch_ifsc_code varchar(15),
  is_black_listed varchar(1),
  pump_fuel_id integer,
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (pump_id)
);
COMMENT ON TABLE pump IS 'Legacy table LGST_Pump';

-- LGST_Pump_Fuel_History: 1016 rows
CREATE TABLE pump_fuel_history (
  pump_fuel_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pump_id integer,
  rate numeric(10,2),
  date_updated varchar(15),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (pump_fuel_id)
);
COMMENT ON TABLE pump_fuel_history IS 'Legacy table LGST_Pump_Fuel_History';

-- LGST_RailwayFreight: 87 rows
CREATE TABLE railway_freight (
  railway_freight_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  wagon_id integer,
  source_id integer,
  destination_id integer,
  rate_amt numeric(18,0),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (railway_freight_id)
);
COMMENT ON TABLE railway_freight IS 'Legacy table LGST_RailwayFreight';

-- LGST_RakeDetail: 553 rows
CREATE TABLE rake_detail (
  rk_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vp_schedule_id integer,
  arrival_date varchar(15),
  arrival_time varchar(10),
  dispatch_date varchar(15),
  dispatch_time varchar(10),
  rk_place_date1 varchar(15),
  rk_place_time1 varchar(10),
  rk_place_date2 varchar(15),
  rk_place_time2 varchar(10),
  rk_removal_date1 varchar(15),
  rk_removal_time1 varchar(10),
  rk_removal_date2 varchar(15),
  rk_removal_time2 varchar(10),
  dc_hrs_rk1 integer,
  dc_hrs_rk2 integer,
  reach_date varchar(15),
  reach_time varchar(10),
  unload_date varchar(15),
  unload_time varchar(10),
  is_completed smallint,
  created_date timestamp,
  created_by varchar(10),
  modified_date timestamp,
  modified_by varchar(10),
  is_active smallint,
  PRIMARY KEY (rk_id)
);
COMMENT ON TABLE rake_detail IS 'Legacy table LGST_RakeDetail';

-- LGST_RakeStatus: 1 rows
CREATE TABLE rake_status (
  rake_status_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vp_schedule_id integer,
  status_remark varchar(50),
  created_date timestamp,
  createdby integer,
  PRIMARY KEY (rake_status_id)
);
COMMENT ON TABLE rake_status IS 'Legacy table LGST_RakeStatus';

-- LGST_RateContract: 532 rows
CREATE TABLE rate_contract (
  rate_contract_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id integer,
  from_date varchar(8),
  to_date varchar(8),
  remark varchar(500),
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (rate_contract_id)
);
COMMENT ON TABLE rate_contract IS 'Legacy table LGST_RateContract';

-- LGST_RateContract_History: 2971 rows
CREATE TABLE rate_contract_history (
  rate_contract_history_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  rate_contract_id integer,
  customer_id integer,
  from_date varchar(8),
  to_date varchar(8),
  remark varchar(500),
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (rate_contract_history_id)
);
COMMENT ON TABLE rate_contract_history IS 'Legacy table LGST_RateContract_History';

-- LGST_RateMatrix: 5005 rows
CREATE TABLE rate_matrix (
  rate_matrix_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  rate_contract_id integer,
  source_id integer,
  destination_id integer,
  rate_amt numeric(18,2),
  mode varchar(50),
  goods_id integer,
  unit_id integer,
  rate_number integer,
  truck_capacity varchar(50),
  standared_time numeric(5,0),
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (rate_matrix_id)
);
COMMENT ON TABLE rate_matrix IS 'Legacy table LGST_RateMatrix';

-- LGST_RateMatrixSlab: 719 rows
CREATE TABLE rate_matrix_slab (
  rate_slab_id integer,
  rate_matrix_id integer,
  range_from numeric(5,2),
  range_to numeric(5,2),
  rate_amt numeric(10,0),
  is_pro_data smallint
);
COMMENT ON TABLE rate_matrix_slab IS 'Legacy table LGST_RateMatrixSlab';

-- LGST_RateMatrix_History: 38939 rows
CREATE TABLE rate_matrix_history (
  rate_matrix_history_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  rate_matrix_id integer,
  rate_contract_id integer,
  source_id integer,
  destination_id integer,
  rate_amt numeric(25,2),
  mode varchar(50),
  goods_id integer,
  unit_id integer,
  rate_number integer,
  truck_capacity varchar(50),
  created_by varchar(50),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (rate_matrix_history_id)
);
COMMENT ON TABLE rate_matrix_history IS 'Legacy table LGST_RateMatrix_History';

-- LGST_Roles: 11 rows
CREATE TABLE roles (
  role_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  role_u_id integer,
  role_name varchar(50),
  description varchar(500),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (role_id)
);
COMMENT ON TABLE roles IS 'Legacy table LGST_Roles';

-- LGST_SearchColumn: 137 rows
CREATE TABLE search_column (
  search_column_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  search_column_key varchar(50),
  search_column_text varchar(50),
  search_column_value varchar(200),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (search_column_id)
);
COMMENT ON TABLE search_column IS 'Legacy table LGST_SearchColumn';

-- LGST_State: 41 rows
CREATE TABLE state (
  state_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  state varchar(50),
  description varchar(200),
  country_id integer,
  remarks_if_any varchar(200),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (state_id)
);
COMMENT ON TABLE state IS 'Legacy table LGST_State';

-- LGST_Transport: 1536 rows
CREATE TABLE transport (
  transport_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  transport_name varchar(200),
  transport_add varchar(500),
  city_id integer,
  state_id integer,
  country_id integer,
  contact_name varchar(200),
  contract_phone varchar(15),
  pan varchar(15),
  sev_taxnumber varchar(15),
  tds_rate numeric(25,2),
  no_tds_apply_amount numeric(25,2),
  primary_mobile_no varchar(15),
  sec_mobile_no varchar(15),
  pa_nscanimage varchar(200),
  is_black_listed smallint,
  is_associate smallint,
  paymentmode varchar(50),
  available_locations varchar(500),
  remarks_if_any varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  payable1 varchar(50),
  payable2 varchar(50),
  payable3 varchar(50),
  payable4 varchar(50),
  declaration_url varchar(200),
  PRIMARY KEY (transport_id)
);
COMMENT ON TABLE transport IS 'Legacy table LGST_Transport';

-- LGST_TransporterPaymentDetail: 904 rows
CREATE TABLE transporter_payment_detail (
  payment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  payment_slip_no varchar(50),
  transporter_id integer,
  total_freight numeric(18,2),
  total_detention numeric(18,2),
  total_advance numeric(18,2),
  total_hamali numeric(18,2),
  total_commision numeric(18,2),
  total_tds numeric(18,2),
  total_damage numeric(18,2),
  total_stationary numeric(18,2),
  payble_amt numeric(18,2),
  isactive smallint,
  createdby varchar(5),
  created_date timestamp,
  modifiedby varchar(5),
  modified_date timestamp,
  payment_status integer,
  pending_amt numeric(10,0),
  PRIMARY KEY (payment_id)
);
COMMENT ON TABLE transporter_payment_detail IS 'Legacy table LGST_TransporterPaymentDetail';

-- LGST_TransporterPaymentDetails: 3 rows
CREATE TABLE transporter_payment_details (
  payment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  payment_slip_no varchar(50),
  transport_id integer,
  truck_id integer,
  driver_name varchar(500),
  in_date varchar(50),
  in_time varchar(5),
  out_date varchar(50),
  out_time varchar(5),
  detention_paidby varchar(50),
  detention_days integer,
  detention_value numeric(25,2),
  total_freight numeric(25,2),
  advance numeric(25,2),
  hamali numeric(25,2),
  commission numeric(25,2),
  tds numeric(25,2),
  total_adv_freight numeric(25,2),
  less_printing numeric(25,2),
  balance_freight numeric(25,2),
  net_amount numeric(25,2),
  net_paid_amt numeric(15,2),
  labours varchar(500),
  supervisors varchar(500),
  remark varchar(500),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (payment_id)
);
COMMENT ON TABLE transporter_payment_details IS 'Legacy table LGST_TransporterPaymentDetails';

-- LGST_TransporterPaymentEntry: 14 rows
CREATE TABLE transporter_payment_entry (
  trans_payment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  payment_id integer,
  payable_amt numeric(18,2),
  received_amt numeric(18,2),
  received_date date,
  tds numeric(18,2),
  pending_amt numeric(18,2),
  payment_mode varchar(20),
  bank_name varchar(100),
  acc_no_cheque_no varchar(20),
  cheque_date date,
  remark varchar(100),
  is_active smallint,
  created_date timestamp,
  createdby varchar(5),
  modified_date timestamp,
  modifiedby varchar(5),
  PRIMARY KEY (trans_payment_id)
);
COMMENT ON TABLE transporter_payment_entry IS 'Legacy table LGST_TransporterPaymentEntry';

-- LGST_TransporterPaymentLR: 1454 rows
CREATE TABLE transporter_payment_lr (
  payment_lr_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  payment_id integer,
  lr_detail_id integer,
  freight numeric(18,2),
  detention_paidby varchar(50),
  detention_days integer,
  detention_amt numeric(18,2),
  advance numeric(18,2),
  hamali numeric(18,2),
  commision numeric(18,2),
  tds numeric(18,2),
  damage numeric(18,2),
  stationary numeric(18,2),
  balance_freight numeric(18,2),
  isactive smallint,
  createdby varchar(5),
  created_date timestamp,
  modifiedby varchar(5),
  modified_date timestamp,
  pending_freight numeric(10,2),
  reference_no varchar(50),
  PRIMARY KEY (payment_lr_id)
);
COMMENT ON TABLE transporter_payment_lr IS 'Legacy table LGST_TransporterPaymentLR';

-- LGST_TransporterPaymentPaidLR: 0 rows
CREATE TABLE transporter_payment_paid_lr (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  payment_id integer,
  lr_detail_id integer,
  truck_id integer,
  is_lr_copy boolean,
  is_invoice_no boolean,
  is_way_bill boolean,
  is_seal_no boolean,
  is_kata_receipt boolean,
  created_date timestamp,
  createdby varchar(10),
  PRIMARY KEY (id)
);
COMMENT ON TABLE transporter_payment_paid_lr IS 'Legacy table LGST_TransporterPaymentPaidLR';

-- LGST_TransporterRateMatrix: 140 rows
CREATE TABLE transporter_rate_matrix (
  trans_rate_matrix_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  source_id integer,
  destination_id integer,
  trans_truck_type varchar(10),
  rate_amt numeric(18,0),
  createdby integer,
  created_date timestamp,
  modifiedby integer,
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (trans_rate_matrix_id)
);
COMMENT ON TABLE transporter_rate_matrix IS 'Legacy table LGST_TransporterRateMatrix';

-- LGST_Trip: 16498 rows
CREATE TABLE trip (
  trip_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  client_id integer,
  from_city_id integer,
  to_c_ity_id integer,
  description varchar(1000),
  remarks_if_any varchar(200),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  start_date varchar(10),
  end_date varchar(10),
  opening_km numeric(15,0),
  closing_km numeric(15,0),
  is_trip_completed smallint,
  trip_name varchar(100),
  vehicle_arrange_by varchar(200),
  is_empty smallint,
  truck_id integer,
  driver_id integer,
  log_process_id integer,
  isfirst integer,
  islast integer,
  advance numeric(10,0),
  vp_schedule_id integer,
  onward_freight numeric(10,2),
  lr_detail_id integer,
  d_challan_id integer,
  start_time varchar(10),
  end_time varchar(10),
  PRIMARY KEY (trip_id)
);
COMMENT ON TABLE trip IS 'Legacy table LGST_Trip';

-- LGST_Truck: 7443 rows
CREATE TABLE truck (
  truck_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  truck_number varchar(50),
  purchase_date varchar(15),
  chasis_number varchar(10),
  engin_number varchar(50),
  make varchar(50),
  capacity varchar(50),
  fit_number varchar(25),
  gp_number varchar(25),
  fit_date varchar(8),
  gp_date varchar(15),
  fit_due_date varchar(15),
  gp_due_date varchar(15),
  np_number varchar(25),
  tax_number varchar(25),
  np_date varchar(15),
  tax_date varchar(15),
  np_due_date varchar(15),
  tax_due_date varchar(15),
  insurance_company varchar(200),
  insurance_number varchar(25),
  ins_date varchar(15),
  ins_due_date varchar(15),
  tyres integer,
  truck_type varchar(1),
  is_transist smallint,
  remarks varchar(500),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  cft numeric(20,2),
  volumne numeric(20,2),
  extra_diesel_allowed smallint,
  monthly_fixed_exp numeric(20,2),
  rp_no varchar(15),
  truck_capacity varchar(10),
  insurance_amt numeric(25,2),
  transporter integer,
  tax_amt numeric(25,2),
  salary numeric(25,2),
  permit_amt numeric(25,2),
  emi numeric(25,2),
  fitness varchar(8),
  std_avg numeric(10,2),
  trans_truck_type varchar(10),
  fitness_amt integer,
  PRIMARY KEY (truck_id)
);
COMMENT ON TABLE truck IS 'Legacy table LGST_Truck';

-- LGST_TruckAdvancePayment: 3 rows
CREATE TABLE truck_advance_payment (
  truck_advance_payment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  truck_id integer,
  payment_mode integer,
  amount numeric(25,2),
  posting_date varchar(8),
  remark varchar(500),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (truck_advance_payment_id)
);
COMMENT ON TABLE truck_advance_payment IS 'Legacy table LGST_TruckAdvancePayment';

-- LGST_TruckExpense: 0 rows
CREATE TABLE truck_expense (
  trk_exp_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  truck_number integer,
  exp_date varchar(15),
  exp_amount numeric(10,5),
  exp_remarks varchar(500),
  expense_id integer,
  remarks_if_any varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (trk_exp_id)
);
COMMENT ON TABLE truck_expense IS 'Legacy table LGST_TruckExpense';

-- LGST_TruckMaintenaceItem: 0 rows
CREATE TABLE truck_maintenace_item (
  id integer,
  maintenance_id integer,
  particular integer,
  is_checked smallint,
  current_status varchar(50),
  regarding_action varchar(50),
  remark varchar(100)
);
COMMENT ON TABLE truck_maintenace_item IS 'Legacy table LGST_TruckMaintenaceItem';

-- LGST_TruckMaintenance: 0 rows
CREATE TABLE truck_maintenance (
  maintenance_id integer,
  truck_id integer,
  driver_id integer,
  posting_date date,
  opening_km integer,
  preparedby varchar(100),
  checkedby varchar(100),
  authorisedby varchar(100),
  remark varchar(500),
  is_active smallint,
  createdby integer,
  created_date timestamp,
  modifiedby integer,
  modified_date timestamp
);
COMMENT ON TABLE truck_maintenance IS 'Legacy table LGST_TruckMaintenance';

-- LGST_Unit: 75 rows
CREATE TABLE unit (
  unit_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  unit_name varchar(50),
  description varchar(500),
  remarks_if_any varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  is_slab_rate smallint,
  PRIMARY KEY (unit_id)
);
COMMENT ON TABLE unit IS 'Legacy table LGST_Unit';

-- LGST_UserPerRole: 189 rows
CREATE TABLE user_per_role (
  users_per_role_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id integer,
  role_id integer,
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (users_per_role_id)
);
COMMENT ON TABLE user_per_role IS 'Legacy table LGST_UserPerRole';

-- LGST_Users: 189 rows
CREATE TABLE users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_name varchar(50),
  password varchar(50),
  first_name varchar(50),
  middle_name varchar(50),
  last_name varchar(50),
  email varchar(50),
  branch_id integer,
  company_id integer,
  login_count integer,
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  created_by varchar(20),
  is_active smallint,
  PRIMARY KEY (user_id)
);
COMMENT ON TABLE users IS 'Legacy table LGST_Users';

-- LGST_VPLoadItems: 8869 rows
CREATE TABLE vp_load_items (
  vp_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vp_load_id integer,
  lr_detail_id integer,
  grn_item_id integer,
  item_id integer,
  qty integer,
  pending_qty integer,
  created_by varchar(10),
  created_date timestamp,
  modified_by varchar(10),
  modified_date timestamp,
  is_active smallint,
  damage_qty integer,
  PRIMARY KEY (vp_item_id)
);
COMMENT ON TABLE vp_load_items IS 'Legacy table LGST_VPLoadItems';

-- LGST_VPLoadItems_Temp: 1 rows
CREATE TABLE vp_load_items_temp (
  vp_item_id integer,
  vp_load_id integer,
  lr_detail_id integer,
  grn_item_id integer,
  item_id integer,
  qty integer,
  pending_qty integer,
  created_by varchar(10),
  created_date timestamp,
  modified_by varchar(10),
  modified_date timestamp,
  is_active smallint,
  damage_qty integer
);
COMMENT ON TABLE vp_load_items_temp IS 'Legacy table LGST_VPLoadItems_Temp';

-- LGST_VPLoading: 7020 rows
CREATE TABLE vp_loading (
  vp_load_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vp_schedule_id integer,
  mrrr_wagon_id integer,
  wagon_id integer,
  vp_id integer,
  vp_no varchar(15),
  lr_detail_id integer,
  supervisor_id integer,
  createdby varchar(10),
  created_date timestamp,
  modified_by varchar(10),
  modified_date timestamp,
  is_active smallint,
  damage_qty integer,
  labourcharge numeric(10,2),
  labour_id integer,
  is_l_charge_paid smallint,
  payment_date timestamp,
  payment_no varchar(10),
  loading_date date,
  tds_per numeric(5,2),
  tds_amt numeric(10,0),
  branch_id integer,
  payment_paid_by integer,
  PRIMARY KEY (vp_load_id)
);
COMMENT ON TABLE vp_loading IS 'Legacy table LGST_VPLoading';

-- LGST_VPLoading_Temp: 1 rows
CREATE TABLE vp_loading_temp (
  vp_load_id integer,
  vp_schedule_id integer,
  mrrr_wagon_id integer,
  wagon_id integer,
  vp_id integer,
  vp_no varchar(15),
  lr_detail_id integer,
  supervisor_id integer,
  createdby varchar(10),
  created_date timestamp,
  modified_by varchar(10),
  modified_date timestamp,
  is_active smallint,
  damage_qty integer,
  labourcharge numeric(10,2),
  labour_id integer,
  is_l_charge_paid smallint,
  payment_date timestamp,
  payment_no varchar(10),
  loading_date date,
  tds_per numeric(5,2),
  tds_amt numeric(10,0),
  branch_id integer,
  payment_paid_by integer
);
COMMENT ON TABLE vp_loading_temp IS 'Legacy table LGST_VPLoading_Temp';

-- LGST_VPPlanning: 0 rows
CREATE TABLE vp_planning (
  vp_plan_id integer,
  vp_schedule_id integer,
  loading_instruction_url varchar(2000),
  loading_diagram_url varchar(2000),
  loading_summary_url varchar(2000),
  loading_solution_url varchar(2000),
  created_by integer,
  created_date timestamp,
  modified_by integer,
  modified_date timestamp,
  is_active smallint
);
COMMENT ON TABLE vp_planning IS 'Legacy table LGST_VPPlanning';

-- LGST_VPPlanningItem: 0 rows
CREATE TABLE vp_planning_item (
  vp_planning_item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vp_planning_id integer,
  item_id integer,
  lr_detail_id integer,
  qty integer,
  volume numeric(25,2),
  weight numeric(25,0),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  wagon varchar(50),
  lr_item_id integer,
  remaining_qty integer,
  PRIMARY KEY (vp_planning_item_id)
);
COMMENT ON TABLE vp_planning_item IS 'Legacy table LGST_VPPlanningItem';

-- LGST_VPSchedule: 297 rows
CREATE TABLE vp_schedule (
  vp_schedule_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vp_schedule_date varchar(10),
  schedule_title varchar(500),
  source_id integer,
  destination_id integer,
  from_branch_id integer,
  to_branch_id integer,
  is_final smallint,
  is_completed smallint,
  is_mrrr smallint,
  is_s_rake smallint,
  is_d_rake smallint,
  is_sdcwc smallint,
  is_ddcwc smallint,
  is_dgrn smallint,
  is_rake_closed smallint,
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  rake_no varchar(20),
  PRIMARY KEY (vp_schedule_id)
);
COMMENT ON TABLE vp_schedule IS 'Legacy table LGST_VPSchedule';

-- LGST_VPScheduleCount: 3010 rows
CREATE TABLE vp_schedule_count (
  vp_schedule_count_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vp_schedule_id integer,
  wagon_type varchar(50),
  wagon_id integer,
  count integer,
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (vp_schedule_count_id)
);
COMMENT ON TABLE vp_schedule_count IS 'Legacy table LGST_VPScheduleCount';

-- LGST_VehicleLoadType: 8 rows
CREATE TABLE vehicle_load_type (
  vehicle_load_type_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vehicle_load_type_name varchar(50),
  description text,
  remarks_if_any varchar(200),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (vehicle_load_type_id)
);
COMMENT ON TABLE vehicle_load_type IS 'Legacy table LGST_VehicleLoadType';

-- LGST_Wagon: 9 rows
CREATE TABLE wagon (
  wagon_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  wagon_name varchar(100),
  wagon_type varchar(50),
  description varchar(500),
  height numeric(25,2),
  width numeric(25,2),
  length numeric(25,2),
  weight numeric(25,2),
  created_by varchar(20),
  created_date timestamp,
  modified_by varchar(20),
  modified_date timestamp,
  is_active smallint,
  PRIMARY KEY (wagon_id)
);
COMMENT ON TABLE wagon IS 'Legacy table LGST_Wagon';

-- Results: 0 rows
CREATE TABLE results (
  row_number bigint,
  order_id varchar(50),
  initiate_order_id integer,
  from_branch_id integer,
  to_branch_id integer,
  client_id integer,
  city_id integer,
  order_status varchar(50),
  customer_name varchar(100),
  customr_address text,
  from_branch varchar(50),
  to_branch varchar(50),
  city_name varchar(50),
  i_pickup_date varchar(30),
  order_status_id integer,
  from_branch_address varchar(500),
  to_branch_address varchar(500),
  io_date varchar(10),
  remaining_truck_qty integer,
  truck_quantity integer,
  is_order_completed smallint
);
COMMENT ON TABLE results IS 'Legacy table Results';
